/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeUI.framework/HomeUI
 */

@interface HUColorPaletteView : UIView <HUQuickControlInteractiveView, UIGestureRecognizerDelegate> {
    double  _circleRadius;
    HFColorPalette * _colorPalette;
    NSArray * _colorSwatchViews;
    UILongPressGestureRecognizer * _gestureRecognizer;
    <HUQuickControlViewInteractionDelegate> * _interactionDelegate;
    HUQuickControlSimpleViewProfile * _profile;
    HFColorPaletteColor * _selectedColor;
    NSNumber * _trackingColorIndex;
    bool  _userInteractionActive;
}

@property (nonatomic) double circleRadius;
@property (nonatomic, retain) HFColorPalette *colorPalette;
@property (nonatomic, copy) NSArray *colorSwatchViews;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) UILongPressGestureRecognizer *gestureRecognizer;
@property (readonly) unsigned long long hash;
@property (nonatomic) <HUQuickControlViewInteractionDelegate> *interactionDelegate;
@property (nonatomic, retain) HUQuickControlSimpleViewProfile *profile;
@property (nonatomic, retain) HFColorPaletteColor *selectedColor;
@property (nonatomic) long long sizeSubclass;
@property (readonly) Class superclass;
@property (nonatomic, retain) NSNumber *trackingColorIndex;
@property (getter=isUserInteractionActive, nonatomic) bool userInteractionActive;
@property (nonatomic, retain) id value;

- (void).cxx_destruct;
- (void)_handleGesture:(id)arg1;
- (void)_rebuildColorSwatchViews;
- (void)_setSelectedColor:(id)arg1 notifyDelegate:(bool)arg2 updateSelectionState:(bool)arg3;
- (void)_updateColorSelectionAnimated:(bool)arg1;
- (void)beginUserInteractionWithFirstTouchGestureRecognizer:(id)arg1;
- (double)circleRadius;
- (id)colorPalette;
- (id)colorSwatchViews;
- (id)gestureRecognizer;
- (bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (id)initWithProfile:(id)arg1;
- (id)initWithProfile:(id)arg1 colorPalette:(id)arg2;
- (id)interactionDelegate;
- (bool)isUserInteractionActive;
- (void)layoutSubviews;
- (id)profile;
- (id)selectedColor;
- (void)setCircleRadius:(double)arg1;
- (void)setColorPalette:(id)arg1;
- (void)setColorSwatchViews:(id)arg1;
- (void)setGestureRecognizer:(id)arg1;
- (void)setInteractionDelegate:(id)arg1;
- (void)setProfile:(id)arg1;
- (void)setSelectedColor:(id)arg1;
- (void)setTrackingColorIndex:(id)arg1;
- (void)setUserInteractionActive:(bool)arg1;
- (void)setValue:(id)arg1;
- (id)trackingColorIndex;
- (id)value;

@end
