/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeUI.framework/HomeUI
 */

@interface HUInstructionsCell : UITableViewCell <HUCellProtocol> {
    UIButton * _actionButton;
    NSArray * _constraints;
    <HUInstructionsCellDelegate> * _delegate;
    UILabel * _descriptionLabel;
    double  _iconHeight;
    UIStackView * _iconStackView;
    HFItem * _item;
    HUGridLayoutOptions * _layoutOptions;
    UILabel * _titleLabel;
}

@property (nonatomic, retain) UIButton *actionButton;
@property (nonatomic, retain) NSArray *constraints;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <HUInstructionsCellDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) UILabel *descriptionLabel;
@property (readonly) unsigned long long hash;
@property (nonatomic) double iconHeight;
@property (nonatomic, retain) UIStackView *iconStackView;
@property (nonatomic, retain) HFItem *item;
@property (nonatomic, retain) HUGridLayoutOptions *layoutOptions;
@property (readonly) Class superclass;
@property (nonatomic, retain) UILabel *titleLabel;

- (void).cxx_destruct;
- (void)_actionButtonTapped:(id)arg1;
- (id)actionButton;
- (id)constraints;
- (id)delegate;
- (id)descriptionLabel;
- (void)didMoveToSuperview;
- (double)iconHeight;
- (id)iconStackView;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (id)item;
- (id)layoutOptions;
- (void)layoutSubviews;
- (void)setActionButton:(id)arg1;
- (void)setConstraints:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setDescriptionLabel:(id)arg1;
- (void)setIconHeight:(double)arg1;
- (void)setIconStackView:(id)arg1;
- (void)setItem:(id)arg1;
- (void)setLayoutOptions:(id)arg1;
- (void)setTitleLabel:(id)arg1;
- (id)titleLabel;
- (void)updateConstraints;
- (void)updateUIWithAnimation:(bool)arg1;

@end
