/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeUI.framework/HomeUI
 */

@interface HUInstructionsItem : HFStaticItem

- (id)initWithStyle:(unsigned long long)arg1 title:(id)arg2 description:(id)arg3 icons:(id)arg4 actionButtonTitle:(id)arg5;

@end
