/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeUI.framework/HomeUI
 */

@interface HUQuickControlSliderGestureTransformer : NSObject {
    HUQuickControlPanningContext * _context;
    double  _currentSliderValue;
    <HUQuickControlSliderGestureTransformerDelegate> * _delegate;
    UIGestureRecognizer * _gestureRecognizer;
    bool  _hasRecognizedSignificantSliderMovement;
    bool  _ignoreTouches;
    double  _referenceSliderValue;
    struct CGPoint { 
        double x; 
        double y; 
    }  _referenceTouchLocation;
}

@property (nonatomic, readonly) HUQuickControlPanningContext *context;
@property (nonatomic) double currentSliderValue;
@property (nonatomic) <HUQuickControlSliderGestureTransformerDelegate> *delegate;
@property (nonatomic, retain) UIGestureRecognizer *gestureRecognizer;
@property (nonatomic) bool hasRecognizedSignificantSliderMovement;
@property (nonatomic) bool ignoreTouches;
@property (nonatomic) double referenceSliderValue;
@property (nonatomic) struct CGPoint { double x1; double x2; } referenceTouchLocation;

- (void).cxx_destruct;
- (void)_handleGesturePan:(id)arg1;
- (void)_handleSliderValuePan:(struct CGPoint { double x1; double x2; })arg1;
- (double)_rawSliderValueForLocation:(struct CGPoint { double x1; double x2; })arg1;
- (bool)_shouldIgnoreAllGestures;
- (id)context;
- (double)currentSliderValue;
- (void)dealloc;
- (id)delegate;
- (id)gestureRecognizer;
- (bool)hasRecognizedSignificantSliderMovement;
- (bool)ignoreTouches;
- (id)initWithGestureRecognizer:(id)arg1 context:(id)arg2;
- (double)referenceSliderValue;
- (struct CGPoint { double x1; double x2; })referenceTouchLocation;
- (void)setCurrentSliderValue:(double)arg1;
- (void)setDelegate:(id)arg1;
- (void)setGestureRecognizer:(id)arg1;
- (void)setHasRecognizedSignificantSliderMovement:(bool)arg1;
- (void)setIgnoreTouches:(bool)arg1;
- (void)setReferenceSliderValue:(double)arg1;
- (void)setReferenceTouchLocation:(struct CGPoint { double x1; double x2; })arg1;

@end
