/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeUI.framework/HomeUI
 */

@interface HUSetupServiceOptionCell : UITableViewCell <HUDisableableCellProtocol> {
    bool  _checked;
    bool  _disabled;
    UIView * _iconContainerView;
    <HFIconDescriptor> * _iconDescriptor;
    HUIconView * _iconView;
    bool  _suggestion;
    UILabel * _titleLabel;
}

@property (getter=isChecked, nonatomic) bool checked;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (getter=isDisabled, nonatomic) bool disabled;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) UIView *iconContainerView;
@property (nonatomic, copy) <HFIconDescriptor> *iconDescriptor;
@property (nonatomic, retain) HUIconView *iconView;
@property (getter=isSuggestion, nonatomic) bool suggestion;
@property (readonly) Class superclass;
@property (nonatomic, copy) NSString *title;
@property (nonatomic, retain) UILabel *titleLabel;

- (void).cxx_destruct;
- (id)iconContainerView;
- (id)iconDescriptor;
- (id)iconView;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (bool)isChecked;
- (bool)isDisabled;
- (bool)isSuggestion;
- (void)prepareForReuse;
- (void)setChecked:(bool)arg1;
- (void)setDisabled:(bool)arg1;
- (void)setIconContainerView:(id)arg1;
- (void)setIconDescriptor:(id)arg1;
- (void)setIconView:(id)arg1;
- (void)setSuggestion:(bool)arg1;
- (void)setTitle:(id)arg1;
- (void)setTitleLabel:(id)arg1;
- (id)title;
- (id)titleLabel;

@end
