/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PassKitCore.framework/PassKitCore
 */

@interface ASRiskScorer : NSObject <ASRiskScoring> {
    NSXPCConnection * _connection;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

+ (id)sharedInstance;

- (void).cxx_destruct;
- (void)getScoreMessageUsingSettings:(id)arg1 completion:(id /* block */)arg2;
- (id)initWithServiceName:(id)arg1;
- (id)scoreMessageUsingSettings:(id)arg1 error:(id*)arg2;

@end
