/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PassKitCore.framework/PassKitCore
 */

@interface PKPaymentProvisioningResponse : PKPaymentWebServiceResponse {
    NSURL * _passURL;
}

@property (nonatomic, copy) NSURL *passURL;

- (void).cxx_destruct;
- (id)initWithData:(id)arg1;
- (id)passURL;
- (void)setPassURL:(id)arg1;

@end
