/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PassKitCore.framework/PassKitCore
 */

@interface PKPaymentRemoteCredential : PKPaymentCredential {
    NSString * _identifier;
    NSArray * _metadata;
    NSURL * _passURL;
    long long  _status;
    NSArray * _summaryMetadata;
}

@property (nonatomic, copy) NSString *identifier;
@property (nonatomic, readonly, copy) NSArray *metadata;
@property (nonatomic, copy) NSURL *passURL;
@property (nonatomic) long long status;
@property (nonatomic, readonly, copy) NSArray *summaryMetadata;

- (void).cxx_destruct;
- (id)identifier;
- (id)init;
- (id)initWithDictionary:(id)arg1;
- (id)metadata;
- (id)passURL;
- (void)setIdentifier:(id)arg1;
- (void)setPassURL:(id)arg1;
- (void)setStatus:(long long)arg1;
- (long long)status;
- (id)summaryMetadata;

@end
