/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NetworkServiceProxy.framework/NetworkServiceProxy
 */

@interface NPEdgeLatency : NSObject <NSSecureCoding> {
    unsigned long long  _edgeIndex;
    unsigned long long  _roundTripTime;
}

@property unsigned long long edgeIndex;
@property unsigned long long roundTripTime;

+ (bool)supportsSecureCoding;

- (long long)compare:(id)arg1;
- (unsigned long long)edgeIndex;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithRTT:(unsigned long long)arg1 edgeIndex:(unsigned long long)arg2;
- (unsigned long long)roundTripTime;
- (void)setEdgeIndex:(unsigned long long)arg1;
- (void)setRoundTripTime:(unsigned long long)arg1;

@end
