/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NetworkServiceProxy.framework/NetworkServiceProxy
 */

@interface NPTuscanyOnRamp : NSObject <NSSecureCoding> {
    NSData * _dayPass;
    NSDate * _dayPassCreationDate;
    double  _dayPassHardExpiry;
    NWHostEndpoint * _daypassEndpoint;
    unsigned long long  _maxFrameSize;
    NSDate * _retryDate;
    NWEndpoint * _tuscanyEndpoint;
    NWEndpoint * _tuscanyUDPEndpoint;
}

@property (retain) NSData *dayPass;
@property (readonly) NSDate *dayPassCreationDate;
@property double dayPassHardExpiry;
@property (readonly) NWHostEndpoint *daypassEndpoint;
@property (readonly) bool isDayPassExpired;
@property (readonly) unsigned long long maxFrameSize;
@property (retain) NSDate *retryDate;
@property (readonly) NWEndpoint *tuscanyEndpoint;
@property (readonly) NWEndpoint *tuscanyUDPEndpoint;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)dayPass;
- (id)dayPassCreationDate;
- (double)dayPassHardExpiry;
- (id)daypassEndpoint;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithEndpointString:(id)arg1;
- (void)invalidateDayPass;
- (bool)isDayPassExpired;
- (bool)isDayPassPastExpiry:(double)arg1;
- (bool)isEqual:(id)arg1;
- (unsigned long long)maxFrameSize;
- (void)refreshDayPassWithWaldoDelegate:(id)arg1 softExpiry:(double)arg2 retryInterval:(double)arg3 completionHandler:(id /* block */)arg4;
- (id)retryDate;
- (void)setDayPass:(id)arg1;
- (void)setDayPassHardExpiry:(double)arg1;
- (void)setRetryDate:(id)arg1;
- (id)tuscanyEndpoint;
- (id)tuscanyUDPEndpoint;

@end
