/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MobileCoreServices.framework/MobileCoreServices
 */

@interface _LSConcreteLazyPropertyList : _LSLazyPropertyList {
    NSData * _plistData;
}

+ (bool)supportsSecureCoding;

- (id)_loadPropertyListPeeking:(bool)arg1;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithPropertyListData:(id)arg1;

@end
