/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MobileCoreServices.framework/MobileCoreServices
 */

@interface _LSDOpenService : _LSDService

+ (id)XPCInterface;
+ (Class)clientClass;
+ (id)dispatchQueue;
+ (id)serviceName;

@end
