/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MobileCoreServices.framework/MobileCoreServices
 */

@interface _LSDService : NSObject <NSXPCListenerDelegate> {
    NSXPCListener * _listener;
}

@property (readonly) NSXPCListener *XPCListener;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

+ (bool)XPCConnectionIsAlwaysPrivileged;
+ (id)XPCConnectionToService;
+ (id)XPCInterface;
+ (id)XPCProxyWithErrorHandler:(id /* block */)arg1;
+ (id)XPCProxyWithSelector:(SEL)arg1 errorHandler:(id /* block */)arg2;
+ (id)allServiceClasses;
+ (void)beginListeningWithAllServices;
+ (Class)clientClass;
+ (id)dispatchQueue;
+ (bool)isEnabled;
+ (id)serviceName;
+ (id)synchronousXPCProxyWithErrorHandler:(id /* block */)arg1;

- (id)XPCListener;
- (id)initWithXPCListener:(id)arg1;
- (bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;

@end
