/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ReplayKit.framework/ReplayKit
 */

@interface RPBroadcastController : NSObject {
    <RPBroadcastControllerDelegate> * _broadcastControllerDelegate;
    NSURL * _broadcastURL;
    bool  _broadcasting;
    NSDictionary * _serviceInfo;
}

@property (nonatomic) <RPBroadcastControllerDelegate> *broadcastControllerDelegate;
@property (nonatomic, readonly) NSURL *broadcastURL;
@property (getter=isBroadcasting, nonatomic, readonly) bool broadcasting;
@property (nonatomic, retain) NSDictionary *serviceInfo;

- (void).cxx_destruct;
- (id)broadcastControllerDelegate;
- (id)broadcastURL;
- (void)dealloc;
- (void)finishBroadcastWithHandler:(id /* block */)arg1;
- (bool)isBroadcasting;
- (void)pauseBroadcast;
- (void)resumeBroadcast;
- (id)serviceInfo;
- (void)setBroadcastControllerDelegate:(id)arg1;
- (void)setServiceInfo:(id)arg1;
- (void)startBroadcastWithHandler:(id /* block */)arg1;

@end
