/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ReplayKit.framework/ReplayKit
 */

@interface RPBroadcastActivityExtensionHostContext : NSExtensionContext <RPBroadcastActivityCommunicationHostProtocol> {
    RPBroadcastActivityHostViewController * _hostViewController;
}

@property (nonatomic) RPBroadcastActivityHostViewController *hostViewController;

+ (id)_extensionAuxiliaryHostProtocol;
+ (id)_extensionAuxiliaryVendorProtocol;

- (void).cxx_destruct;
- (oneway void)extensionDidFinishWithLaunchURL:(id)arg1 cancelled:(bool)arg2;
- (id)extensionObjectProxy;
- (id)hostViewController;
- (oneway void)presentationInfoWithCompletion:(id /* block */)arg1;
- (void)setHostViewController:(id)arg1;

@end
