/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreSuggestionsInternals.framework/CoreSuggestionsInternals
 */

@interface SGDPowerLog : NSObject

+ (void)endDissectionOfMessage:(id)arg1 inContext:(unsigned long long)arg2;
+ (void)logPrewarmWithLastPrewarmTime:(double)arg1;
+ (void)startDissectionOfMessage:(id)arg1 inContext:(unsigned long long)arg2;

@end
