/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CVML.framework/CVML
 */

@interface CVMLPixelBufferCGImageSourceConverter : CVMLPixelBufferCoreGraphicsConverter {
    struct CGImageSource { } * _imageSource;
}

- (struct CGImage { }*)_subsampledImageForScale:(double)arg1 remainingScale:(double*)arg2 appliedScale:(double*)arg3 error:(id*)arg4;
- (void)dealloc;
- (id)init;
- (id)initWithData:(id)arg1;
- (id)initWithImageSource:(struct CGImageSource { }*)arg1;
- (id)initWithURL:(id)arg1;
- (id)newBufferBestFitInWidth:(unsigned long long)arg1 height:(unsigned long long)arg2 format:(unsigned int)arg3 error:(id*)arg4;
- (id)newCroppedBufferWithWidth:(unsigned long long)arg1 height:(unsigned long long)arg2 format:(unsigned int)arg3 cropRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg4 error:(id*)arg5;

@end
