/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CVML.framework/CVML
 */

@interface CVMLPixelBufferConverter : NSObject {
    unsigned long long  _height;
    long long  _orientationToApply;
    unsigned long long  _rasterHeight;
    unsigned long long  _rasterWidth;
    unsigned long long  _width;
}

@property (readonly) unsigned long long height;
@property (readonly) long long orientationToApply;
@property (readonly) unsigned long long rasterHeight;
@property (readonly) unsigned long long rasterWidth;
@property (readonly) unsigned long long width;

- (struct CGColorSpace { }*)_colorspaceForFormat:(unsigned int)arg1;
- (bool)_failWithCVStatus:(int)arg1 format:(unsigned int)arg2 message:(id)arg3 error:(id*)arg4;
- (double)_scaleForBestFitInWidth:(unsigned long long)arg1 height:(unsigned long long)arg2 resultWidth:(unsigned long long*)arg3 resultHeight:(unsigned long long*)arg4;
- (double)_scaleForCropRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 scaledToWidth:(unsigned long long)arg2 height:(unsigned long long)arg3 adjustedCropRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; }*)arg4;
- (unsigned long long)height;
- (id)init;
- (id)initWithOrientationToApply:(long long)arg1 rasterWidth:(unsigned long long)arg2 rasterHeight:(unsigned long long)arg3;
- (id)newBufferBestFitInWidth:(unsigned long long)arg1 height:(unsigned long long)arg2 format:(unsigned int)arg3 error:(id*)arg4;
- (id)newCroppedBufferWithWidth:(unsigned long long)arg1 height:(unsigned long long)arg2 format:(unsigned int)arg3 cropRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg4 error:(id*)arg5;
- (long long)orientationToApply;
- (unsigned long long)rasterHeight;
- (unsigned long long)rasterWidth;
- (unsigned long long)width;

@end
