/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CVML.framework/CVML
 */

@interface CVMLPixelBufferCoreImageConverter : CVMLPixelBufferConverter {
    CIImage * _image;
}

- (void).cxx_destruct;
- (id)_preparePixelBufferWithImage:(id)arg1 originalToPixelBufferTransform:(struct CGAffineTransform { double x1; double x2; double x3; double x4; double x5; double x6; })arg2 width:(unsigned long long)arg3 height:(unsigned long long)arg4 format:(unsigned int)arg5 error:(id*)arg6;
- (id)_preparePixelBufferWithOriginalToPixelBufferTransform:(struct CGAffineTransform { double x1; double x2; double x3; double x4; double x5; double x6; })arg1 width:(unsigned long long)arg2 height:(unsigned long long)arg3 format:(unsigned int)arg4 error:(id*)arg5;
- (id)init;
- (id)initWithCVPixelBuffer:(struct __CVBuffer { }*)arg1 orientation:(long long)arg2;
- (id)initWithImage:(id)arg1 orientation:(long long)arg2;
- (id)newBufferBestFitInWidth:(unsigned long long)arg1 height:(unsigned long long)arg2 format:(unsigned int)arg3 error:(id*)arg4;
- (id)newCroppedBufferWithWidth:(unsigned long long)arg1 height:(unsigned long long)arg2 format:(unsigned int)arg3 cropRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg4 error:(id*)arg5;

@end
