/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CVML.framework/CVML
 */

@interface CVMLImageGrouper : NSObject

+ (id)groupImageprints:(id)arg1 withOptions:(id)arg2 cancellationSemaphore:(id)arg3 error:(id*)arg4;

@end
