/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ResponseKit.framework/ResponseKit
 */

@interface RKProactiveGrammar : NSObject

+ (id)sharedManager;
+ (bool)supportsLanguage:(id)arg1;

- (id)copyAttributedTokenForText:(id)arg1 forLanguage:(id)arg2;
- (void)dealloc;
- (void*)getLanguageModel:(id)arg1;
- (id)init;

@end
