/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ResponseKit.framework/ResponseKit
 */

@interface RKUtilities : NSObject

+ (bool)isLanguageSupportedByNSLinguisticTaggerForLanguageIdentification:(id)arg1;
+ (id)normalizeForPersonalization:(id)arg1;
+ (id)removeEmoji:(id)arg1;
+ (id)stripDiacritics:(id)arg1;
+ (id)stripEmojiSkinTones:(id)arg1;

@end
