/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CloudKitDaemon.framework/CloudKitDaemon
 */

@interface CKDFetchServerEnvironmentOperation : CKDOperation {
    long long  _environment;
}

@property (nonatomic) long long environment;

- (id)activityCreate;
- (long long)environment;
- (void)fillOutOperationResult:(id)arg1;
- (id)initWithOperationInfo:(id)arg1 clientContext:(id)arg2;
- (void)main;
- (Class)operationResultClass;
- (void)setEnvironment:(long long)arg1;
- (bool)shouldCheckAppVersion;

@end
