/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
 */

@interface CKBrowserSelectionLayoutAttributes : UICollectionViewLayoutAttributes {
    bool  _jittering;
    double  _offsetFactorX;
    double  _offsetFactorY;
    double  _offsetX;
    double  _offsetY;
    bool  _showingDeleteButton;
}

@property (getter=isJittering, nonatomic) bool jittering;
@property (nonatomic) double offsetFactorX;
@property (nonatomic) double offsetFactorY;
@property (nonatomic) double offsetX;
@property (nonatomic) double offsetY;
@property (getter=isShowingDeleteButton, nonatomic) bool showingDeleteButton;

- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)debugDescription;
- (bool)isEqual:(id)arg1;
- (bool)isJittering;
- (bool)isShowingDeleteButton;
- (double)offsetFactorX;
- (double)offsetFactorY;
- (double)offsetX;
- (double)offsetY;
- (void)setJittering:(bool)arg1;
- (void)setOffsetFactorX:(double)arg1;
- (void)setOffsetFactorY:(double)arg1;
- (void)setOffsetX:(double)arg1;
- (void)setOffsetY:(double)arg1;
- (void)setShowingDeleteButton:(bool)arg1;

@end
