/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Search.framework/Search
 */

@interface SPFeedbackSpeechResult : NSObject <NSSecureCoding> {
    unsigned long long  _spotlightResultsSize;
    bool  _stable;
    NSString * _text;
    double  _timestamp;
    unsigned long long  _webResultsSize;
}

@property (nonatomic) unsigned long long spotlightResultsSize;
@property (nonatomic) bool stable;
@property (nonatomic, retain) NSString *text;
@property (nonatomic) double timestamp;
@property (nonatomic) unsigned long long webResultsSize;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithText:(id)arg1 stable:(bool)arg2 timestamp:(double)arg3 webResultsSize:(unsigned long long)arg4 spotlightResultsSize:(unsigned long long)arg5;
- (void)setSpotlightResultsSize:(unsigned long long)arg1;
- (void)setStable:(bool)arg1;
- (void)setText:(id)arg1;
- (void)setTimestamp:(double)arg1;
- (void)setWebResultsSize:(unsigned long long)arg1;
- (unsigned long long)spotlightResultsSize;
- (bool)stable;
- (id)text;
- (double)timestamp;
- (unsigned long long)webResultsSize;

@end
