/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Search.framework/Search
 */

@interface SPSearchResultSection : PBCodable <NSCopying> {
    NSString * _category;
    NSString * _displayIdentifier;
    unsigned int  _domain;
    int  _flags;
    struct { 
        unsigned int domain : 1; 
        unsigned int flags : 1; 
    }  _has;
    NSArray * _hiddenExtResults;
    NSString * _icon;
    bool  _immutable;
    bool  _isGlanceCategory;
    NSMutableOrderedSet * _resultSet;
    NSString * _resultSetIdentifier;
    NSString * _scheme;
}

@property (nonatomic, retain) NSString *category;
@property (nonatomic, retain) NSString *displayIdentifier;
@property (nonatomic) unsigned int domain;
@property (nonatomic) int flags;
@property (nonatomic, readonly) bool hasCategory;
@property (nonatomic, readonly) bool hasDisplayIdentifier;
@property (nonatomic) bool hasDomain;
@property (nonatomic) bool hasFlags;
@property (nonatomic, readonly) bool hasIcon;
@property (nonatomic, readonly) bool hasResults;
@property (nonatomic, readonly) bool hasScheme;
@property (nonatomic, retain) NSArray *hiddenExtResults;
@property (nonatomic, retain) NSString *icon;
@property (readonly) bool immutable;
@property (nonatomic) bool isGlanceCategory;
@property (nonatomic, retain) NSString *resultSetIdentifier;
@property (nonatomic, retain) NSString *scheme;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (void)addHiddenExtResult:(id)arg1;
- (void)addResults:(id)arg1;
- (void)addResults:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)addResultsFromArray:(id)arg1;
- (id)category;
- (void)clearResults;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (id)displayIdentifier;
- (unsigned int)domain;
- (void)encodeWithCoder:(id)arg1;
- (int)flags;
- (bool)hasCategory;
- (bool)hasDisplayIdentifier;
- (bool)hasDomain;
- (bool)hasFlags;
- (bool)hasIcon;
- (bool)hasResults;
- (bool)hasScheme;
- (unsigned long long)hash;
- (id)hiddenExtResults;
- (id)icon;
- (bool)immutable;
- (unsigned long long)indexOfResult:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (bool)isEqual:(id)arg1;
- (bool)isGlanceCategory;
- (void)makeImmutable;
- (bool)readFrom:(id)arg1;
- (void)removeResults:(id)arg1;
- (void)removeResultsAtIndex:(unsigned long long)arg1;
- (void)removeResultsInArray:(id)arg1;
- (void)replaceResultsAtIndex:(unsigned long long)arg1 withResults:(id)arg2;
- (id)resultSet;
- (id)resultSetIdentifier;
- (id)results;
- (id)resultsAtIndex:(unsigned long long)arg1;
- (unsigned long long)resultsCount;
- (id)scheme;
- (void)serializeTo:(id)arg1;
- (bool)serialized;
- (void)setCategory:(id)arg1;
- (void)setDisplayIdentifier:(id)arg1;
- (void)setDomain:(unsigned int)arg1;
- (void)setFlags:(int)arg1;
- (void)setHasDomain:(bool)arg1;
- (void)setHasFlags:(bool)arg1;
- (void)setHiddenExtResults:(id)arg1;
- (void)setIcon:(id)arg1;
- (void)setIsGlanceCategory:(bool)arg1;
- (void)setResultSetIdentifier:(id)arg1;
- (void)setScheme:(id)arg1;
- (void)sortUsingComparator:(id /* block */)arg1;
- (void)writeTo:(id)arg1;

@end
