/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Search.framework/Search
 */

@interface SPSearchResultDeserializerConcrete : PBDataReader {
    unsigned long long  _byteVector;
    bool  _munmapAtDealloc;
}

@property unsigned long long byteVector;
@property bool munmapAtDealloc;

- (unsigned long long)byteVector;
- (void)dealloc;
- (bool)deserializeNextSection:(id*)arg1;
- (id)initWithMallocRegion:(unsigned long long)arg1 length:(unsigned long long)arg2;
- (id)initWithMappedRegion:(unsigned long long)arg1 length:(unsigned long long)arg2;
- (id)initWithSerializer:(id)arg1;
- (bool)munmapAtDealloc;
- (void)setByteVector:(unsigned long long)arg1;
- (void)setMunmapAtDealloc:(bool)arg1;

@end
