/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UpNextWidget.framework/UpNextWidget
 */

@interface UpNextWidget.DetailedViewController : UIViewController {
    void detailedView;
    void largeEventView;
    void largeReminderView;
    void lastKnownHypothesis;
    void lastKnownMapImage;
    void outstandingHypothesizer;
    void outstandingSnapshotter;
    void previousSize;
    void showExpandedMode;
    void smallElementsView;
}

@property (nonatomic, retain) EKTravelEngineHypothesis *lastKnownHypothesis;
@property (nonatomic, retain) UIImage *lastKnownMapImage;
@property (nonatomic) bool showExpandedMode;

- (id /* block */).cxx_destruct;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)lastKnownHypothesis;
- (id)lastKnownMapImage;
- (void)loadView;
- (void)refreshWithAlarms:(id)arg1 events:(id)arg2 reminders:(id)arg3;
- (void)restoreWithHypothesis:(id)arg1 mapImage:(id)arg2;
- (void)setLastKnownHypothesis:(id)arg1;
- (void)setLastKnownMapImage:(id)arg1;
- (void)setShowExpandedMode:(bool)arg1;
- (bool)showExpandedMode;
- (void)systemLayoutFittingSizeDidChangeForChildContentContainer:(id)arg1;

@end
