/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSUnitDuration : NSDimension <NSSecureCoding>

+ (id)baseUnit;
+ (id)hours;
+ (id)minutes;
+ (id)seconds;

@end
