/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSUnit : NSObject <NSCopying, NSSecureCoding> {
    NSString * _symbol;
}

@property (readonly, copy) NSString *symbol;

// Image: /System/Library/Frameworks/Foundation.framework/Foundation

+ (bool)supportsSecureCoding;

- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithSymbol:(id)arg1;
- (bool)isEqual:(id)arg1;
- (id)symbol;

// Image: /System/Library/Frameworks/HealthKit.framework/HealthKit

+ (Class)hk_lengthUnitClass;
+ (SEL)hk_selectorForMethodName:(id)arg1;
+ (id)hk_unitForHKUnit:(id)arg1;

- (id)hk_unitRepresentation;

@end
