/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ToneLibrary.framework/ToneLibrary
 */

@interface TLCapabilitiesManager : NSObject {
    NSDictionary * _deviceCodeNameSimplicationMapping;
    bool  _isAlertToneStoreAvailable;
    bool  _isRingtoneStoreAvailable;
}

@property (getter=isAlertToneStoreAvailable, nonatomic, readonly) bool alertToneStoreAvailable;
@property (nonatomic, readonly) NSString *deviceCodeName;
@property (getter=isFakingSynchronizedVibrationCapability, nonatomic, readonly) bool fakingSynchronizedVibrationCapability;
@property (nonatomic, readonly) bool hasSynchronizedVibrationsCapability;
@property (nonatomic, readonly) bool hasUserGeneratedVibrationsCapability;
@property (nonatomic, readonly) bool hasVibratorCapability;
@property (getter=isRingtoneStoreAvailable, nonatomic, readonly) bool ringtoneStoreAvailable;
@property (nonatomic, readonly) NSString *simplifiedDeviceCodeName;

+ (id)sharedCapabilitiesManager;

- (void).cxx_destruct;
- (void)_checkRingtoneStoreAvailability;
- (void)_handleStoreAvailableItemKindsChangedNotification:(id)arg1;
- (bool)_hasSynchronizedVibrationsCapability;
- (bool)_hasTelephonyCapability;
- (void)dealloc;
- (id)deviceCodeName;
- (bool)hasSynchronizedVibrationsCapability;
- (bool)hasUserGeneratedVibrationsCapability;
- (bool)hasVibratorCapability;
- (id)init;
- (bool)isAlertToneStoreAvailable;
- (bool)isFakingSynchronizedVibrationCapability;
- (bool)isRingtoneStoreAvailable;
- (id)simplifiedDeviceCodeName;

@end
