/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NCLaunchStats.framework/NCLaunchStats
 */

@interface NCLaunchStats : NSObject {
    id /* block */  asyncRecommendHandler;
    bool  backgroundAppRefreshSwitchedOn;
    CDAttribute * bundleAttr;
    int  classCLockedToken;
    CDBudget * dataBudget;
    CDBudget * energyBudget;
    NSDate * fireWakeupDate;
    NSDate * forecastStartDate;
    bool  isClassCLocked;
    bool  kEnableSyslog;
    unsigned int  kTimeGuardBand;
    NSDate * lastTriggerTime;
    NSMutableDictionary * launchTracker;
    NSObject<OS_dispatch_queue> * ncLaunchStatsQueue;
    long long  numPrewarmedLaunches;
    long long  numRepeatedPrewarms;
    NSMutableDictionary * prewarmDurationTracker;
    NSMutableDictionary * prewarmTimeTracker;
    id /* block */  recommendHandler;
    NSMutableDictionary * seqTracker;
    CDSession * sessionDuet;
    NSMutableDictionary * slotToWidgetMap;
    CDAttribute * userEventAttr;
    CDDHistoryWindow * widgetHistoryWindow;
}

- (void).cxx_destruct;
- (void)addSlot:(unsigned long long)arg1 forWidget:(id)arg2;
- (void)complete:(id)arg1;
- (void)dealloc;
- (void)endEvent:(id)arg1;
- (void)getPredictedSlots;
- (id)init;
- (void)initAfterClassCUnlocked;
- (void)log:(id)arg1;
- (void)ncTriggerObserver:(id)arg1;
- (void)preWarmHasEnded:(id)arg1 withResult:(unsigned long long)arg2 withTriggerType:(int)arg3 withSequence:(unsigned long long)arg4;
- (void)preWarmHasStarted:(id)arg1 withResult:(unsigned long long)arg2 withTriggerType:(int)arg3 withSequence:(unsigned long long)arg4;
- (void)recordPrewarmStatisticsRaw:(id)arg1;
- (void)setNCLaunchRecommendationHandler:(id /* block */)arg1;
- (void)setNCLaunchRecommendationHandlerWithCompletion:(id /* block */)arg1;
- (void)startEvent:(id)arg1;
- (void)updateBARSwitch;
- (id)widgetsForDate:(id)arg1;
- (id)widgetsForSlot:(unsigned long long)arg1;

@end
