/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreRecognition.framework/CoreRecognition
 */

@interface CRAlignmentLayer : CALayer {
    CATextLayer * _cardNumberLayer;
    CATextLayer * _cardholderNameLayer;
    CATextLayer * _expirationDateLayer;
    CALayer * _infoLayer;
    CATextLayer * _instructionLayer;
    CAShapeLayer * _maskLayer;
    CAShapeLayer * _outlineLayer;
}

@property (retain) CATextLayer *cardNumberLayer;
@property (retain) CATextLayer *cardholderNameLayer;
@property (retain) CATextLayer *expirationDateLayer;
@property (retain) CALayer *infoLayer;
@property (retain) CATextLayer *instructionLayer;
@property (retain) CAShapeLayer *maskLayer;
@property (retain) CAShapeLayer *outlineLayer;

+ (id)layer;

- (void).cxx_destruct;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })alignmentRect;
- (void)animateFoundCardRect:(id)arg1;
- (void)animateFoundCode:(id)arg1 codePosition:(struct CGPoint { double x1; double x2; })arg2 codeFrameIndex:(unsigned long long)arg3 cardHolder:(id)arg4 cardholderPosition:(struct CGPoint { double x1; double x2; })arg5 cardholderFrameIndex:(unsigned long long)arg6 expDate:(id)arg7 expdatePosition:(struct CGPoint { double x1; double x2; })arg8 expDateFrameIndex:(unsigned long long)arg9 completionBlock:(id /* block */)arg10;
- (id)cardNumberLayer;
- (id)cardholderNameLayer;
- (id)expirationDateLayer;
- (void)fadePlacementImage;
- (id)infoLayer;
- (id)init;
- (id)instructionLayer;
- (void)layoutSublayers;
- (void)makeTextLayer:(id)arg1 matchWidthOfText:(id)arg2;
- (id)maskLayer;
- (id)outlineLayer;
- (void)propogateMaskColor:(id)arg1 outlineColor:(id)arg2 placementTextColor:(id)arg3 capturedTextColor:(id)arg4;
- (void)resetLayer;
- (void)setCardNumberLayer:(id)arg1;
- (void)setCardholderNameLayer:(id)arg1;
- (void)setExpirationDateLayer:(id)arg1;
- (void)setInfoLayer:(id)arg1;
- (void)setInstructionLayer:(id)arg1;
- (void)setMaskLayer:(id)arg1;
- (void)setOutlineLayer:(id)arg1;

@end
