/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Memories.framework/Memories
 */

@interface MiroVPMutableMetadataRange : MiroVPMetadataRange

@property (nonatomic, retain) NSDictionary *analysisDict;
@property (nonatomic) int durationInFrames;
@property (nonatomic) unsigned long long flags;
@property (nonatomic) int startTimeInFrames;
@property (nonatomic) unsigned long long type;

- (void)setAnalysisDict:(id)arg1;
- (void)setDurationInFrames:(int)arg1;
- (void)setFlags:(unsigned long long)arg1;
- (void)setStartTimeInFrames:(int)arg1;
- (void)setType:(unsigned long long)arg1;

@end
