/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Memories.framework/Memories
 */

@interface MiroMemoryDebugCollectionViewController : UICollectionViewController <MiroMemoryDebugCollectionViewControllerProtocol> {
    MiroAutoEditController * _autoEditController;
    unsigned long long  _currentSortType;
    <MiroMemoryDebugCollectionViewControllerDelegate> * _delegate;
    bool  _isSaveMode;
    MiroMemory * _memory;
    UIBarButtonItem * _sortBarButton;
    NSArray * _sortTitles;
}

@property (nonatomic, retain) MiroAutoEditController *autoEditController;
@property (nonatomic) unsigned long long currentSortType;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <MiroMemoryDebugCollectionViewControllerDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic) bool isSaveMode;
@property (retain) MiroMemory *memory;
@property (nonatomic) UIBarButtonItem *sortBarButton;
@property (nonatomic, retain) NSArray *sortTitles;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)autoEditController;
- (void)bringUpActions:(id)arg1;
- (void)bringUpSortOptions:(id)arg1;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (struct CGSize { double x1; double x2; })collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (unsigned long long)currentSortType;
- (id)delegate;
- (void)didReceiveMemoryWarning;
- (void)done:(id)arg1;
- (bool)isSaveMode;
- (id)memory;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)resetMemoryToCleanState:(id)arg1;
- (void)saveDebugPanelForMemory:(id)arg1;
- (void)setAutoEditController:(id)arg1;
- (void)setCurrentSortType:(unsigned long long)arg1;
- (void)setDelegate:(id)arg1;
- (void)setIsSaveMode:(bool)arg1;
- (void)setMemory:(id)arg1;
- (void)setSortBarButton:(id)arg1;
- (void)setSortTitles:(id)arg1;
- (id)sortBarButton;
- (id)sortTitles;
- (void)viewDidLoad;
- (void)viewWillAppear:(bool)arg1;
- (void)viewWillTransitionToSize:(struct CGSize { double x1; double x2; })arg1 withTransitionCoordinator:(id)arg2;

@end
