/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Memories.framework/Memories
 */

@interface MiroMemoryEditorBottomToolbar : UIToolbar {
    MiroAutoEditor * _autoEditor;
    UIBarButtonItem * _doneButtonItem;
    <MiroCancelDoneDelegate> * _doneCancelDelegate;
    bool  _isSpinning;
    bool  _playPauseButtonEnabled;
    <MiroPlayerControlling> * _playerController;
    bool  _showDoneCancelButtons;
}

@property (nonatomic, retain) MiroAutoEditor *autoEditor;
@property (nonatomic, retain) UIBarButtonItem *doneButtonItem;
@property (nonatomic) <MiroCancelDoneDelegate> *doneCancelDelegate;
@property (nonatomic) bool isSpinning;
@property (nonatomic) bool playPauseButtonEnabled;
@property (nonatomic) <MiroPlayerControlling> *playerController;
@property (nonatomic) bool showDoneCancelButtons;

- (void).cxx_destruct;
- (id)_activityButtonRow;
- (id)_activityItem;
- (void)_applicationWillResignActive:(id)arg1;
- (id)_cancelButtonItem;
- (id)_flexibleSpaceItem;
- (void)_handlePlayerDidBeginPlayingNotification:(id)arg1;
- (void)_handlePlayerDidDidPlayToEndTimeNotification:(id)arg1;
- (void)_pause:(id)arg1;
- (id)_pauseButtonItem;
- (id)_pauseButtonRow;
- (void)_play:(id)arg1;
- (id)_playButtonItem;
- (id)_playButtonRow;
- (void)_updateItemsAnimated:(bool)arg1;
- (id)autoEditor;
- (void)dealloc;
- (id)doneButtonItem;
- (id)doneCancelDelegate;
- (id)initWithCoder:(id)arg1;
- (bool)isSpinning;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;
- (bool)playPauseButtonEnabled;
- (id)playerController;
- (void)setAutoEditor:(id)arg1;
- (void)setDoneButtonItem:(id)arg1;
- (void)setDoneCancelDelegate:(id)arg1;
- (void)setIsSpinning:(bool)arg1;
- (void)setPlayPauseButtonEnabled:(bool)arg1;
- (void)setPlayerController:(id)arg1;
- (void)setShowDoneCancelButtons:(bool)arg1;
- (bool)showDoneCancelButtons;
- (void)stopSpinning;
- (void)updateItems;

@end
