/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriTasks.framework/SiriTasks
 */

@interface STStartWorkoutRequest : AFSiriRequest {
    long long  _activityType;
    HKQuantity * _goal;
    long long  _goalType;
    bool  _isOpenGoal;
    long long  _locationType;
    bool  _skipActivitySetup;
}

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)_initWithType:(long long)arg1 location:(long long)arg2 goal:(id)arg3 goalType:(long long)arg4 isOpenGoal:(bool)arg5 skipActivitySetup:(bool)arg6;
- (long long)activityType;
- (id)createResponse;
- (void)encodeWithCoder:(id)arg1;
- (long long)goalType;
- (id)initWithCoder:(id)arg1;
- (bool)isOpenGoal;
- (long long)locationType;
- (bool)skipActivitySetup;
- (id)workoutGoal;

@end
