/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotosPlayer.framework/PhotosPlayer
 */

@interface ISLivePhotoPlaybackFilter : NSObject {
    bool  _canPlay;
    double  _hintProgress;
    bool  _isPerformingInputChanges;
    id /* block */  _outputChangeHandler;
    long long  _state;
}

@property (nonatomic) bool canPlay;
@property (nonatomic, readonly) double hintProgress;
@property (setter=_setPerformingInputChanges:, nonatomic) bool isPerformingInputChanges;
@property (nonatomic, copy) id /* block */ outputChangeHandler;
@property (nonatomic, readonly) long long state;

- (void).cxx_destruct;
- (void)_setPerformingInputChanges:(bool)arg1;
- (bool)canPlay;
- (double)hintProgress;
- (id)init;
- (void)inputDidChange;
- (bool)isPerformingInputChanges;
- (id /* block */)outputChangeHandler;
- (void)performInputChanges:(id /* block */)arg1;
- (void)setCanPlay:(bool)arg1;
- (void)setHintProgress:(double)arg1;
- (void)setOutputChangeHandler:(id /* block */)arg1;
- (void)setState:(long long)arg1;
- (long long)state;

@end
