/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotosPlayer.framework/PhotosPlayer
 */

@interface ISLivePhotoHintBehavior : ISBehavior {
    bool  __didFinishPreparing;
    bool  __preparing;
    float  _prerollRate;
    struct { 
        long long value; 
        int timescale; 
        unsigned int flags; 
        long long epoch; 
    }  _seekTime;
}

@property (setter=_setDidFinishPreparing:, nonatomic) bool _didFinishPreparing;
@property (getter=_isPreparing, setter=_setPreparing:, nonatomic) bool _preparing;
@property (nonatomic, readonly) float prerollRate;
@property (nonatomic, readonly) struct { long long x1; int x2; unsigned int x3; long long x4; } seekTime;

- (bool)_didFinishPreparing;
- (void)_handleDidFinishPreparing;
- (void)_handleDidPreroll;
- (void)_handleDidSeekToBeginning;
- (bool)_isPreparing;
- (void)_prepareIfNeeded;
- (void)_preroll;
- (void)_seekToBeginning;
- (void)_setDidFinishPreparing:(bool)arg1;
- (void)_setPreparing:(bool)arg1;
- (void)activeDidChange;
- (void)hintWithProgress:(float)arg1;
- (id)initWithInitialLayoutInfo:(id)arg1 seekTime:(struct { long long x1; int x2; unsigned int x3; long long x4; })arg2 prerollRate:(float)arg3;
- (float)prerollRate;
- (struct { long long x1; int x2; unsigned int x3; long long x4; })seekTime;

@end
