/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotosPlayer.framework/PhotosPlayer
 */

@interface ISLivePhotoUIView : ISBasePlayerUIView <UIGestureRecognizerDelegate, UIInteractionProgressObserver> {
    AVAudioSession * __audioSession;
    UIPreviewForceInteractionProgress * __interactionProgress;
    ISLivePhotoPlaybackFilter * __playbackFilter;
    bool  __playingVitality;
    NSObject<OS_dispatch_queue> * _audioSessionQueue;
    UIGestureRecognizer * _playbackGestureRecognizer;
}

@property (setter=_setAudioSession:, nonatomic, retain) AVAudioSession *_audioSession;
@property (nonatomic, readonly) UIPreviewForceInteractionProgress *_interactionProgress;
@property (nonatomic, readonly) ISLivePhotoPlaybackFilter *_playbackFilter;
@property (setter=_setPlayingVitality:, nonatomic) bool _playingVitality;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) UIGestureRecognizer *playbackGestureRecognizer;
@property (nonatomic, retain) ISLivePhotoPlayer *player;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)_audioSession;
- (void)_handlePlaybackRecognizer:(id)arg1;
- (id)_interactionProgress;
- (id)_playbackFilter;
- (Class)_playbackFilterClass;
- (bool)_playingVitality;
- (void)_setAudioSession:(id)arg1;
- (void)_setPlayingVitality:(bool)arg1;
- (void)_updateForceInteractionProgress;
- (void)_updatePlaybackFilterInput;
- (void)dealloc;
- (bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (id)init;
- (void)interactionProgress:(id)arg1 didEnd:(bool)arg2;
- (void)interactionProgressDidUpdate:(id)arg1;
- (id)livePhotoPlayer;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;
- (id)playbackGestureRecognizer;
- (void)playerDidChange;
- (void)setPlayer:(id)arg1;

@end
