/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotosPlayer.framework/PhotosPlayer
 */

@interface ISLivePhotoPlayer : ISBasePlayer {
    long long  __playbackIdentifier;
    bool  __shouldPlayHintWhenReady;
    bool  __shouldPlayVitalityWhenReady;
    bool  __shouldPrepareForHintWhenReady;
    bool  __shouldPrepareForVitalityWhenReady;
    long long  _currentPlaybackStyle;
    ISLivePhotoPlaybackFilter * _playbackFilter;
    bool  _playingVitality;
    ISLivePhotoVitalityFilter * _vitalityFilter;
}

@property (setter=_setPlaybackIdentifier:, nonatomic) long long _playbackIdentifier;
@property (setter=_setShouldPlayHintWhenReady:, nonatomic) bool _shouldPlayHintWhenReady;
@property (setter=_setShouldPlayVitalityWhenReady:, nonatomic) bool _shouldPlayVitalityWhenReady;
@property (setter=_setShouldPrepareForHintWhenReady:, nonatomic) bool _shouldPrepareForHintWhenReady;
@property (setter=_setShouldPrepareForVitalityWhenReady:, nonatomic) bool _shouldPrepareForVitalityWhenReady;
@property (setter=_setCurrentPlaybackStyle:, nonatomic) long long currentPlaybackStyle;
@property (nonatomic, retain) ISLivePhotoPlaybackFilter *playbackFilter;
@property (getter=isPlayingVitality, setter=_setPlayingVitality:, nonatomic) bool playingVitality;
@property (nonatomic, retain) ISLivePhotoVitalityFilter *vitalityFilter;

- (void).cxx_destruct;
- (void)_handlePlaybackFilterDidChange:(id)arg1;
- (void)_handleVitalityFilterDidChange:(id)arg1;
- (long long)_incrementedPlaybackIdentifier;
- (double)_photoTransitionDuration;
- (void)_playHintIfNeeded;
- (long long)_playbackIdentifier;
- (void)_prepareForVitalityIfNeeded;
- (void)_setCurrentPlaybackStyle:(long long)arg1;
- (void)_setPlaybackIdentifier:(long long)arg1;
- (void)_setPlayingVitality:(bool)arg1;
- (void)_setShouldPlayHintWhenReady:(bool)arg1;
- (void)_setShouldPlayVitalityWhenReady:(bool)arg1;
- (void)_setShouldPrepareForHintWhenReady:(bool)arg1;
- (void)_setShouldPrepareForVitalityWhenReady:(bool)arg1;
- (bool)_shouldPlayHintWhenReady;
- (bool)_shouldPlayVitalityWhenReady;
- (bool)_shouldPrepareForHintWhenReady;
- (bool)_shouldPrepareForVitalityWhenReady;
- (void)_updatePlayingVitality;
- (long long)currentPlaybackStyle;
- (bool)isPlayingVitality;
- (void)playHintWhenReady;
- (void)playVitality;
- (id)playbackFilter;
- (void)playerItemDidChange;
- (void)prepareForHintWhenReady;
- (void)prepareForVitality;
- (void)setPlaybackFilter:(id)arg1;
- (void)setVitalityFilter:(id)arg1;
- (void)showPlaybackHintWithProgress:(float)arg1;
- (void)startPlaybackWithStyle:(long long)arg1;
- (void)statusDidChange;
- (void)stopPlayback;
- (void)videoPlayRateDidChange;
- (double)videoWillPlayToEndInterval;
- (id)vitalityFilter;

@end
