/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotosPlayer.framework/PhotosPlayer
 */

@interface ISTransitionApplier : NSObject

+ (id)defaultApplier;

- (void)_setValue:(id)arg1 forKeyPath:(id)arg2 ofLayer:(id)arg3 withTransitionOptions:(id)arg4;
- (void)applyAlpha:(double)arg1 scale:(double)arg2 scaleAnchorOffset:(struct CGPoint { double x1; double x2; })arg3 blurRadius:(double)arg4 toLayer:(id)arg5 withTransitionOptions:(id)arg6;

@end
