/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Home.framework/Home
 */

@interface HFServiceGroupBuilder : HFItemBuilder {
    NSString * _name;
    HFMutableSetDiff * _serviceUUIDs;
}

@property (nonatomic, copy) NSString *name;
@property (nonatomic, readonly) NSString *primaryServiceType;
@property (nonatomic, readonly) HMServiceGroup *serviceGroup;
@property (nonatomic, readonly) HFMutableSetDiff *serviceUUIDs;
@property (nonatomic, readonly) NSArray *services;

+ (Class)homeKitRepresentationClass;

- (void).cxx_destruct;
- (id)_createServiceGroup;
- (id)_performValidation;
- (id)_updateName;
- (id)_updateServices;
- (void)addService:(id)arg1;
- (id)commitItem;
- (id)initWithExistingObject:(id)arg1 inHome:(id)arg2;
- (id)name;
- (id)primaryServiceType;
- (void)removeService:(id)arg1;
- (id)serviceGroup;
- (id)serviceUUIDs;
- (id)services;
- (void)setName:(id)arg1;
- (void)setServiceGroup:(id)arg1;
- (bool)shouldAllowAddingService:(id)arg1;

@end
