/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/BulletinBoard.framework/BulletinBoard
 */

@interface BBObserver : NSObject <BBAssertionDelegate> {
    NSMutableDictionary * _attachmentInfoByAttachmentUUIDByBulletinID;
    NSMapTable * _bulletinLifeAssertions;
    NSObject<OS_dispatch_queue> * _calloutQueue;
    <BBObserverDelegate> * _delegate;
    struct { 
        unsigned int addBulletinPlayLightsAndSirens : 1; 
        unsigned int addBulletin : 1; 
        unsigned int modifyBulletin : 1; 
        unsigned int modifyBulletinDEPRECATED : 1; 
        unsigned int removeBulletin : 1; 
        unsigned int removeBulletinFinal : 1; 
        unsigned int sectionOrderRule : 1; 
        unsigned int sectionOrder : 1; 
        unsigned int sectionInfo : 1; 
        unsigned int sectionParameters : 1; 
        unsigned int removeSection : 1; 
        unsigned int fetchImage : 1; 
        unsigned int fetchSize : 1; 
        unsigned int sizeConstraints : 1; 
        unsigned int multiSizeConstraints : 1; 
        unsigned int imageForThumbData : 1; 
        unsigned int sizeForThumbSize : 1; 
        unsigned int purgeReferences : 1; 
        unsigned int alertBehaviorOverrides : 1; 
        unsigned int alertBehaviorOverrideState : 1; 
        unsigned int invalidatedBulletinIDs : 1; 
        unsigned int serverConnectionChanged : 1; 
        unsigned int serverReceivedResponse : 1; 
    }  _delegateFlags;
    NSString * _gatewayName;
    unsigned long long  _gatewayPriority;
    bool  _isGateway;
    unsigned long long  _observerFeed;
    NSObject<OS_dispatch_queue> * _queue;
    NSMutableDictionary * _remainingFeedsByBulletinID;
    NSMutableDictionary * _sectionParameters;
    BBObserverServerProxy * _serverProxy;
}

@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <BBObserverDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly, copy) NSString *gatewayName;
@property (nonatomic, readonly) unsigned long long gatewayPriority;
@property (readonly) unsigned long long hash;
@property (nonatomic) unsigned long long observerFeed;
@property (readonly) Class superclass;

// Image: /System/Library/PrivateFrameworks/BulletinBoard.framework/BulletinBoard

+ (void)initialize;
+ (id)observerGlobalQueue;

- (void).cxx_destruct;
- (id)_attachmentInfoForBulletin:(id)arg1;
- (void)_fetchAndProcessImageForBulletin:(id)arg1 withKey:(id)arg2 constraints:(id)arg3 attachmentType:(long long)arg4 completion:(id /* block */)arg5;
- (id)_initWithCalloutQueue:(id)arg1 gatewayName:(id)arg2 gatewayPriority:(unsigned long long)arg3 isGateway:(bool)arg4;
- (void)_preFetchAttachmentInfoIfNecessaryForBulletin:(id)arg1 withCompletion:(id /* block */)arg2;
- (bool)_queue_attachmentImagesFetchedForBulletin:(id)arg1;
- (id)_queue_attachmentInfoForBulletin:(id)arg1 create:(bool)arg2;
- (bool)_queue_attachmentSizesFetchedForBulletin:(id)arg1;
- (void)_queue_getAttachmentImagesIfPossibleForBulletin:(id)arg1 withCompletion:(id /* block */)arg2;
- (void)_queue_getAttachmentSizesIfPossibleForBulletin:(id)arg1 withCompletion:(id /* block */)arg2;
- (void)_queue_invalidate;
- (void)_queue_noteAttachmentImagesFetchedForBulletin:(id)arg1;
- (void)_queue_noteAttachmentSizesFetchedForBulletin:(id)arg1;
- (void)_queue_registerBulletin:(id)arg1 withTransactionID:(unsigned long long)arg2;
- (void)_queue_serverProxy:(id)arg1 connectionStateDidChange:(bool)arg2;
- (void)_queue_setAttachmentImage:(id)arg1 forKey:(id)arg2 forBulletin:(id)arg3;
- (void)_queue_setAttachmentSize:(struct CGSize { double x1; double x2; })arg1 forKey:(id)arg2 forBulletin:(id)arg3;
- (void)_queue_updateAddBulletin:(id)arg1 forFeeds:(unsigned long long)arg2 withReply:(id /* block */)arg3;
- (void)_queue_updateBulletin:(id)arg1 forFeeds:(unsigned long long)arg2 withReply:(id /* block */)arg3;
- (void)_queue_updateModifyBulletin:(id)arg1 forFeeds:(unsigned long long)arg2 withReply:(id /* block */)arg3;
- (void)_queue_updateRemoveBulletin:(id)arg1 forFeeds:(unsigned long long)arg2 withReply:(id /* block */)arg3;
- (void)_reasonableConstraintsForAttachmentType:(long long)arg1 withCompletionHandler:(id /* block */)arg2;
- (void)assertionExpired:(id)arg1 transactionID:(unsigned long long)arg2;
- (id)attachmentImageForKey:(id)arg1 forBulletin:(id)arg2;
- (struct CGSize { double x1; double x2; })attachmentSizeForKey:(id)arg1 forBulletin:(id)arg2;
- (void)clearBulletins:(id)arg1 inSection:(id)arg2;
- (void)clearBulletinsFromDate:(id)arg1 toDate:(id)arg2 inSections:(id)arg3;
- (void)clearSection:(id)arg1;
- (void)dealloc;
- (id)delegate;
- (id)description;
- (id)gatewayName;
- (unsigned long long)gatewayPriority;
- (void)getAlertBehaviorOverridesWithCompletion:(id /* block */)arg1;
- (void)getAttachmentImageForBulletin:(id)arg1 withCompletion:(id /* block */)arg2;
- (void)getBulletinsForPublisherMatchIDs:(id)arg1 sectionID:(id)arg2 withCompletion:(id /* block */)arg3;
- (void)getBulletinsPublishedAfterDate:(id)arg1 withCompletion:(id /* block */)arg2;
- (void)getBulletinsWithCompletion:(id /* block */)arg1;
- (void)getParametersForSectionID:(id)arg1 withCompletion:(id /* block */)arg2;
- (void)getPrimaryAttachmentDataForBulletin:(id)arg1 withCompletion:(id /* block */)arg2;
- (void)getPrivilegedSenderTypesWithCompletion:(id /* block */)arg1;
- (void)getSectionInfoForActiveSectionsWithCompletion:(id /* block */)arg1;
- (void)getSectionInfoForSectionIDs:(id)arg1 withCompletion:(id /* block */)arg2;
- (void)getSectionInfoWithCompletion:(id /* block */)arg1;
- (void)getSectionOrderRuleWithCompletion:(id /* block */)arg1;
- (void)getSortDescriptorsForSectionID:(id)arg1 withCompletion:(id /* block */)arg2;
- (void)getUniversalSectionIDForSectionID:(id)arg1 withCompletion:(id /* block */)arg2;
- (id)init;
- (id)initWithQueue:(id)arg1;
- (id)initWithQueue:(id)arg1 asGateway:(id)arg2 priority:(unsigned long long)arg3;
- (id)initWithQueue:(id)arg1 forGateway:(id)arg2;
- (void)invalidate;
- (bool)isValid;
- (void)noteAlertBehaviorOverrideStateChanged:(id)arg1;
- (void)noteAlertBehaviorOverridesChanged:(id)arg1;
- (void)noteServerReceivedResponseForBulletin:(id)arg1;
- (unsigned long long)observerFeed;
- (id)parametersForSectionID:(id)arg1;
- (void)removeBulletins:(id)arg1 inSection:(id)arg2;
- (void)removeBulletins:(id)arg1 inSection:(id)arg2 fromFeed:(unsigned long long)arg3;
- (void)removeSection:(id)arg1;
- (void)requestListBulletinsForSectionID:(id)arg1;
- (void)requestNoticesBulletinsForSectionID:(id)arg1;
- (void)sendResponse:(id)arg1;
- (void)serverProxy:(id)arg1 connectionStateDidChange:(bool)arg2;
- (void)setDelegate:(id)arg1;
- (void)setObserverFeed:(unsigned long long)arg1;
- (void)updateBulletin:(id)arg1 forFeeds:(unsigned long long)arg2 withReply:(id /* block */)arg3;
- (void)updateSectionInfo:(id)arg1;
- (void)updateSectionOrder:(id)arg1;
- (void)updateSectionOrderRule:(id)arg1;
- (void)updateSectionParameters:(id)arg1 forSectionID:(id)arg2;

// Image: /System/Library/PrivateFrameworks/BulletinDistributorCompanion.framework/BulletinDistributorCompanion

- (void)getPrimaryAttachmentInfoForBulletin:(id)arg1 withCompletion:(id /* block */)arg2;

@end
