/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/HomeKit.framework/HomeKit
 */

@interface _HMCameraSource : NSObject <HMFMessageReceiver> {
    HMCameraView * _cameraView;
    NSObject<OS_dispatch_queue> * _clientQueue;
    HMDelegateCaller * _delegateCaller;
    NSNumber * _imageRotation;
    HMFMessageDispatcher * _msgDispatcher;
    NSUUID * _profileUniqueIdentifier;
    NSObject<OS_dispatch_queue> * _propertyQueue;
    NSString * _sessionID;
    NSNumber * _slotIdentifier;
}

@property (nonatomic) HMCameraView *cameraView;
@property (nonatomic, retain) NSObject<OS_dispatch_queue> *clientQueue;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic, retain) HMDelegateCaller *delegateCaller;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) NSNumber *imageRotation;
@property (nonatomic, readonly) NSObject<OS_dispatch_queue> *messageReceiveQueue;
@property (nonatomic, readonly) NSUUID *messageTargetUUID;
@property (nonatomic, retain) HMFMessageDispatcher *msgDispatcher;
@property (nonatomic, readonly, copy) NSUUID *profileUniqueIdentifier;
@property (nonatomic, retain) NSObject<OS_dispatch_queue> *propertyQueue;
@property (nonatomic, readonly, copy) NSString *sessionID;
@property (nonatomic, readonly, copy) NSNumber *slotIdentifier;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)cameraView;
- (id)clientQueue;
- (id)delegateCaller;
- (id)imageRotation;
- (id)initWithSessionID:(id)arg1 slotIdentifier:(id)arg2 imageRotation:(id)arg3 clientQueue:(id)arg4 delegateCaller:(id)arg5 msgDispatcher:(id)arg6 profileUniqueIdentifier:(id)arg7;
- (id)messageReceiveQueue;
- (id)messageTargetUUID;
- (id)msgDispatcher;
- (id)profileUniqueIdentifier;
- (id)propertyQueue;
- (id)sessionID;
- (void)setCameraView:(id)arg1;
- (void)setClientQueue:(id)arg1;
- (void)setDelegateCaller:(id)arg1;
- (void)setImageRotation:(id)arg1;
- (void)setMsgDispatcher:(id)arg1;
- (void)setPropertyQueue:(id)arg1;
- (id)slotIdentifier;

@end
