/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AuthKit.framework/AuthKit
 */

@interface AKCircleRequestContext : NSObject <NSSecureCoding> {
    NSString * _heartbeatTokenValue;
    NSString * _identityTokenValue;
    AKCircleRequestPayload * _payload;
    NSString * _pushToken;
    bool  _waitForReply;
    double  _waitForReplyTimeout;
}

@property (nonatomic, retain) NSString *heartbeatTokenValue;
@property (nonatomic, retain) NSString *identityTokenValue;
@property (nonatomic, retain) AKCircleRequestPayload *payload;
@property (nonatomic, retain) NSString *pushToken;
@property (nonatomic) bool waitForReply;
@property (nonatomic) double waitForReplyTimeout;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)heartbeatTokenValue;
- (id)identityTokenValue;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)payload;
- (id)pushToken;
- (void)setHeartbeatTokenValue:(id)arg1;
- (void)setIdentityTokenValue:(id)arg1;
- (void)setPayload:(id)arg1;
- (void)setPushToken:(id)arg1;
- (void)setWaitForReply:(bool)arg1;
- (void)setWaitForReplyTimeout:(double)arg1;
- (bool)waitForReply;
- (double)waitForReplyTimeout;

@end
