/* Generated by RuntimeBrowser.
 */

@protocol CDPWaitingApprovalDelegate

@required

- (void)waitingApprovalViewController:(CDPWaitingApprovalViewController *)arg1 escapeHatchTappedWithOffer:(unsigned long long)arg2;

@end
