/* Generated by RuntimeBrowser.
 */

@protocol CKFullScreenAppViewControllerDelegate <NSObject>

@required

- (void)fullscreenAppViewController:(CKFullScreenAppViewController *)arg1 wantsToSwitchToPlugin:(IMBalloonPlugin *)arg2;
- (void)fullscreenAppViewControllerWantsToCollapse:(CKFullScreenAppViewController *)arg1;

@end
