/* Generated by RuntimeBrowser.
 */

@protocol CNUIPRLikenessProviderCache <NSObject>

@required

- (<CNUIPRLikenessProvider> *)loadingPlaceholderProvider;
- (<CNUIPRLikenessProvider> *)placeholderProvider;

@end
