/* Generated by RuntimeBrowser.
 */

@protocol DKHostRemoteContext <NSObject>

@required

- (void)enableVolumeHUD:(bool)arg1;
- (void)getAsset:(void *)arg1 completion:(void *)arg2; // needs 2 arg types, found 7: NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSData *, void*
- (void)setScreenToBrightness:(float)arg1 animate:(bool)arg2;

@end
