/* Generated by RuntimeBrowser.
 */

@protocol FCContentContextInternal <NSObject, FCCacheFlushing>

@required

- (FCArticleListRecordSource *)articleListRecordSource;
- (FCArticleRecordSource *)articleRecordSource;
- (FCChannelMembershipController *)channelMembershipController;
- (FCCKDatabase *)contentDatabase;
- (FCFeedDatabase *)feedDatabase;
- (FCPurchaseLookupRecordSource *)purchaseLookupRecordSource;
- (FCResourceRecordSource *)resourceRecordSource;
- (FCTagRecordSource *)tagRecordSource;
- (FCWebArchiveSource *)webArchiveSource;

@end
