/* Generated by RuntimeBrowser.
 */

@protocol GEONavigationObserver <NSObject>

@optional

- (void)navigation:(GEONavigation *)arg1 didChangeGuidanceState:(GEONavigationGuidanceState *)arg2;
- (void)navigation:(GEONavigation *)arg1 didChangeShouldSuppressCellularDataAlerts:(bool)arg2;
- (void)navigation:(GEONavigation *)arg1 didUpdateDisplayETA:(NSDate *)arg2 displayRemainingTime:(double)arg3;
- (void)navigationDidChangeNavigationState:(GEONavigation *)arg1;

@end
