/* Generated by RuntimeBrowser.
 */

@protocol HDFitnessFriendsActivityDataManagerDelegate <NSObject>

@optional

- (void)fitnessFriendsActivityDataManager:(HDFitnessFriendsActivityDataManager *)arg1 recievedNewSnapshots:(NSArray *)arg2 workouts:(NSArray *)arg3 achievements:(NSArray *)arg4;

@end
