/* Generated by RuntimeBrowser.
 */

@protocol HDFitnessFriendsNotificationEngineDelegate <NSObject>

@optional

- (void)notificationEngine:(HDFitnessFriendsNotificationEngine *)arg1 didDetectEvents:(NSArray *)arg2;

@end
