/* Generated by RuntimeBrowser.
 */

@protocol HMDCameraStreamSnapshotHandlerDelegate <NSObject>

@required

- (void)streamSnapshotHandler:(HMDCameraStreamSnapshotHandler *)arg1 didGetNewSnapshot:(NSData *)arg2;

@end
