/* Generated by RuntimeBrowser.
 */

@protocol INSetMessageAttributeIntent <NSObject, JSExport>

@required

- (NSString *)attribute;
- (NSArray *)identifiers;
- (void)setAttribute:(NSString *)arg1;
- (void)setIdentifiers:(NSArray *)arg1;

@end
