/* Generated by RuntimeBrowser.
 */

@protocol INStartWorkoutIntent <NSObject, JSExport>

@required

- (NSNumber *)goalValue;
- (NSNumber *)isOpenEnded;
- (void)setGoalValue:(NSNumber *)arg1;
- (void)setIsOpenEnded:(NSNumber *)arg1;
- (void)setWorkoutGoalUnitType:(long long)arg1;
- (void)setWorkoutLocationType:(long long)arg1;
- (void)setWorkoutName:(NSString *)arg1;
- (long long)workoutGoalUnitType;
- (long long)workoutLocationType;
- (NSString *)workoutName;

@end
