/* Generated by RuntimeBrowser.
 */

@protocol ISPlayerItemObserver <NSObject>

@optional

- (void)playerItemContentDidChange:(ISPlayerItem *)arg1;
- (void)playerItemStatusDidChange:(ISPlayerItem *)arg1;

@end
