/* Generated by RuntimeBrowser.
 */

@protocol MiroActivityItemProviderDelegate <NSObject>

@required

- (void)cancel;
- (void)dismissProgressController;
- (void)presentProgressController:(UIViewController *)arg1;

@end
