/* Generated by RuntimeBrowser.
 */

@protocol MNNavigationServiceRemoteProxyDelegate <MNNavigationServiceClientInterface>

@required

- (void)remoteProxy:(MNNavigationServiceRemoteProxy *)arg1 didFinishReconnectingWithDetails:(MNActiveRouteDetails *)arg2;

@end
