/* Generated by RuntimeBrowser.
 */

@protocol MusicLocalPlaybackHistoryItemDataSource <NSObject>

@required

- (NSArray *)offersForMediaItem:(MPMediaItem *)arg1;
- (bool)wantsBuyButtonForItem:(MPMediaItem *)arg1;
- (bool)wantsContextualActionsButtonForItem:(MPMediaItem *)arg1;

@end
