/* Generated by RuntimeBrowser.
 */

@protocol MusicUpNextTableViewDelegate <MusicTableViewDelegate>

@required

- (void)tableView:(MusicUpNextTableView *)arg1 pinView:(UIView *)arg2 didUpdatePinLocation:(long long)arg3;

@end
