/* Generated by RuntimeBrowser.
 */

@protocol NCNotificationStaticContentProviding <NSObject>

@required

- (NSDate *)date;
- (id /* block */)defaultAction:(void *)arg1; // needs 1 arg types, found 4: id /* block */, void*, id, SEL
- (<NCNotificationStaticContentProvidingDelegate> *)delegate;
- (id /* block */)dismissAction:(void *)arg1; // needs 1 arg types, found 4: id /* block */, void*, id, SEL
- (NSString *)hintText;
- (UIImage *)icon;
- (NSArray *)interfaceActions;
- (NSString *)primarySubtitleText;
- (NSString *)primaryText;
- (NSString *)secondaryText;
- (void)setDelegate:(id <NCNotificationStaticContentProvidingDelegate>)arg1;
- (UIImage *)thumbnail;
- (NSString *)title;

@end
