/* Generated by RuntimeBrowser.
 */

@protocol NCNotificationListCellDelegate <NSObject>

@required

- (void)notificationListCell:(NCNotificationListCell *)arg1 requestsClearingNotificationRequest:(NCNotificationRequest *)arg2;
- (void)notificationListCell:(NCNotificationListCell *)arg1 requestsPerformAction:(NCNotificationAction *)arg2 forNotificationRequest:(NCNotificationRequest *)arg3;
- (void)notificationListCellDidHideCellActions:(NCNotificationListCell *)arg1;
- (void)notificationListCellDidRevealCellActions:(NCNotificationListCell *)arg1;
- (void)notificationListCellDidSignificantUserInteraction:(NCNotificationListCell *)arg1;
- (bool)notificationListCellShouldShowActionsForNotificationRequest:(NCNotificationRequest *)arg1;
- (void)willTearDownNotificationListCell:(NCNotificationListCell *)arg1;

@end
