/* Generated by RuntimeBrowser.
 */

@protocol PUMutableTimelineScrubberModel <NSObject>

@required

- (struct PUTimelineScrubberInsets { double x1; double x2; })contentInsets;
- (double)contentOffset;
- (double)contentRange;
- (double)scrubberOffset;
- (double)scrubbingRate;
- (void)setContentInsets:(struct PUTimelineScrubberInsets { double x1; double x2; })arg1;
- (void)setContentOffset:(double)arg1;
- (void)setContentRange:(double)arg1;
- (void)setScrubberOffset:(double)arg1;
- (void)setScrubbingRate:(double)arg1;

@end
