/* Generated by RuntimeBrowser.
 */

@protocol PUMutableTimelineModel <NSObject>

@required

- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })contentInsets;
- (struct CGPoint { double x1; double x2; })contentOffset;
- (struct CGSize { double x1; double x2; })contentRange;
- (void)setContentInsets:(struct UIEdgeInsets { double x1; double x2; double x3; double x4; })arg1;
- (void)setContentOffset:(struct CGPoint { double x1; double x2; })arg1;
- (void)setContentRange:(struct CGSize { double x1; double x2; })arg1;

@end
