/* Generated by RuntimeBrowser.
 */

@protocol PXSectionedLayoutEngineDelegate <PXLayoutEngineDelegate>

@optional

- (PXLayoutGenerator *)layoutEngine:(PXSectionedLayoutEngine *)arg1 layoutGeneratorForSection:(unsigned long long)arg2;

@end
