/* Generated by RuntimeBrowser.
 */

@protocol SearchUIRowCardSection <SearchUICardSection>

@required

- (UIImage *)image;

@optional

- (double)imageCornerRadius;
- (bool)imageIsRightAligned;
- (NSString *)leftText;
- (NSString *)rightText;

@end
