/* Generated by RuntimeBrowser.
 */

@protocol SearchUINowPlayingCardSectionMovie <NSObject>

@required

- (NSArray *)icons;
- (UIImage *)image;
- (NSURL *)punchoutURI;
- (UIImage *)ratingGlyph;
- (NSString *)ratingText;
- (void)setIcons:(NSArray *)arg1;
- (void)setImage:(UIImage *)arg1;
- (void)setPunchoutURI:(NSURL *)arg1;
- (void)setRatingGlyph:(UIImage *)arg1;
- (void)setRatingText:(NSString *)arg1;
- (void)setSubtitleMaxLines:(unsigned long long)arg1;
- (void)setUrl:(NSURL *)arg1;
- (NSString *)subtitle;
- (unsigned long long)subtitleMaxLines;
- (NSString *)title;
- (NSURL *)url;

@end
