/* Generated by RuntimeBrowser.
 */

@protocol SearchUIMovieCardSectionDetail <NSObject>

@required

- (unsigned long long)descriptionMaxLines;
- (NSString *)descriptionText;
- (NSString *)title;

@end
