/* Generated by RuntimeBrowser.
 */

@protocol VSAApplicationControllerDelegate <NSObject>

@required

- (void)applicationController:(VSAApplicationController *)arg1 didReceiveViewModel:(VSAViewModel *)arg2;
- (void)applicationController:(VSAApplicationController *)arg1 didReceiveViewModelError:(NSError *)arg2;
- (void)applicationController:(VSAApplicationController *)arg1 request:(VSAApplicationControllerRequest *)arg2 didCompleteWithResponse:(VSAApplicationControllerResponse *)arg3;
- (void)applicationController:(VSAApplicationController *)arg1 request:(VSAApplicationControllerRequest *)arg2 didFailWithError:(NSError *)arg3;
- (void)applicationController:(VSAApplicationController *)arg1 startDidFailWithError:(NSError *)arg2;
- (void)applicationControllerDidStart:(VSAApplicationController *)arg1;

@optional

- (void)applicationController:(VSAApplicationController *)arg1 didStopWithError:(NSError *)arg2;

@end
