/* Generated by RuntimeBrowser.
 */

@protocol VSAAuthenticationViewController <NSObject>

@required

- (bool)isCancellationAllowed;
- (struct CGSize { double x1; double x2; })preferredLogoSize;
- (void)setCancellationAllowed:(bool)arg1;

@end
