/* Generated by RuntimeBrowser.
 */

@protocol VSAIdentityProviderPickerViewController <NSObject>

@required

- (unsigned long long)additionalProvidersMode;
- (<VSAIdentityProviderPickerViewControllerDelegate> *)delegate;
- (NSArray *)featuredIdentityProviders;
- (bool)isCancellationAllowed;
- (NSString *)requestingAppDisplayName;
- (NSString *)resourceTitle;
- (void)setAdditionalProvidersMode:(unsigned long long)arg1;
- (void)setCancellationAllowed:(bool)arg1;
- (void)setDelegate:(id <VSAIdentityProviderPickerViewControllerDelegate>)arg1;
- (void)setFeaturedIdentityProviders:(NSArray *)arg1;
- (void)setRequestingAppDisplayName:(NSString *)arg1;
- (void)setResourceTitle:(NSString *)arg1;

@end
