/* Generated by RuntimeBrowser.
 */

@protocol VSALoadingViewController <NSObject>

@required

- (<VSALoadingViewControllerDelegate> *)delegate;
- (bool)isCancellationAllowed;
- (void)setCancellationAllowed:(bool)arg1;
- (void)setDelegate:(id <VSALoadingViewControllerDelegate>)arg1;

@end
