/* Generated by RuntimeBrowser.
 */

@protocol VSAViewServiceRequestOperationDelegate <NSObject>

@optional

- (void)viewServiceRequestOperation:(VSAViewServiceRequestOperation *)arg1 dismissViewController:(UIViewController *)arg2;
- (void)viewServiceRequestOperation:(VSAViewServiceRequestOperation *)arg1 presentViewController:(UIViewController *)arg2;

@end
