/* Generated by RuntimeBrowser.
 */

@protocol VTGestureMonitorDelegate <NSObject>

@required

- (void)gestureMonitorDidReceivedSleepGesture:(VTGestureMonitor *)arg1;
- (void)gestureMonitorDidReceivedWakeGesture:(VTGestureMonitor *)arg1;

@end
