/* Generated by RuntimeBrowser.
 */

@protocol WBSCompletionListItem <NSObject>

@required

- (NSString *)parsecDomainIdentifier;

@optional

- (unsigned long long)engagementDestination;
- (NSString *)lastSearchQuery;
- (SFSearchResult *)sfSearchResultValue;

@end
