/* Generated by RuntimeBrowser.
 */

@protocol WGWidgetHostingViewControllerHost <NSObject>

@optional

- (bool)shouldPurgeArchivedSnapshotsForWidget:(WGWidgetHostingViewController *)arg1;
- (long long)userSpecifiedDisplayModeForWidget:(WGWidgetHostingViewController *)arg1;
- (void)widget:(WGWidgetHostingViewController *)arg1 didChangeUserSpecifiedDisplayMode:(long long)arg2;
- (void)widget:(WGWidgetHostingViewController *)arg1 didEncounterProblematicSnapshotAtURL:(NSURL *)arg2;

@end
