/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/LinkPresentation.framework/LinkPresentation
 */

@interface LPCSSVariable : NSObject {
    NSString * _name;
}

@property (nonatomic, readonly, copy) NSString *name;

- (void).cxx_destruct;
- (id)initWithName:(id)arg1;
- (id)initWithName:(id)arg1 resolvingWithThemePath:(id)arg2;
- (id)name;

@end
