/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/TelephonyUtilities.framework/TelephonyUtilities
 */

@interface TUCallDisplayContext : NSObject <NSCopying, NSSecureCoding> {
    NSString * _companyName;
    <TUCallDisplayContextDelegate> * _delegate;
    NSString * _firstName;
    NSString * _label;
    int  _legacyAddressBookIdentifier;
    NSString * _name;
    NSObject<OS_dispatch_queue> * _serialQueue;
    NSString * _suggestedName;
}

@property (nonatomic, copy) NSString *companyName;
@property (nonatomic) <TUCallDisplayContextDelegate> *delegate;
@property (nonatomic, copy) NSString *firstName;
@property (nonatomic, copy) NSString *label;
@property (nonatomic) int legacyAddressBookIdentifier;
@property (nonatomic, copy) NSString *name;
@property (nonatomic, retain) NSObject<OS_dispatch_queue> *serialQueue;
@property (nonatomic, copy) NSString *suggestedName;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (void)_initializeStateWithCall:(id)arg1;
- (id)companyName;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)delegate;
- (void)encodeWithCoder:(id)arg1;
- (id)firstName;
- (unsigned long long)hash;
- (id)init;
- (id)initWithCall:(id)arg1 serialQueue:(id)arg2;
- (id)initWithCoder:(id)arg1;
- (bool)isEqual:(id)arg1;
- (id)label;
- (int)legacyAddressBookIdentifier;
- (id)name;
- (id)serialQueue;
- (void)setCompanyName:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setFirstName:(id)arg1;
- (void)setLabel:(id)arg1;
- (void)setLegacyAddressBookIdentifier:(int)arg1;
- (void)setName:(id)arg1;
- (void)setSerialQueue:(id)arg1;
- (void)setSuggestedName:(id)arg1;
- (id)suggestedName;

@end
