/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/TelephonyUtilities.framework/TelephonyUtilities
 */

@interface TUCallSoundPlayer : NSObject {
    TUSoundPlayer * _player;
}

@property (nonatomic, retain) TUSoundPlayer *player;
@property (getter=isPlaying, nonatomic, readonly) bool playing;

- (void).cxx_destruct;
- (bool)attemptToPlaySoundType:(long long)arg1 forCall:(id)arg2;
- (bool)attemptToPlaySoundType:(long long)arg1 forCall:(id)arg2 completion:(id /* block */)arg3;
- (id)init;
- (bool)isPlaying;
- (id)player;
- (void)setPlayer:(id)arg1;
- (void)stopPlaying;

@end
