/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/KeyboardServices.framework/KeyboardServices
 */

@interface _KSTextReplacementManager : NSObject <_KSTextReplacementStoreProtocol, _KSTextReplacementSyncProtocol> {
    _KSTextReplacementCKStore * _ckStore;
    bool  _forceCloudKit;
    _KSTextReplacementLegacyStore * _legacyStore;
    bool  _legacyStoreDidSwitchToContainer;
    NSObject<_KSTextReplacementStoreProtocol> * _textReplacementStore;
}

@property (nonatomic, retain) _KSTextReplacementCKStore *ckStore;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic) bool forceCloudKit;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) _KSTextReplacementLegacyStore *legacyStore;
@property (nonatomic) bool legacyStoreDidSwitchToContainer;
@property (readonly) Class superclass;
@property (nonatomic, retain) NSObject<_KSTextReplacementStoreProtocol> *textReplacementStore;

- (void).cxx_destruct;
- (void)checkForMigration;
- (id)ckStore;
- (void)dealloc;
- (bool)deviceDidMigrate;
- (bool)forceCloudKit;
- (bool)forceCloudKitSync;
- (id)forwardingTargetForSelector:(SEL)arg1;
- (id)initWithDirectoryPath:(id)arg1;
- (id)legacyStore;
- (void)legacyStoreDidImportChanges;
- (bool)legacyStoreDidSwitchToContainer;
- (void)migrateLegacyStore;
- (void)migrateLocallyCheckCompatibility:(bool)arg1;
- (void)notifyTextReplacementDidChange;
- (void)pushAllLocalRecordsOnceIfNeeded;
- (void)requestSyncShouldPull:(bool)arg1 withCompletionHandler:(id /* block */)arg2;
- (void)respondToLegacyStoreNotif:(id)arg1;
- (void)respondToMigrationCompletion;
- (void)setCkStore:(id)arg1;
- (void)setForceCloudKit:(bool)arg1;
- (void)setLegacyStore:(id)arg1;
- (void)setLegacyStoreDidSwitchToContainer:(bool)arg1;
- (void)setTextReplacementStore:(id)arg1;
- (void)setupAssistaceDidComplete;
- (id)textReplacementStore;

@end
