/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/KeyboardServices.framework/KeyboardServices
 */

@interface _KSTRClient : NSObject {
    long long  _generation;
}

@property (nonatomic) long long generation;

- (void)cancel;
- (long long)generation;
- (id)init;
- (void)setGeneration:(long long)arg1;

@end
