/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppPredictionWidget.framework/AppPredictionWidget
 */

@interface APWSimpleBundleIdProvider : NSObject <APWBundleIdProviding> {
    NSString * _bundleIdentifier;
    unsigned char  _sources;
}

@property (nonatomic, readonly) NSString *bundleIdentifier;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) unsigned char sources;
@property (readonly) Class superclass;

+ (id)simpleBundleIdProvidersWithStrings:(id)arg1;

- (void).cxx_destruct;
- (id)bundleIdentifier;
- (id)description;
- (id)initWithBundleIdentifier:(id)arg1 sources:(unsigned char)arg2;
- (unsigned char)sources;

@end
