/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MarkupUI.framework/MarkupUI
 */

@interface MUCGPDFReader : NSObject

- (void)readAnnotationsFromCGPDFDocument:(struct CGPDFDocument { }*)arg1 toController:(id)arg2 replacedAnnotationMaps:(id*)arg3;

@end
