/* Generated by RuntimeBrowser
   Image: /usr/lib/libAWDSupportFramework.dylib
 */

@interface AWDDNSDomainStats : PBCodable <NSCopying> {
    struct { 
        unsigned int *list; 
        unsigned long long count; 
        unsigned long long size; 
    }  _answeredQuerySendCounts;
    NSString * _domain;
    struct { 
        unsigned int networkType : 1; 
    }  _has;
    int  _networkType;
    struct { 
        unsigned int *list; 
        unsigned long long count; 
        unsigned long long size; 
    }  _responseLatencyMs;
    struct { 
        unsigned int *list; 
        unsigned long long count; 
        unsigned long long size; 
    }  _unansweredQuerySendCounts;
}

@property (nonatomic, readonly) unsigned int*answeredQuerySendCounts;
@property (nonatomic, readonly) unsigned long long answeredQuerySendCountsCount;
@property (nonatomic, retain) NSString *domain;
@property (nonatomic, readonly) bool hasDomain;
@property (nonatomic) bool hasNetworkType;
@property (nonatomic) int networkType;
@property (nonatomic, readonly) unsigned int*responseLatencyMs;
@property (nonatomic, readonly) unsigned long long responseLatencyMsCount;
@property (nonatomic, readonly) unsigned int*unansweredQuerySendCounts;
@property (nonatomic, readonly) unsigned long long unansweredQuerySendCountsCount;

- (int)StringAsNetworkType:(id)arg1;
- (void)addAnsweredQuerySendCount:(unsigned int)arg1;
- (void)addResponseLatencyMs:(unsigned int)arg1;
- (void)addUnansweredQuerySendCount:(unsigned int)arg1;
- (unsigned int)answeredQuerySendCountAtIndex:(unsigned long long)arg1;
- (unsigned int*)answeredQuerySendCounts;
- (unsigned long long)answeredQuerySendCountsCount;
- (void)clearAnsweredQuerySendCounts;
- (void)clearResponseLatencyMs;
- (void)clearUnansweredQuerySendCounts;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (id)description;
- (id)dictionaryRepresentation;
- (id)domain;
- (bool)hasDomain;
- (bool)hasNetworkType;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (int)networkType;
- (id)networkTypeAsString:(int)arg1;
- (bool)readFrom:(id)arg1;
- (unsigned int*)responseLatencyMs;
- (unsigned int)responseLatencyMsAtIndex:(unsigned long long)arg1;
- (unsigned long long)responseLatencyMsCount;
- (void)setAnsweredQuerySendCounts:(unsigned int*)arg1 count:(unsigned long long)arg2;
- (void)setDomain:(id)arg1;
- (void)setHasNetworkType:(bool)arg1;
- (void)setNetworkType:(int)arg1;
- (void)setResponseLatencyMs:(unsigned int*)arg1 count:(unsigned long long)arg2;
- (void)setUnansweredQuerySendCounts:(unsigned int*)arg1 count:(unsigned long long)arg2;
- (unsigned int)unansweredQuerySendCountAtIndex:(unsigned long long)arg1;
- (unsigned int*)unansweredQuerySendCounts;
- (unsigned long long)unansweredQuerySendCountsCount;
- (void)writeTo:(id)arg1;

@end
