/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DiagnosticsSupport.framework/DiagnosticsSupport
 */

@interface DSHandler : NSObject {
    <DSHardwareButtonEventDelegate> * _delegate;
}

@property (nonatomic) <DSHardwareButtonEventDelegate> *delegate;

- (void).cxx_destruct;
- (id)delegate;
- (void)setDelegate:(id)arg1;

@end
