/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DiagnosticsSupport.framework/DiagnosticsSupport
 */

@interface DSHardwareButtonEventManager : NSObject {
    NSLock * _buttonDelegateChangeLock;
    struct __IOHIDEventSystemClient { } * _buttonHIDSystemClient;
    NSMutableArray * _digitalCrownButtonDelegates;
    NSMutableArray * _gameControllerMenuButtonDelegates;
    NSMutableArray * _homeButtonDelegates;
    NSObject<OS_dispatch_queue> * _mButtonEventQueue;
    NSMutableArray * _remoteMenuHomeButtonDelegates;
    NSMutableArray * _ringerSwitchDelegates;
    NSMutableArray * _sideButtonDelegates;
    NSMutableArray * _siriButtonDelegates;
    NSMutableArray * _siriRemoteMenuButtonDelegates;
    NSMutableArray * _sleepWakeButtonDelegates;
    NSMutableArray * _volumeDecrementButtonDelegates;
    NSMutableArray * _volumeIncrementButtonDelegates;
}

@property (nonatomic, retain) NSLock *buttonDelegateChangeLock;
@property (nonatomic) struct __IOHIDEventSystemClient { }*buttonHIDSystemClient;
@property (nonatomic, retain) NSMutableArray *digitalCrownButtonDelegates;
@property (nonatomic, retain) NSMutableArray *gameControllerMenuButtonDelegates;
@property (nonatomic, retain) NSMutableArray *homeButtonDelegates;
@property (nonatomic, retain) NSObject<OS_dispatch_queue> *mButtonEventQueue;
@property (nonatomic, retain) NSMutableArray *remoteMenuHomeButtonDelegates;
@property (nonatomic, retain) NSMutableArray *ringerSwitchDelegates;
@property (nonatomic, retain) NSMutableArray *sideButtonDelegates;
@property (nonatomic, retain) NSMutableArray *siriButtonDelegates;
@property (nonatomic, retain) NSMutableArray *siriRemoteMenuButtonDelegates;
@property (nonatomic, retain) NSMutableArray *sleepWakeButtonDelegates;
@property (nonatomic, retain) NSMutableArray *volumeDecrementButtonDelegates;
@property (nonatomic, retain) NSMutableArray *volumeIncrementButtonDelegates;

+ (id)sharedInstance;

- (void).cxx_destruct;
- (id)buttonDelegateChangeLock;
- (struct __IOHIDEventSystemClient { }*)buttonHIDSystemClient;
- (void)cleanUpSystemClient;
- (id)digitalCrownButtonDelegates;
- (id)gameControllerMenuButtonDelegates;
- (id)homeButtonDelegates;
- (id)init;
- (id)mButtonEventQueue;
- (void)postButtonEventsCompletedNotificationOnSwallowed:(int)arg1 upEvent:(bool)arg2;
- (void)registerButtonEventDelegate:(id)arg1 forButtons:(unsigned long long)arg2;
- (id)remoteMenuHomeButtonDelegates;
- (void)removeEventHandler:(id /* block */)arg1;
- (id)ringerSwitchDelegates;
- (void)setButtonDelegateChangeLock:(id)arg1;
- (void)setButtonHIDSystemClient:(struct __IOHIDEventSystemClient { }*)arg1;
- (void)setDigitalCrownButtonDelegates:(id)arg1;
- (void)setGameControllerMenuButtonDelegates:(id)arg1;
- (void)setHomeButtonDelegates:(id)arg1;
- (void)setMButtonEventQueue:(id)arg1;
- (void)setRemoteMenuHomeButtonDelegates:(id)arg1;
- (void)setRingerSwitchDelegates:(id)arg1;
- (void)setSideButtonDelegates:(id)arg1;
- (void)setSiriButtonDelegates:(id)arg1;
- (void)setSiriRemoteMenuButtonDelegates:(id)arg1;
- (void)setSleepWakeButtonDelegates:(id)arg1;
- (void)setVolumeDecrementButtonDelegates:(id)arg1;
- (void)setVolumeIncrementButtonDelegates:(id)arg1;
- (id)sideButtonDelegates;
- (id)siriButtonDelegates;
- (id)siriRemoteMenuButtonDelegates;
- (id)sleepWakeButtonDelegates;
- (void)startEventManagerWithPriority:(int)arg1 buttonEventDelegate:(id)arg2 forButtons:(unsigned long long)arg3;
- (void)stopEventManager;
- (int)triggerEventWithDelegates:(id)arg1 event:(unsigned long long)arg2;
- (id)volumeDecrementButtonDelegates;
- (id)volumeIncrementButtonDelegates;

@end
