/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpotlightUI.framework/SpotlightUI
 */

@interface SPUISearchResultHandler : NSObject <SKStoreProductViewControllerDelegate, UIDocumentInteractionControllerDelegate> {
    <SPUISearchResultHandlerDelegate> * _delegate;
}

@property (readonly, copy) NSString *debugDescription;
@property <SPUISearchResultHandlerDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

+ (id)sharedResultHandler;

- (void).cxx_destruct;
- (bool)asyncViewControllerForResult:(id)arg1 preview:(bool)arg2 completion:(id /* block */)arg3;
- (id)delegate;
- (void)handleResultSelected:(id)arg1;
- (void)modalViewControllerClosed;
- (void)presentViewController:(id)arg1;
- (void)productViewControllerDidFinish:(id)arg1;
- (void)requestAuthAndPresentViewController:(id)arg1;
- (void)requestAuthIfNecessaryAndPresentViewController:(id)arg1;
- (void)setDelegate:(id)arg1;
- (id)viewControllerForResult:(id)arg1 preview:(bool)arg2;

@end
