/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpotlightUI.framework/SpotlightUI
 */

@interface SPUIImageUtilities : NSObject

+ (unsigned long long)defaultStyle;
+ (id)generateImageNamed:(id)arg1 withColor:(id)arg2 forClass:(Class)arg3 isKitImage:(bool)arg4;
+ (unsigned long long)previewStyle;

@end
