/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface AWDHomeKitHomeSharing : PBCodable <NSCopying> {
    int  _errorCode;
    struct { 
        unsigned int timestamp : 1; 
        unsigned int errorCode : 1; 
        unsigned int invitationSide : 1; 
        unsigned int inviteDelay : 1; 
    }  _has;
    int  _invitationSide;
    unsigned int  _inviteDelay;
    unsigned long long  _timestamp;
}

@property (nonatomic) int errorCode;
@property (nonatomic) bool hasErrorCode;
@property (nonatomic) bool hasInvitationSide;
@property (nonatomic) bool hasInviteDelay;
@property (nonatomic) bool hasTimestamp;
@property (nonatomic) int invitationSide;
@property (nonatomic) unsigned int inviteDelay;
@property (nonatomic) unsigned long long timestamp;

- (int)StringAsInvitationSide:(id)arg1;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (int)errorCode;
- (bool)hasErrorCode;
- (bool)hasInvitationSide;
- (bool)hasInviteDelay;
- (bool)hasTimestamp;
- (unsigned long long)hash;
- (int)invitationSide;
- (id)invitationSideAsString:(int)arg1;
- (unsigned int)inviteDelay;
- (bool)isEqual:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (bool)readFrom:(id)arg1;
- (void)setErrorCode:(int)arg1;
- (void)setHasErrorCode:(bool)arg1;
- (void)setHasInvitationSide:(bool)arg1;
- (void)setHasInviteDelay:(bool)arg1;
- (void)setHasTimestamp:(bool)arg1;
- (void)setInvitationSide:(int)arg1;
- (void)setInviteDelay:(unsigned int)arg1;
- (void)setTimestamp:(unsigned long long)arg1;
- (unsigned long long)timestamp;
- (void)writeTo:(id)arg1;

@end
