/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDAWDLogEventObserver : NSObject <HMDLogEventObserver>

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

+ (void)_submitAWDMetric:(id)arg1 type:(unsigned int)arg2;
+ (void)initialize;
+ (id)resultWithType:(unsigned long long)arg1 resultCode:(int)arg2 duration:(unsigned int)arg3 transportType:(unsigned long long)arg4 isClient:(bool)arg5;
+ (id)sharedAWDServerConnection;
+ (id)stringForMetricType:(unsigned int)arg1;

- (void)dispatcher:(id)arg1 didReceiveEvent:(id)arg2;

@end
