/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDAccessoryPairingEvent : HMDLogEvent <HMDAWDLogEvent> {
    HMDAccessory * _pairedAccessory;
    HAPAccessoryServer * _server;
    HMDUnpairedAccessory * _unpairedAccessory;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) HMDAccessory *pairedAccessory;
@property (nonatomic, retain) HAPAccessoryServer *server;
@property (readonly) Class superclass;
@property (nonatomic, readonly) HMDUnpairedAccessory *unpairedAccessory;

+ (void)initialize;
+ (id)pairingAccessory:(id)arg1;
+ (id)uuid;

- (void).cxx_destruct;
- (unsigned int)AWDMessageType;
- (id)initPairingEvent:(id)arg1;
- (id)metricForAWD;
- (id)pairedAccessory;
- (void)pairedAccessory:(id)arg1;
- (void)pairedToServer:(id)arg1;
- (id)server;
- (void)setPairedAccessory:(id)arg1;
- (void)setServer:(id)arg1;
- (id)unpairedAccessory;

@end
