/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDCameraSnapshotIDSStream : NSObject <IDSServiceDelegate> {
    IDSService * _idsProxyService;
    HAPOSTransaction * _snapshotStreamTransaction;
    NSUUID * _uniqueIdentifier;
    NSObject<OS_dispatch_queue> * _workQueue;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) IDSService *idsProxyService;
@property (nonatomic, retain) HAPOSTransaction *snapshotStreamTransaction;
@property (readonly) Class superclass;
@property (nonatomic, readonly) NSUUID *uniqueIdentifier;
@property (nonatomic, readonly) NSObject<OS_dispatch_queue> *workQueue;

- (void).cxx_destruct;
- (void)_reset;
- (id)idsProxyService;
- (id)init;
- (void)setSnapshotStreamTransaction:(id)arg1;
- (id)snapshotStreamTransaction;
- (id)uniqueIdentifier;
- (id)workQueue;

@end
