/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDCameraIDSSessionInitiator : HMDCameraIDSSessionHandler <HMDCameraRemoteStreamSenderProtocol, IDSServiceDelegate, IDSSessionDelegate> {
    <HMDCameraIDSSessionInitiatorDelegate> * _delegate;
    NSObject<OS_dispatch_queue> * _delegateQueue;
    NSString * _destinationID;
    AVCPacketRelay * _packetRelay;
    HAPOSTransaction * _packetRelayTransaction;
}

@property (readonly, copy) NSString *debugDescription;
@property (nonatomic, readonly) <HMDCameraIDSSessionInitiatorDelegate> *delegate;
@property (nonatomic, readonly) NSObject<OS_dispatch_queue> *delegateQueue;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly, copy) NSString *destinationID;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) AVCPacketRelay *packetRelay;
@property (nonatomic, retain) HAPOSTransaction *packetRelayTransaction;
@property (readonly) Class superclass;

+ (id)logCategory;

- (void).cxx_destruct;
- (void)_callSessionEnded:(id)arg1;
- (void)_callSessionStarted:(id)arg1;
- (void)_reset;
- (void)_sendInvitation;
- (void)_startPacketRelayWithVideoSocket:(int)arg1 videoNetworkConfig:(id)arg2 cameraVideoSSRC:(unsigned int)arg3 audioSocket:(int)arg4 audioNetworkConfig:(id)arg5 cameraAudioSSRC:(unsigned int)arg6;
- (id)delegate;
- (id)delegateQueue;
- (id)destinationID;
- (id)initWithSessionID:(id)arg1 destinationID:(id)arg2 delegate:(id)arg3 delegateQueue:(id)arg4;
- (id)logIdentifier;
- (void)openRelaySession;
- (id)packetRelay;
- (id)packetRelayTransaction;
- (void)session:(id)arg1 receivedInvitationAcceptFromID:(id)arg2;
- (void)session:(id)arg1 receivedInvitationCancelFromID:(id)arg2;
- (void)session:(id)arg1 receivedInvitationDeclineFromID:(id)arg2;
- (void)sessionEnded:(id)arg1 withReason:(unsigned int)arg2 error:(id)arg3;
- (void)sessionStarted:(id)arg1;
- (void)setPacketRelay:(id)arg1;
- (void)setPacketRelayTransaction:(id)arg1;
- (void)startPacketRelayWithVideoSocket:(int)arg1 videoNetworkConfig:(id)arg2 cameraVideoSSRC:(unsigned int)arg3 audioSocket:(int)arg4 audioNetworkConfig:(id)arg5 cameraAudioSSRC:(unsigned int)arg6;

@end
