/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDCameraSnapshotIDSStreamInitiator : HMDCameraSnapshotIDSStream <HMFLogging, IDSServiceDelegate> {
    <HMDCameraSnapshotIDSStreamInitiatorDelegate> * _delegate;
    NSObject<OS_dispatch_queue> * _delegateQueue;
    NSString * _destinationID;
    NSString * _filePath;
    NSString * _requestIdentifier;
    NSString * _sendFileIdentifier;
}

@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <HMDCameraSnapshotIDSStreamInitiatorDelegate> *delegate;
@property (nonatomic, retain) NSObject<OS_dispatch_queue> *delegateQueue;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) NSString *destinationID;
@property (nonatomic, retain) NSString *filePath;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) NSString *requestIdentifier;
@property (nonatomic, retain) NSString *sendFileIdentifier;
@property (readonly) Class superclass;

+ (id)logCategory;

- (void).cxx_destruct;
- (void)_callFileTransferFailed:(id)arg1;
- (void)_reset;
- (void)_sendFile:(id)arg1;
- (void)dealloc;
- (id)delegate;
- (id)delegateQueue;
- (id)destinationID;
- (id)filePath;
- (id)initWithRequestIdentifier:(id)arg1 destinationID:(id)arg2 delegate:(id)arg3 queue:(id)arg4;
- (id)logIdentifier;
- (id)requestIdentifier;
- (void)sendFile:(id)arg1;
- (id)sendFileIdentifier;
- (void)service:(id)arg1 account:(id)arg2 identifier:(id)arg3 didSendWithSuccess:(bool)arg4 error:(id)arg5;
- (void)setDelegate:(id)arg1;
- (void)setDelegateQueue:(id)arg1;
- (void)setDestinationID:(id)arg1;
- (void)setFilePath:(id)arg1;
- (void)setRequestIdentifier:(id)arg1;
- (void)setSendFileIdentifier:(id)arg1;

@end
