/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDCharacteristicEnableNotificationLogEvent : HMDLogEvent <HMDAWDLogEvent> {
    HMDAccessory * _accessory;
    NSArray * _characteristics;
    bool  _enabled;
    bool  _isClient;
    unsigned long long  _transportType;
}

@property (nonatomic, readonly) HMDAccessory *accessory;
@property (nonatomic, readonly) NSArray *characteristics;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) bool enabled;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) bool isClient;
@property (readonly) Class superclass;
@property (nonatomic, readonly) unsigned long long transportType;

+ (void)initialize;
+ (id)logEventEnableNotification:(bool)arg1 characteristics:(id)arg2 accessory:(id)arg3 isClient:(bool)arg4 transportType:(unsigned long long)arg5;
+ (id)uuid;

- (void).cxx_destruct;
- (unsigned int)AWDMessageType;
- (id)accessory;
- (id)characteristics;
- (bool)enabled;
- (id)initWithEnabled:(bool)arg1 characteristics:(id)arg2 accessory:(id)arg3 isClient:(bool)arg4 transportType:(unsigned long long)arg5;
- (bool)isClient;
- (id)metricForAWD;
- (unsigned long long)transportType;

@end
