/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDCameraStreamManagerSession : NSObject {
    HMFMessage * _currentMessage;
    NSString * _currentSessionID;
    NSString * _destinationID;
    <HMDCameraStreamControlManagerProtocol> * _streamControlManager;
    HMFTimer * _streamSetupTimer;
    NSString * _streamShowingAppIdentifier;
}

@property (nonatomic, retain) HMFMessage *currentMessage;
@property (nonatomic, readonly) NSString *currentSessionID;
@property (nonatomic, readonly) NSString *destinationID;
@property (nonatomic, readonly) <HMDCameraStreamControlManagerProtocol> *streamControlManager;
@property (nonatomic, readonly) HMFTimer *streamSetupTimer;
@property (nonatomic, readonly) NSString *streamShowingAppIdentifier;

- (void).cxx_destruct;
- (id)currentMessage;
- (id)currentSessionID;
- (id)destinationID;
- (id)initWithSessionID:(id)arg1 destinationID:(id)arg2 streamShowingAppIdentifier:(id)arg3 controlManager:(id)arg4 setupWaitPeriod:(unsigned long long)arg5;
- (void)setCurrentMessage:(id)arg1;
- (id)streamControlManager;
- (id)streamSetupTimer;
- (id)streamShowingAppIdentifier;

@end
