/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDSyncOperationManager : NSObject {
    NSObject<OS_dispatch_queue> * _clientQueue;
    NSMutableArray * _cloudMergeOperations;
    NSMutableArray * _cloudPushOperations;
    HMDHomeManager * _homeManager;
    NSMutableArray * _idsMergeOperations;
    long long  _pauseCloudPushLevel;
    NSObject<OS_dispatch_queue> * _propertyQueue;
    NSObject<OS_dispatch_queue> * _workQueue;
}

@property (nonatomic, readonly) NSObject<OS_dispatch_queue> *clientQueue;
@property (nonatomic, retain) NSMutableArray *cloudMergeOperations;
@property (nonatomic, retain) NSMutableArray *cloudPushOperations;
@property (nonatomic) HMDHomeManager *homeManager;
@property (nonatomic, retain) NSMutableArray *idsMergeOperations;
@property (nonatomic) long long pauseCloudPushLevel;
@property (nonatomic, readonly) NSObject<OS_dispatch_queue> *propertyQueue;
@property (nonatomic, readonly) NSObject<OS_dispatch_queue> *workQueue;

- (void).cxx_destruct;
- (void)_handleNextOperation;
- (void)addOperation:(id)arg1;
- (id)clientQueue;
- (id)cloudMergeOperations;
- (id)cloudPushOperations;
- (id)dequeueNextOperation;
- (id)description;
- (id)dumpState;
- (id)homeManager;
- (id)idsMergeOperations;
- (id)initWithClientQueue:(id)arg1 homeManager:(id)arg2;
- (void)killCloudPushAndResume;
- (void)pauseCloudPush;
- (long long)pauseCloudPushLevel;
- (id)propertyQueue;
- (void)resumeCloudPush;
- (void)setCloudMergeOperations:(id)arg1;
- (void)setCloudPushOperations:(id)arg1;
- (void)setHomeManager:(id)arg1;
- (void)setIdsMergeOperations:(id)arg1;
- (void)setPauseCloudPushLevel:(long long)arg1;
- (id)workQueue;

@end
