/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDSnapshotFile : NSObject <HMFLogging> {
    NSString * _filePath;
    NSString * _logString;
    NSNumber * _slotIdentifier;
    CAContext * _snapshotContext;
    NSDate * _snapshotTimestamp;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) NSString *filePath;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSString *logString;
@property (nonatomic, retain) NSNumber *slotIdentifier;
@property (nonatomic, retain) CAContext *snapshotContext;
@property (nonatomic, readonly) NSDate *snapshotTimestamp;
@property (readonly) Class superclass;

+ (id)logCategory;

- (void).cxx_destruct;
- (struct CGImage { }*)createSnapshotCGImageRef:(id)arg1;
- (void)dealloc;
- (id)description;
- (id)filePath;
- (unsigned long long)hash;
- (id)initWithImageDirectory:(id)arg1;
- (id)initWithImageDirectory:(id)arg1 data:(id)arg2;
- (bool)isEqual:(id)arg1;
- (id)logIdentifier;
- (id)logString;
- (void)setSlotIdentifier:(id)arg1;
- (void)setSnapshotContext:(id)arg1;
- (id)slotIdentifier;
- (id)snapshotContext;
- (id)snapshotTimestamp;
- (void)updateSlotIdentifierWithContext:(id)arg1;

@end
