/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDSnapshotRequestHandler : NSObject <HMFLogging, HMFTimerDelegate> {
    HMDAccessory * _accessory;
    NSString * _imageCacheDirectory;
    NSString * _logString;
    HMDSnapshotFile * _mostRecentSnapshot;
    HMFTimer * _mostRecentSnapshotInvalidationTimer;
    NSMutableArray * _pendingRequests;
    NSObject<OS_dispatch_queue> * _workQueue;
}

@property (nonatomic, readonly) HMDAccessory *accessory;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSString *imageCacheDirectory;
@property (nonatomic, readonly) NSString *logString;
@property (nonatomic, retain) HMDSnapshotFile *mostRecentSnapshot;
@property (nonatomic, retain) HMFTimer *mostRecentSnapshotInvalidationTimer;
@property (nonatomic, readonly) NSMutableArray *pendingRequests;
@property (readonly) Class superclass;
@property (nonatomic, readonly) NSObject<OS_dispatch_queue> *workQueue;

+ (id)logCategory;

- (void).cxx_destruct;
- (void)_handleImageResourceData:(id)arg1 error:(id)arg2;
- (id)accessory;
- (id)imageCacheDirectory;
- (id)initWithAccessory:(id)arg1 imageCacheDirectory:(id)arg2;
- (id)logIdentifier;
- (id)logString;
- (id)mostRecentSnapshot;
- (id)mostRecentSnapshotInvalidationTimer;
- (id)pendingRequests;
- (void)requestSnapshot:(id)arg1 completionHandler:(id /* block */)arg2;
- (void)setMostRecentSnapshot:(id)arg1;
- (void)setMostRecentSnapshotInvalidationTimer:(id)arg1;
- (void)timerDidFire:(id)arg1;
- (id)workQueue;

@end
