/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriCore.framework/SiriCore
 */

@interface SiriCoreLocalSpeechRecognizer : NSObject <AFSpeechServiceDelegate> {
    <SiriCoreLocalSpeechRecognizerDelegate> * _delegate;
    SiriCoreLocalSpeechDESRecord * _desRecord;
    NSXPCConnection * _esConnection;
    NSObject<OS_dispatch_queue> * _queue;
    bool  _recognitionActive;
    NSString * _siriLanguage;
}

@property (readonly, copy) NSString *debugDescription;
@property (nonatomic, readonly) <SiriCoreLocalSpeechRecognizerDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, copy) NSString *siriLanguage;
@property (readonly) Class superclass;

+ (id)speechProfileDataLastModifiedDataForLanguage:(id)arg1;

- (void).cxx_destruct;
- (id)_connection;
- (void)_readProfileAndUserDataWithLanguage:(id)arg1 allowOverride:(bool)arg2 tryLastDESRecipe:(bool)arg3 completion:(id /* block */)arg4;
- (id)_service;
- (id)_serviceWithFunctionName:(id)arg1 errorHandler:(id /* block */)arg2;
- (void)addAudioPacket:(id)arg1;
- (void)createSpeechProfileWithLanguage:(id)arg1 JSONData:(id)arg2 completion:(id /* block */)arg3;
- (id)delegate;
- (void)disableDESWithCompletion:(id /* block */)arg1;
- (void)fetchAssetsForLanguage:(id)arg1 completion:(id /* block */)arg2;
- (void)finishAudio;
- (void)getOfflineDictationStatusWithCompletion:(id /* block */)arg1;
- (id)init;
- (id)initWithDelegate:(id)arg1;
- (void)invalidate;
- (void)runAdaptationRecipeEvaluation:(id)arg1 localSpeechDESRecord:(id)arg2 completion:(id /* block */)arg3;
- (void)setSiriLanguage:(id)arg1;
- (id)siriLanguage;
- (oneway void)speechServiceDidFinishRecognitionWithError:(id)arg1;
- (oneway void)speechServiceDidProcessAudioDuration:(double)arg1;
- (oneway void)speechServiceDidRecognizePhrases:(id)arg1;
- (oneway void)speechServiceDidRecognizeTokens:(id)arg1;
- (void)startSpeechRecognitionWithLanguage:(id)arg1 task:(id)arg2 context:(id)arg3 narrowband:(bool)arg4 detectUtterances:(bool)arg5 maximumRecognitionDuration:(double)arg6 didStartHandler:(id /* block */)arg7;
- (void)updateSpeechProfileWithLanguage:(id)arg1 userData:(id)arg2 completion:(id /* block */)arg3;

@end
