/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CloudKit.framework/CloudKit
 */

@interface CKAcceptSharesOperationInfo : CKOperationInfo <NSSecureCoding> {
    bool  _isUsingLegacyAPI;
    NSArray * _shareMetadatasToAccept;
}

@property (nonatomic) bool isUsingLegacyAPI;
@property (nonatomic, retain) NSArray *shareMetadatasToAccept;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (bool)isUsingLegacyAPI;
- (void)setIsUsingLegacyAPI:(bool)arg1;
- (void)setShareMetadatasToAccept:(id)arg1;
- (id)shareMetadatasToAccept;

@end
