/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CloudKit.framework/CloudKit
 */

@interface CKFetchServerEnvironmentOperationResult : CKOperationResult <NSSecureCoding> {
    long long  _environment;
}

@property (nonatomic) long long environment;

+ (bool)supportsSecureCoding;

- (void)encodeWithCoder:(id)arg1;
- (long long)environment;
- (id)initWithCoder:(id)arg1;
- (void)setEnvironment:(long long)arg1;

@end
