/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsCore.framework/NewsCore
 */

@interface FCAddRSSFeedCommand : FCCommand {
    NSString * _addRSSFeedTitle;
    NSURL * _addRSSFeedURL;
}

@property (nonatomic, copy) NSString *addRSSFeedTitle;
@property (nonatomic, copy) NSURL *addRSSFeedURL;

- (void).cxx_destruct;
- (id)addRSSFeedTitle;
- (id)addRSSFeedURL;
- (void)encodeWithCoder:(id)arg1;
- (void)executeWithContext:(id)arg1 delegate:(id)arg2;
- (id)initWithAddRSSFeedURL:(id)arg1 title:(id)arg2;
- (id)initWithCoder:(id)arg1;
- (void)setAddRSSFeedTitle:(id)arg1;
- (void)setAddRSSFeedURL:(id)arg1;

@end
