/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsCore.framework/NewsCore
 */

@interface FCAssetHandleDownloadRequest : NSObject <FCOperationCanceling, FCOperationPrioritizing> {
    id /* block */  _cancelHandler;
    long long  _networkPriority;
    id /* block */  _priorityHandler;
}

@property (nonatomic, copy) id /* block */ cancelHandler;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic) long long networkPriority;
@property (nonatomic, copy) id /* block */ priorityHandler;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)cancel;
- (id /* block */)cancelHandler;
- (long long)networkPriority;
- (id /* block */)priorityHandler;
- (void)setCancelHandler:(id /* block */)arg1;
- (void)setNetworkPriority:(long long)arg1;
- (void)setPriorityHandler:(id /* block */)arg1;

@end
