/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsCore.framework/NewsCore
 */

@interface FCCKOperation : FCOperation

@property (nonatomic, readonly) long long queuePriorityForChildCKOperation;

- (bool)canRetryWithError:(id)arg1 retryAfter:(double*)arg2;
- (unsigned long long)maxRetries;
- (long long)queuePriorityForChildCKOperation;

@end
