/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsCore.framework/NewsCore
 */

@interface FCCKOrderFeedResponse : NSObject {
    NSString * _feedID;
    NSArray * _feedItemAndArticleRecords;
    bool  _reachedEnd;
    bool  _reachedMinOrder;
    bool  _reachedOrderLimit;
    bool  _wasDropped;
}

@property (nonatomic, copy) NSString *feedID;
@property (nonatomic, copy) NSArray *feedItemAndArticleRecords;
@property (nonatomic) bool reachedEnd;
@property (nonatomic, readonly) bool reachedMinOrder;
@property (nonatomic) bool reachedOrderLimit;
@property (nonatomic) bool wasDropped;

- (void).cxx_destruct;
- (id)description;
- (id)feedID;
- (id)feedItemAndArticleRecords;
- (bool)reachedEnd;
- (bool)reachedMinOrder;
- (bool)reachedOrderLimit;
- (void)setFeedID:(id)arg1;
- (void)setFeedItemAndArticleRecords:(id)arg1;
- (void)setReachedEnd:(bool)arg1;
- (void)setReachedOrderLimit:(bool)arg1;
- (void)setWasDropped:(bool)arg1;
- (bool)wasDropped;

@end
