/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsCore.framework/NewsCore
 */

@interface FCContentContext : NSObject <FCCKDatabaseDelegate, FCContentContext> {
    FCAppConfiguration * _appConfiguration;
    FCArticleController * _articleController;
    FCAssetManager * _assetManager;
    NSString * _contentDirectory;
    NSString * _contentStoreFrontID;
    FCFlintResourceManager * _flintResourceManager;
    FCContentContextInternal * _internalContentContext;
    FCTagController * _tagController;
}

@property (nonatomic, readonly) FCAppConfiguration *appConfiguration;
@property (nonatomic, readonly) FCArticleController *articleController;
@property (nonatomic, readonly) FCAssetManager *assetManager;
@property (nonatomic, copy) NSString *contentDirectory;
@property (nonatomic, readonly, copy) NSString *contentStoreFrontID;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) FCFlintResourceManager *flintResourceManager;
@property (nonatomic, readonly) bool hasBeenRateLimited;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) FCContentContextInternal *internalContentContext;
@property (readonly) Class superclass;
@property (nonatomic, readonly) FCTagController *tagController;

- (void).cxx_destruct;
- (id)appConfiguration;
- (id)articleController;
- (id)assetManager;
- (void)clearCloudKitCaches;
- (id)contentDirectory;
- (id)contentStoreFrontID;
- (void)databaseHasBeenRateLimited:(id)arg1 retryAfter:(double)arg2;
- (void)enableFlushing;
- (id)flintResourceManager;
- (bool)hasBeenRateLimited;
- (id)initWithContentDatabase:(id)arg1 contentContainer:(id)arg2 contentHostDirectory:(id)arg3 contentDirectory:(id)arg4 networkBehaviorMonitor:(id)arg5 contentStoreFrontID:(id)arg6 setupExcerptURLProtocol:(bool)arg7;
- (id)initWithContentHostDirectory:(id)arg1 networkBehaviorMonitor:(id)arg2 contentStoreFrontID:(id)arg3;
- (id)internalContentContext;
- (void)setContentDirectory:(id)arg1;
- (void)setInternalContentContext:(id)arg1;
- (id)tagController;

@end
