/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsCore.framework/NewsCore
 */

@interface FCHeadlineClusteringRules : NSObject {
    unsigned long long  _maxCluserSize;
    unsigned long long  _minCluserSize;
    FCSolConfiguration * _solConfiguration;
}

@property (nonatomic, readonly) unsigned long long maxCluserSize;
@property (nonatomic, readonly) unsigned long long minCluserSize;
@property (nonatomic, retain) FCSolConfiguration *solConfiguration;

+ (id)defaultRules;

- (void).cxx_destruct;
- (id)init;
- (id)initWithMinClusterSize:(unsigned long long)arg1 maxClusterSize:(unsigned long long)arg2;
- (id)initWithMinClusterSize:(unsigned long long)arg1 maxClusterSize:(unsigned long long)arg2 solConfiguration:(id)arg3;
- (unsigned long long)maxCluserSize;
- (unsigned long long)minCluserSize;
- (void)setSolConfiguration:(id)arg1;
- (id)solConfiguration;

@end
