/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsCore.framework/NewsCore
 */

@interface FCNotificationController : NSObject <FCUserInfoObserving> {
    FCCommandQueue * _commandQueue;
    NSString * _deviceToken;
    NSString * _notificationsUserID;
    NSString * _storefrontID;
    FCUserInfo * _userInfo;
}

@property (nonatomic, retain) FCCommandQueue *commandQueue;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, copy) NSString *deviceToken;
@property (readonly) unsigned long long hash;
@property (nonatomic, copy) NSString *notificationsUserID;
@property (nonatomic, copy) NSString *storefrontID;
@property (readonly) Class superclass;
@property (nonatomic, retain) FCUserInfo *userInfo;

- (void).cxx_destruct;
- (void)_registerDeviceToken:(id)arg1;
- (id)commandQueue;
- (void)dealloc;
- (id)deviceToken;
- (id)init;
- (id)initWithUserInfo:(id)arg1 storefrontID:(id)arg2 commandQueue:(id)arg3;
- (id)notificationsUserID;
- (void)registerDeviceToken:(id)arg1;
- (bool)registerNotificationsForTagID:(id)arg1 isPaid:(bool)arg2;
- (void)setCommandQueue:(id)arg1;
- (void)setDeviceToken:(id)arg1;
- (void)setNotificationsUserID:(id)arg1;
- (void)setStorefrontID:(id)arg1;
- (void)setUserInfo:(id)arg1;
- (id)storefrontID;
- (bool)unregisterNotificationsForTagID:(id)arg1;
- (id)userInfo;
- (void)userInfoDidChangeNotificationUserID:(id)arg1;

@end
