/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsCore.framework/NewsCore
 */

@interface FCResourceRecordSource : FCRecordSource

+ (unsigned long long)dataSizeLimit;
+ (id)desiredKeys;
+ (id)recordFromCKRecord:(id)arg1 base:(id)arg2;
+ (id)recordType;
+ (id)storeFilename;
+ (unsigned long long)storeVersion;

@end
