/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsCore.framework/NewsCore
 */

@interface FCTopicFeedGroupEmittingOperation : FCFeedGroupEmittingOperation {
    <FCHeadlineClustering> * _headlineClusterer;
}

@property (nonatomic, retain) <FCHeadlineClustering> *headlineClusterer;

- (void).cxx_destruct;
- (id)_editorialFeedTransformation;
- (id)_joinedFeedTransformation;
- (id)_nonEditorialFeedTransformationWithFeedContext:(id)arg1;
- (id)_sortTopicsForDisplay:(id)arg1 clusteredHeadlines:(id)arg2;
- (id)headlineClusterer;
- (void)performOperation;
- (void)setHeadlineClusterer:(id)arg1;

@end
