/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsCore.framework/NewsCore
 */

@interface FCWebAccessEntry : NSObject {
    NSString * _email;
    NSString * _identifier;
    NSDate * _lastRetryAttemptTime;
    NSString * _purchaseReceipt;
    NSString * _tagID;
}

@property (nonatomic, copy) NSString *email;
@property (nonatomic, copy) NSString *identifier;
@property (nonatomic, copy) NSDate *lastRetryAttemptTime;
@property (nonatomic, copy) NSString *purchaseReceipt;
@property (nonatomic, copy) NSString *tagID;

- (void).cxx_destruct;
- (id)dictionaryRepresentation;
- (id)email;
- (id)identifier;
- (id)initWithEntryID:(id)arg1 dictionaryRepresentation:(id)arg2;
- (id)initWithEntryID:(id)arg1 tagID:(id)arg2 lastRetryAttemptTime:(id)arg3 email:(id)arg4 purchaseReceipt:(id)arg5;
- (id)lastRetryAttemptTime;
- (id)purchaseReceipt;
- (void)setEmail:(id)arg1;
- (void)setIdentifier:(id)arg1;
- (void)setLastRetryAttemptTime:(id)arg1;
- (void)setPurchaseReceipt:(id)arg1;
- (void)setTagID:(id)arg1;
- (id)tagID;

@end
