/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/BackBoardServices.framework/BackBoardServices
 */

@interface BKSFenceLogger : BSFileLogger {
    bool  _reportable;
}

@property (getter=_isReportable, nonatomic, readonly) bool _reportable;

+ (id)initializeLogging;

- (bool)_isReportable;
- (void)_reloadFromDefaultsDictionary:(id)arg1;
- (void)_setEnabled:(bool)arg1;
- (void)_setLevel:(int)arg1;
- (int)level;
- (unsigned long long)logDestinations;
- (id)logPath;
- (id)logPreferenceDomain;
- (id)logPreferenceName;
- (id)logPrefixForCategory:(id)arg1 destination:(unsigned long long)arg2;
- (id)name;
- (bool)shouldEnableOnInternalBuilds;

@end
