/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SearchFoundation.framework/SearchFoundation
 */

@interface SFFeedback : NSObject <NSCopying, NSSecureCoding> {
    unsigned long long  _timestamp;
}

@property unsigned long long timestamp;

// Image: /System/Library/PrivateFrameworks/SearchFoundation.framework/SearchFoundation

+ (bool)supportsSecureCoding;

- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (void)setTimestamp:(unsigned long long)arg1;
- (unsigned long long)timestamp;

// Image: /System/Library/PrivateFrameworks/CoreParsec.framework/CoreParsec

- (id)featureVectorsForClient:(id)arg1;

@end
