/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SearchFoundation.framework/SearchFoundation
 */

@interface SFKeyValueDataCardSection : SFCardSection {
    SFImage * _accessoryImage;
    NSArray * _data;
}

@property (nonatomic, retain) SFImage *accessoryImage;
@property (nonatomic, copy) NSArray *data;

// Image: /System/Library/PrivateFrameworks/SearchFoundation.framework/SearchFoundation

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)accessoryImage;
- (id)data;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)setAccessoryImage:(id)arg1;
- (void)setData:(id)arg1;

// Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI

- (id)searchUICardSection;

@end
