/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Messages.framework/Messages
 */

@interface MSConversation : NSObject <MSMessageContext> {
    NSString * _conversationIdentifier;
    <MSConversationDelegate> * _delegate;
    NSUUID * _identifier;
    NSUUID * _localParticipantIdentifier;
    NSArray * _remoteParticipantIdentifiers;
    MSMessage * _selectedMessage;
}

@property (nonatomic, readonly) NSString *conversationIdentifier;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <MSConversationDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSUUID *identifier;
@property (nonatomic, readonly) MSMessage *inputMessagePayload;
@property (nonatomic, readonly) NSUUID *localParticipantIdentifier;
@property (nonatomic, readonly) NSArray *recipientIdentifiers;
@property (nonatomic, retain) NSArray *remoteParticipantIdentifiers;
@property (nonatomic, retain) MSMessage *selectedMessage;
@property (nonatomic, readonly) NSUUID *senderIdentifier;
@property (readonly) Class superclass;

+ (id)activeConversation;

- (void).cxx_destruct;
- (id)_initWithState:(id)arg1;
- (void)_updateWithState:(id)arg1;
- (id)context;
- (id)conversationIdentifier;
- (id)delegate;
- (id)identifier;
- (id)inputMessagePayload;
- (void)insertAttachment:(id)arg1 withAlternateFilename:(id)arg2 completionHandler:(id /* block */)arg3;
- (void)insertImage:(id)arg1 completionHandler:(id /* block */)arg2;
- (void)insertMediaAtURL:(id)arg1 attributionURL:(id)arg2 attributionIcon:(id)arg3 completionHandler:(id /* block */)arg4;
- (void)insertMediaAtURL:(id)arg1 completionHandler:(id /* block */)arg2;
- (void)insertMessage:(id)arg1 localizedChangeDescription:(id)arg2 completionHandler:(id /* block */)arg3;
- (void)insertRichLink:(id)arg1 completionHandler:(id /* block */)arg2;
- (void)insertSticker:(id)arg1 completionHandler:(id /* block */)arg2;
- (void)insertStickerWithImage:(id)arg1 completionHandler:(id /* block */)arg2;
- (void)insertStickerWithMediaAtURL:(id)arg1 completionHandler:(id /* block */)arg2;
- (void)insertText:(id)arg1 completionHandler:(id /* block */)arg2;
- (id)localParticipantIdentifier;
- (id)recipientIdentifiers;
- (id)remoteParticipantIdentifiers;
- (id)selectedMessage;
- (id)senderIdentifier;
- (id)senderIdentifier;
- (void)setDelegate:(id)arg1;
- (void)setRemoteParticipantIdentifiers:(id)arg1;
- (void)setSelectedMessage:(id)arg1;
- (void)stageMessage:(id)arg1 localizedChangeDescription:(id)arg2 completionHandler:(id /* block */)arg3;
- (void)unstageAllItems;
- (void)updateMessagePayload:(id)arg1 completionHandler:(id /* block */)arg2;

@end
