/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AssistantServices.framework/AssistantServices
 */

@interface AFWatchdogTimer : NSObject {
    id /* block */  _handler;
    double  _interval;
    NSObject<OS_dispatch_queue> * _queue;
    NSObject<OS_dispatch_source> * _timerSource;
}

- (void).cxx_destruct;
- (void)_scheduleTimer;
- (void)cancel;
- (bool)cancelIfNotAlreadyCanceled;
- (id)initWithTimeoutInterval:(double)arg1 onQueue:(id)arg2 timeoutHandler:(id /* block */)arg3;
- (id)initWithTimeoutInterval:(double)arg1 timeoutHandler:(id /* block */)arg2;
- (void)reset;
- (void)start;

@end
