/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PassKitUI.framework/PassKitUI
 */

@interface PKPassTableViewCell : PKCardOnFileTableViewCell {
    PKPaymentPass * _paymentPass;
}

@property (nonatomic, retain) PKPaymentPass *paymentPass;

- (void).cxx_destruct;
- (void)dealloc;
- (id)paymentPass;
- (void)setPaymentPass:(id)arg1;

@end
