/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PassKitUI.framework/PassKitUI
 */

@interface PKPaymentSetupViewController : UIViewController <PKPaymentSetupPrivacyFooterViewDelegate> {
    ACAccountStore * _accountStore;
    bool  _allowsManualEntry;
    long long  _context;
    <PKPaymentSetupViewControllerDelegate> * _delegate;
    bool  _nextButtonPushed;
    PKPaymentProvisioningController * _provisioningController;
    bool  _skipFlowPicker;
}

@property (nonatomic) bool allowsManualEntry;
@property (nonatomic) long long context;
@property (nonatomic) <PKPaymentSetupViewControllerDelegate> *delegate;
@property (nonatomic, readonly, retain) PKPaymentProvisioningController *provisioningController;
@property (nonatomic) bool skipFlowPicker;
@property (nonatomic, readonly, retain) PKPaymentWebService *webService;

- (void).cxx_destruct;
- (id)_configuredCardListViewControllerWithCardList:(id)arg1;
- (id)_configuredCardOnFileEntryViewControllerForCredential:(id)arg1;
- (id)_configuredFlowPickerViewController;
- (id)_configuredManualCardEntryViewController;
- (id)_configuredNextActionViewControllerForAssociatedCredentials;
- (id)_contextSpecificStringForAggdKey:(id)arg1;
- (id)_deviceSpecificLocalizedStringKeyForKey:(id)arg1;
- (bool)_flowPickerRequired;
- (void)_next:(id)arg1;
- (void)_presentNextActionViewController:(id)arg1;
- (bool)allowsManualEntry;
- (id)configuredNextActionViewController;
- (long long)context;
- (void)dealloc;
- (id)delegate;
- (unsigned long long)edgesForExtendedLayout;
- (id)initWithProvisioningController:(id)arg1 context:(long long)arg2 delegate:(id)arg3;
- (void)loadView;
- (void)privacyFooterLinkTapped:(id)arg1;
- (id)provisioningController;
- (void)setAllowsManualEntry:(bool)arg1;
- (void)setContext:(long long)arg1;
- (void)setDelegate:(id)arg1;
- (void)setSkipFlowPicker:(bool)arg1;
- (bool)skipFlowPicker;
- (void)viewDidAppear:(bool)arg1;
- (void)viewDidDisappear:(bool)arg1;
- (void)viewDidLoad;
- (id)webService;

@end
