/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PassKitUI.framework/PassKitUI
 */

@interface PKPassPropertiesSummaryItem : NSObject {
    NSString * _detailText;
    NSString * _headerText;
    unsigned long long  _layout;
    NSString * _primaryText;
    NSString * _subTitleText;
}

@property (nonatomic, readonly, retain) NSString *detailText;
@property (nonatomic, readonly, retain) NSString *headerText;
@property (nonatomic, readonly) unsigned long long layout;
@property (nonatomic, readonly, retain) NSString *primaryText;
@property (nonatomic, readonly, retain) NSString *subTitleText;

- (void).cxx_destruct;
- (id)detailText;
- (id)headerText;
- (id)initWithPrimaryText:(id)arg1 detailText:(id)arg2 subTitleText:(id)arg3 headerText:(id)arg4 layout:(unsigned long long)arg5;
- (unsigned long long)layout;
- (id)primaryText;
- (id)subTitleText;

@end
