/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PassKitUI.framework/PassKitUI
 */

@interface PKPaymentSetupInfoView : UIView {
    UIActivityIndicatorView * _activityIndicatorView;
    UILabel * _bodyLabel;
    long long  _context;
    bool  _insetPrivacyFooter;
    UIImageView * _logo;
    PKPaymentSetupPrivacyFooterView * _privacyFooter;
    bool  _requiresClearBackgroundColor;
}

@property (nonatomic, retain) UIActivityIndicatorView *activityIndicatorView;
@property (nonatomic) long long context;
@property (nonatomic) bool insetPrivacyFooter;
@property (nonatomic, retain) UIImageView *logo;
@property (nonatomic, retain) PKPaymentSetupPrivacyFooterView *privacyFooter;
@property (nonatomic) bool requiresClearBackgroundColor;

- (void).cxx_destruct;
- (id)_bodyFont;
- (id)_titleFont;
- (id)activityIndicatorView;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })bodyInsetsForSize:(struct CGSize { double x1; double x2; })arg1;
- (id)bodyLabel;
- (long long)context;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 context:(long long)arg2;
- (bool)insetPrivacyFooter;
- (bool)isBuddyiPad;
- (void)layoutSubviews;
- (id)logo;
- (void)pk_applyAppearance:(id)arg1;
- (id)privacyFooter;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })privacyInsets;
- (bool)requiresClearBackgroundColor;
- (void)setActivityIndicatorView:(id)arg1;
- (void)setBackgroundColor:(id)arg1;
- (void)setContext:(long long)arg1;
- (void)setInsetPrivacyFooter:(bool)arg1;
- (void)setLogo:(id)arg1;
- (void)setPrivacyFooter:(id)arg1;
- (void)setRequiresClearBackgroundColor:(bool)arg1;
- (struct CGSize { double x1; double x2; })sizeThatFits:(struct CGSize { double x1; double x2; })arg1;

@end
