/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Intents.framework/Intents
 */

@interface _INPBSetSeatTemperatureInCarIntent : PBCodable <NSCopying> {
    bool  _enable;
    struct { 
        unsigned int relativeLevelSetting : 1; 
        unsigned int seat : 1; 
        unsigned int temperatureMode : 1; 
        unsigned int enable : 1; 
    }  _has;
    _INPBIntentMetadata * _intentMetadata;
    _INPBInteger * _level;
    int  _relativeLevelSetting;
    int  _seat;
    int  _temperatureMode;
    PBUnknownFields * _unknownFields;
}

@property (nonatomic) bool enable;
@property (nonatomic) bool hasEnable;
@property (nonatomic, readonly) bool hasIntentMetadata;
@property (nonatomic, readonly) bool hasLevel;
@property (nonatomic) bool hasRelativeLevelSetting;
@property (nonatomic) bool hasSeat;
@property (nonatomic) bool hasTemperatureMode;
@property (nonatomic, retain) _INPBIntentMetadata *intentMetadata;
@property (nonatomic, retain) _INPBInteger *level;
@property (nonatomic) int relativeLevelSetting;
@property (nonatomic) int seat;
@property (nonatomic) int temperatureMode;
@property (nonatomic, readonly) PBUnknownFields *unknownFields;

+ (id)options;

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (bool)enable;
- (bool)hasEnable;
- (bool)hasIntentMetadata;
- (bool)hasLevel;
- (bool)hasRelativeLevelSetting;
- (bool)hasSeat;
- (bool)hasTemperatureMode;
- (unsigned long long)hash;
- (id)intentMetadata;
- (bool)isEqual:(id)arg1;
- (id)level;
- (void)mergeFrom:(id)arg1;
- (bool)readFrom:(id)arg1;
- (int)relativeLevelSetting;
- (int)seat;
- (void)setEnable:(bool)arg1;
- (void)setHasEnable:(bool)arg1;
- (void)setHasRelativeLevelSetting:(bool)arg1;
- (void)setHasSeat:(bool)arg1;
- (void)setHasTemperatureMode:(bool)arg1;
- (void)setIntentMetadata:(id)arg1;
- (void)setLevel:(id)arg1;
- (void)setRelativeLevelSetting:(int)arg1;
- (void)setSeat:(int)arg1;
- (void)setTemperatureMode:(int)arg1;
- (int)temperatureMode;
- (id)unknownFields;
- (void)writeTo:(id)arg1;

@end
