/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Intents.framework/Intents
 */

@interface INGetRestaurantGuestIntentResponse : INIntentResponse {
    INRestaurantGuest * _guest;
}

@property (nonatomic, readonly) long long code;
@property (nonatomic, copy) INRestaurantGuest *guest;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (long long)code;
- (void)encodeWithCoder:(id)arg1;
- (id)guest;
- (id)initWithCoder:(id)arg1;
- (bool)isEqual:(id)arg1;
- (void)setGuest:(id)arg1;

@end
