/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Intents.framework/Intents
 */

@interface INPerson : NSObject <INCacheableContainer, NSCopying, NSSecureCoding> {
    NSString * _contactIdentifier;
    NSString * _displayName;
    NSString * _handle;
    INImage * _image;
    NSPersonNameComponents * _nameComponents;
}

@property (nonatomic, readonly, copy) NSString *contactIdentifier;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly, copy) NSString *displayName;
@property (nonatomic, readonly, copy) NSString *firstName;
@property (nonatomic, readonly, copy) NSString *fullName;
@property (nonatomic, readonly, copy) NSString *handle;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly, copy) INImage *image;
@property (nonatomic, readonly, copy) NSString *lastName;
@property (nonatomic, readonly, copy) NSPersonNameComponents *nameComponents;
@property (readonly) Class superclass;
@property (nonatomic, readonly, copy) NSString *userIdentifier;
@property (nonatomic, readonly, copy) NSString *userName;
@property (nonatomic, readonly, copy) NSString *userURIString;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)_displayName;
- (id)cacheableObjects;
- (id)contactIdentifier;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)displayName;
- (void)encodeWithCoder:(id)arg1;
- (id)firstName;
- (id)fullName;
- (id)handle;
- (unsigned long long)hash;
- (id)image;
- (id)initWithCoder:(id)arg1;
- (id)initWithHandle:(id)arg1 displayName:(id)arg2 contactIdentifier:(id)arg3;
- (id)initWithHandle:(id)arg1 nameComponents:(id)arg2 contactIdentifier:(id)arg3;
- (id)initWithHandle:(id)arg1 nameComponents:(id)arg2 displayName:(id)arg3 image:(id)arg4 contactIdentifier:(id)arg5;
- (id)initWithNameComponents:(id)arg1 displayName:(id)arg2 userName:(id)arg3 userIdentifier:(id)arg4 userURIString:(id)arg5 contactIdentifier:(id)arg6;
- (bool)isEqual:(id)arg1;
- (id)lastName;
- (id)nameComponents;
- (id)userIdentifier;
- (id)userName;
- (id)userURIString;

@end
