/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Intents.framework/Intents
 */

@interface INRestaurantReservationUserBooking : INRestaurantReservationBooking <NSCopying> {
    NSString * _advisementText;
    INRestaurantGuest * _guest;
    unsigned long long  _status;
}

@property (nonatomic, copy) NSString *advisementText;
@property (nonatomic, copy) INRestaurantGuest *guest;
@property (nonatomic) unsigned long long status;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)advisementText;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)guest;
- (id)initWithCoder:(id)arg1;
- (bool)isEqual:(id)arg1;
- (void)setAdvisementText:(id)arg1;
- (void)setGuest:(id)arg1;
- (void)setStatus:(unsigned long long)arg1;
- (unsigned long long)status;

@end
