/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Intents.framework/Intents
 */

@interface INSendPaymentIntent : INIntent <INSendPaymentIntent>

@property (nonatomic, readonly, copy) INCurrencyAmount *currencyAmount;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly, copy) NSString *note;
@property (nonatomic, readonly, copy) INPerson *payee;
@property (nonatomic, readonly, copy) INPaymentMethod *paymentMethod;
@property (readonly) Class superclass;

- (id)_metadata;
- (void)_redactForMissingPrivacyEntitlementOptions:(unsigned long long)arg1;
- (id)_typedBackingStore;
- (id)currencyAmount;
- (id)initWithPayee:(id)arg1 currencyAmount:(id)arg2 note:(id)arg3 paymentMethod:(id)arg4;
- (id)note;
- (id)payee;
- (id)paymentMethod;
- (void)setCurrencyAmount:(id)arg1;
- (void)setNote:(id)arg1;
- (void)setPayee:(id)arg1;
- (void)setPaymentMethod:(id)arg1;

@end
