/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Intents.framework/Intents
 */

@interface INStartVideoCallIntentResponse : INIntentResponse {
    _INPBStartVideoCallIntentResponse * _responseMessagePBRepresentation;
}

@property (nonatomic) long long audioRoute;
@property (nonatomic, readonly) long long code;
@property (nonatomic, copy) NSString *status;
@property (nonatomic, copy) NSArray *targetContacts;

+ (long long)_codeFromErrorCode:(int)arg1;
+ (int)_errorCodeFromCode:(long long)arg1;
+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)_responseMessagePBRepresentation;
- (long long)audioRoute;
- (long long)code;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (id)initWithBackingStore:(id)arg1;
- (id)initWithCode:(long long)arg1 userActivity:(id)arg2;
- (id)initWithCoder:(id)arg1;
- (void)setAudioRoute:(long long)arg1;
- (void)setStatus:(id)arg1;
- (void)setTargetContacts:(id)arg1;
- (id)status;
- (id)targetContacts;

@end
