/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CloudDocsDaemon.framework/CloudDocsDaemon
 */

@interface BRCSyncUpOperation : _BRCOperation <BRCOperationSubclass> {
    NSMutableDictionary * _conflictLosersToResolveByRecordID;
    float  _cost;
    NSMutableArray * _createdAppLibraryNames;
    NSMutableArray * _deletedRecordIDs;
    BRCLocalItem * _itemNeedingPCSChaining;
    NSMutableArray * _iworkUnsharedShareIDs;
    NSMutableArray * _packagesInFlight;
    NSMutableDictionary * _recordIDsToDeleteToEtags;
    NSMutableArray * _recordsNeedingNewSharingInfo;
    NSMutableArray * _recordsNeedingUpdatedSharingInfo;
    NSMutableArray * _recordsToSave;
    unsigned long long  _requestID;
    BRCServerZone * _serverZone;
    NSString * _stageID;
    id /* block */  _syncUpCompletionBlock;
}

@property (nonatomic, retain) NSMutableDictionary *conflictLosersToResolveByRecordID;
@property (nonatomic, readonly) float cost;
@property (nonatomic, readonly) NSMutableArray *createdAppLibraryNames;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic, retain) NSMutableArray *deletedRecordIDs;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) BRCLocalItem *itemNeedingPCSChaining;
@property (nonatomic, retain) NSMutableArray *iworkUnsharedShareIDs;
@property (nonatomic, retain) NSMutableArray *packagesInFlight;
@property (nonatomic, retain) NSMutableDictionary *recordIDsToDeleteToEtags;
@property (nonatomic, retain) NSMutableArray *recordsNeedingNewSharingInfo;
@property (nonatomic, retain) NSMutableArray *recordsNeedingUpdatedSharingInfo;
@property (nonatomic, retain) NSMutableArray *recordsToSave;
@property (nonatomic, retain) BRCServerZone *serverZone;
@property (nonatomic, retain) NSString *stageID;
@property (readonly) Class superclass;
@property (nonatomic, copy) id /* block */ syncUpCompletionBlock;

+ (id)syncUpOperationForZone:(id)arg1 maxCost:(float)arg2 retryAfter:(unsigned long long*)arg3;

- (void).cxx_destruct;
- (void)_performModifyRecordsOrPCSChainOperationWithCompletion:(id /* block */)arg1;
- (bool)_performPCSChainOperationIfNecessaryWithCompletion:(id /* block */)arg1;
- (void)_performUnsharingAndModifyRecordsWithCompletion:(id /* block */)arg1;
- (void)_performUpdateSharingInfoIfNecessary:(id /* block */)arg1;
- (void)_scheduleUnsharingAndModifyRecordsAndZoneCreationOperation;
- (id)conflictLosersToResolveByRecordID;
- (float)cost;
- (id)createActivity;
- (id)createdAppLibraryNames;
- (void)dealloc;
- (id)deletedRecordIDs;
- (void)finishWithResult:(id)arg1 error:(id)arg2;
- (id)initWithZone:(id)arg1;
- (id)itemNeedingPCSChaining;
- (id)iworkUnsharedShareIDs;
- (void)main;
- (id)packagesInFlight;
- (void)performAfterUnsharingIfNeeded:(id /* block */)arg1;
- (bool)prepareWithMaxCost:(float)arg1 retryAfter:(unsigned long long*)arg2;
- (id)recordIDsToDeleteToEtags;
- (id)recordsNeedingNewSharingInfo;
- (id)recordsNeedingUpdatedSharingInfo;
- (id)recordsToSave;
- (id)serverZone;
- (void)setConflictLosersToResolveByRecordID:(id)arg1;
- (void)setDeletedRecordIDs:(id)arg1;
- (void)setItemNeedingPCSChaining:(id)arg1;
- (void)setIworkUnsharedShareIDs:(id)arg1;
- (void)setPackagesInFlight:(id)arg1;
- (void)setRecordIDsToDeleteToEtags:(id)arg1;
- (void)setRecordsNeedingNewSharingInfo:(id)arg1;
- (void)setRecordsNeedingUpdatedSharingInfo:(id)arg1;
- (void)setRecordsToSave:(id)arg1;
- (void)setServerZone:(id)arg1;
- (void)setStageID:(id)arg1;
- (void)setSyncUpCompletionBlock:(id /* block */)arg1;
- (bool)shouldRetryForError:(id)arg1;
- (id)stageID;
- (id /* block */)syncUpCompletionBlock;

@end
