/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI
 */

@interface SearchUINowPlayingCardSection : SearchUICardSection <SearchUINowPlayingCardSection> {
    NSArray * _movieSections;
    NSString * _subtitle;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) bool hasBottomPadding;
@property (nonatomic, readonly) bool hasTopPadding;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) bool hideDivider;
@property (nonatomic, copy) NSArray *movieSections;
@property (nonatomic, readonly) NSArray *punchoutOptions;
@property (nonatomic, readonly) NSString *punchoutPickerDismissLabel;
@property (nonatomic, readonly) NSString *punchoutPickerLabel;
@property (nonatomic, copy) NSString *subtitle;
@property (readonly) Class superclass;
@property (nonatomic, readonly, copy) NSString *type;
@property (nonatomic, readonly, copy) NSURL *url;

- (void).cxx_destruct;
- (id)init;
- (id)movieSections;
- (void)setMovieSections:(id)arg1;
- (void)setSubtitle:(id)arg1;
- (id)subtitle;

@end
