/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI
 */

@interface SearchUIRowCardSection : SearchUICardSection <SearchUIRowCardSection> {
    UIImage * _image;
    double  _imageCornerRadius;
    bool  _imageIsRightAligned;
    NSString * _leftText;
    NSString * _rightText;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) bool hasBottomPadding;
@property (nonatomic, readonly) bool hasTopPadding;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) bool hideDivider;
@property (nonatomic, retain) UIImage *image;
@property (nonatomic) double imageCornerRadius;
@property (nonatomic) bool imageIsRightAligned;
@property (nonatomic, copy) NSString *leftText;
@property (nonatomic, readonly) NSArray *punchoutOptions;
@property (nonatomic, readonly) NSString *punchoutPickerDismissLabel;
@property (nonatomic, readonly) NSString *punchoutPickerLabel;
@property (nonatomic, copy) NSString *rightText;
@property (readonly) Class superclass;
@property (nonatomic, readonly, copy) NSString *type;
@property (nonatomic, readonly, copy) NSURL *url;

- (void).cxx_destruct;
- (id)image;
- (double)imageCornerRadius;
- (bool)imageIsRightAligned;
- (id)init;
- (id)leftText;
- (id)rightText;
- (void)setImage:(id)arg1;
- (void)setImageCornerRadius:(double)arg1;
- (void)setImageIsRightAligned:(bool)arg1;
- (void)setLeftText:(id)arg1;
- (void)setRightText:(id)arg1;

@end
