/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI
 */

@interface SearchUIDescriptionCardSection : SearchUICardSection <SearchUIDescriptionCardSection> {
    NSNumber * _descriptionExpand;
    NSString * _descriptionExpandText;
    unsigned long long  _descriptionMaxLines;
    NSNumber * _descriptionSize;
    NSString * _descriptionText;
    NSNumber * _descriptionWeight;
    UIImage * _image;
    NSString * _imageAlign;
    NSString * _title;
    NSNumber * _titleNoWrap;
    NSNumber * _titleWeight;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) NSNumber *descriptionExpand;
@property (nonatomic, copy) NSString *descriptionExpandText;
@property (nonatomic) unsigned long long descriptionMaxLines;
@property (nonatomic, retain) NSNumber *descriptionSize;
@property (nonatomic, copy) NSString *descriptionText;
@property (nonatomic, retain) NSNumber *descriptionWeight;
@property (nonatomic, readonly) bool hasBottomPadding;
@property (nonatomic, readonly) bool hasTopPadding;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) bool hideDivider;
@property (nonatomic, retain) UIImage *image;
@property (nonatomic, copy) NSString *imageAlign;
@property (nonatomic, readonly) NSArray *punchoutOptions;
@property (nonatomic, readonly) NSString *punchoutPickerDismissLabel;
@property (nonatomic, readonly) NSString *punchoutPickerLabel;
@property (readonly) Class superclass;
@property (nonatomic, copy) NSString *title;
@property (nonatomic, retain) NSNumber *titleNoWrap;
@property (nonatomic, retain) NSNumber *titleWeight;
@property (nonatomic, readonly, copy) NSString *type;
@property (nonatomic, readonly, copy) NSURL *url;

- (void).cxx_destruct;
- (id)descriptionExpand;
- (id)descriptionExpandText;
- (unsigned long long)descriptionMaxLines;
- (id)descriptionSize;
- (id)descriptionText;
- (id)descriptionWeight;
- (id)image;
- (id)imageAlign;
- (id)init;
- (void)setDescriptionExpand:(id)arg1;
- (void)setDescriptionExpandText:(id)arg1;
- (void)setDescriptionMaxLines:(unsigned long long)arg1;
- (void)setDescriptionSize:(id)arg1;
- (void)setDescriptionText:(id)arg1;
- (void)setDescriptionWeight:(id)arg1;
- (void)setImage:(id)arg1;
- (void)setImageAlign:(id)arg1;
- (void)setTitle:(id)arg1;
- (void)setTitleNoWrap:(id)arg1;
- (void)setTitleWeight:(id)arg1;
- (id)title;
- (id)titleNoWrap;
- (id)titleWeight;

@end
