/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI
 */

@interface SearchUIKeyValueDataCardSection : SearchUICardSection <SearchUIKeyValueDataCardSection> {
    UIImage * _accessoryImage;
    NSArray * _keys;
    NSArray * _values;
}

@property (nonatomic, retain) UIImage *accessoryImage;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) bool hasBottomPadding;
@property (nonatomic, readonly) bool hasTopPadding;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) bool hideDivider;
@property (nonatomic, retain) NSArray *keys;
@property (nonatomic, readonly) NSArray *punchoutOptions;
@property (nonatomic, readonly) NSString *punchoutPickerDismissLabel;
@property (nonatomic, readonly) NSString *punchoutPickerLabel;
@property (readonly) Class superclass;
@property (nonatomic, readonly, copy) NSString *type;
@property (nonatomic, readonly, copy) NSURL *url;
@property (nonatomic, retain) NSArray *values;

- (void).cxx_destruct;
- (id)accessoryImage;
- (id)init;
- (id)keys;
- (void)setAccessoryImage:(id)arg1;
- (void)setKeys:(id)arg1;
- (void)setValues:(id)arg1;
- (id)values;

@end
