/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI
 */

@interface SearchUIButtonSection : NSObject <SearchUIMovieCardSectionBuyButton> {
    NSString * _adamID;
    NSString * _offerIdentifier;
    NSString * _subtitle;
    NSString * _title;
    NSURL * _url;
}

@property (nonatomic, copy) NSString *adamID;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, copy) NSString *offerIdentifier;
@property (nonatomic, copy) NSString *subtitle;
@property (readonly) Class superclass;
@property (nonatomic, copy) NSString *title;
@property (nonatomic, copy) NSURL *url;

- (void).cxx_destruct;
- (id)adamID;
- (id)offerIdentifier;
- (void)setAdamID:(id)arg1;
- (void)setOfferIdentifier:(id)arg1;
- (void)setSubtitle:(id)arg1;
- (void)setTitle:(id)arg1;
- (void)setUrl:(id)arg1;
- (id)subtitle;
- (id)title;
- (id)url;

@end
