/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI
 */

@interface SearchUIMovieCardSectionDetail : NSObject <SearchUIMovieCardSectionDetail> {
    unsigned long long  _descriptionMaxLines;
    NSString * _descriptionText;
    NSString * _title;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic) unsigned long long descriptionMaxLines;
@property (nonatomic, copy) NSString *descriptionText;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (nonatomic, copy) NSString *title;

- (void).cxx_destruct;
- (unsigned long long)descriptionMaxLines;
- (id)descriptionText;
- (void)setDescriptionMaxLines:(unsigned long long)arg1;
- (void)setDescriptionText:(id)arg1;
- (void)setTitle:(id)arg1;
- (id)title;

@end
