/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI
 */

@interface SearchUIResultCompatibility : SFSearchResult

- (id)initWithResult:(id)arg1;

@end
