/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI
 */

@interface SearchUICardSection : NSObject <SearchUICardSection> {
    bool  _hasBottomPadding;
    bool  _hasTopPadding;
    bool  _hideDivider;
    NSArray * _punchoutOptions;
    NSString * _punchoutPickerDismissLabel;
    NSString * _punchoutPickerLabel;
    NSString * _type;
    NSURL * _url;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic) bool hasBottomPadding;
@property (nonatomic) bool hasTopPadding;
@property (readonly) unsigned long long hash;
@property (nonatomic) bool hideDivider;
@property (nonatomic, retain) NSArray *punchoutOptions;
@property (nonatomic, retain) NSString *punchoutPickerDismissLabel;
@property (nonatomic, retain) NSString *punchoutPickerLabel;
@property (readonly) Class superclass;
@property (nonatomic, copy) NSString *type;
@property (nonatomic, copy) NSURL *url;

- (void).cxx_destruct;
- (bool)hasBottomPadding;
- (bool)hasTopPadding;
- (bool)hideDivider;
- (id)initWithType:(id)arg1;
- (id)punchoutOptions;
- (id)punchoutPickerDismissLabel;
- (id)punchoutPickerLabel;
- (void)setHasBottomPadding:(bool)arg1;
- (void)setHasTopPadding:(bool)arg1;
- (void)setHideDivider:(bool)arg1;
- (void)setPunchoutOptions:(id)arg1;
- (void)setPunchoutPickerDismissLabel:(id)arg1;
- (void)setPunchoutPickerLabel:(id)arg1;
- (void)setType:(id)arg1;
- (void)setUrl:(id)arg1;
- (id)type;
- (id)url;

@end
