/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI
 */

@interface SearchUITwitterCardSection : SearchUICardSection <SearchUITwitterCardSection> {
    NSString * _date;
    NSString * _footnote;
    NSString * _subtitle;
    NSString * _title;
    <SearchUIRichTextItem> * _tweet;
    UIImage * _tweetImage;
    UIImage * _userThumbnail;
    UIImage * _verifiedImage;
}

@property (nonatomic, copy) NSString *date;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, copy) NSString *footnote;
@property (nonatomic, readonly) bool hasBottomPadding;
@property (nonatomic, readonly) bool hasTopPadding;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) bool hideDivider;
@property (nonatomic, readonly) NSArray *punchoutOptions;
@property (nonatomic, readonly) NSString *punchoutPickerDismissLabel;
@property (nonatomic, readonly) NSString *punchoutPickerLabel;
@property (nonatomic, copy) NSString *subtitle;
@property (readonly) Class superclass;
@property (nonatomic, copy) NSString *title;
@property (nonatomic, retain) <SearchUIRichTextItem> *tweet;
@property (nonatomic, retain) UIImage *tweetImage;
@property (nonatomic, readonly, copy) NSString *type;
@property (nonatomic, readonly, copy) NSURL *url;
@property (nonatomic, retain) UIImage *userThumbnail;
@property (nonatomic, retain) UIImage *verifiedImage;

- (void).cxx_destruct;
- (id)date;
- (id)footnote;
- (id)init;
- (void)setDate:(id)arg1;
- (void)setFootnote:(id)arg1;
- (void)setSubtitle:(id)arg1;
- (void)setTitle:(id)arg1;
- (void)setTweet:(id)arg1;
- (void)setTweetImage:(id)arg1;
- (void)setUserThumbnail:(id)arg1;
- (void)setVerifiedImage:(id)arg1;
- (id)subtitle;
- (id)title;
- (id)tweet;
- (id)tweetImage;
- (id)userThumbnail;
- (id)verifiedImage;

@end
