/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI
 */

@interface SearchUIContactActionsViewController : SearchUIAccessoryViewController <CNUIObjectViewControllerDelegate> {
    CNContactInlineActionsViewController * _inlineActionsViewController;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (retain) CNContactInlineActionsViewController *inlineActionsViewController;
@property (readonly) Class superclass;

+ (bool)supportsResult:(id)arg1;

- (void).cxx_destruct;
- (id)hostingViewControllerForController:(id)arg1;
- (id)inlineActionsViewController;
- (void)setInlineActionsViewController:(id)arg1;
- (id)setupViewWithStyle:(unsigned long long)arg1;
- (void)updateWithResult:(id)arg1;

@end
