/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI
 */

@interface SearchUILabeledImage : SearchUICardSection <SearchUILabeledImage> {
    NSString * _align;
    UIImage * _imageItem;
    NSString * _label;
}

@property (nonatomic, copy) NSString *align;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) UIImage *imageItem;
@property (nonatomic, copy) NSString *label;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)align;
- (id)imageItem;
- (id)label;
- (void)setAlign:(id)arg1;
- (void)setImageItem:(id)arg1;
- (void)setLabel:(id)arg1;

@end
