/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreCDPInternal.framework/CoreCDPInternal
 */

@interface CDPDRecoveryValidatedJoinFlowController : CDPDRecoveryFlowController <CDPDRemoteDeviceSecretValidatorDelegate>

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (unsigned long long)_escapeOfferForDevices:(id)arg1 remoteApproval:(bool)arg2 stringrayStatus:(bool)arg3;
- (void)cancelRemoteSecretValidatorApplicationToJoinCircle:(id)arg1;
- (id)recoveryValidatorWithDevices:(id)arg1 forMultipleICSC:(bool)arg2 withCompletionHandler:(id /* block */)arg3;
- (void)remoteSecretValidator:(id)arg1 applyToJoinCircleWithJoinHandler:(id /* block */)arg2;
- (bool)secretValidator:(id)arg1 shouldAcceptRecoveryError:(id*)arg2;
- (void)secretValidatorWillAttemptRecovery;

@end
