/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreCDPInternal.framework/CoreCDPInternal
 */

@interface CDPDProtectedCloudStorageProxyImpl : NSObject <CDPDProtectedCloudStorageProxy>

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (bool)_performPCSBlock:(id /* block */)arg1 error:(id*)arg2;
- (struct _PCSIdentitySetData { }*)pcsIdentityCreateWithInfo:(id)arg1 error:(id*)arg2;
- (bool)pcsIdentityMigrateCloseDoorWithInfo:(id)arg1 error:(id*)arg2;
- (bool)pcsIdentityMigrateDropStingrayWithInfo:(id)arg1 error:(id*)arg2;
- (bool)pcsIdentityMigrateRestoreHSMWithInfo:(id)arg1 error:(id*)arg2;
- (bool)pcsIdentityMigrateToStingrayWithInfo:(id)arg1 error:(id*)arg2;
- (bool)pcsIdentityMigrateToiCDPWithInfo:(id)arg1 error:(id*)arg2;
- (bool)pcsIdentitySetIsInICDPLocal:(struct _PCSIdentitySetData { }*)arg1 error:(id*)arg2;
- (bool)pcsIdentitySetIsInICDPNetwork:(struct _PCSIdentitySetData { }*)arg1 error:(id*)arg2;
- (struct _PCSIdentitySetData { }*)pcsIdentitySetupWithInfo:(id)arg1 error:(id*)arg2;
- (bool)pcsIdentityiCDPDroppedWithInfo:(id)arg1 error:(id*)arg2;

@end
