/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MapKit.framework/MapKit
 */

@interface MKArtworkImageViewCache : NSObject {
    NSCache * _artworkImageCache;
    MKTransitArtworkManager * _artworkManager;
}

@property (nonatomic, readonly) MKTransitArtworkManager *artworkManager;

+ (id)sharedInstance;

- (void).cxx_destruct;
- (id)_lookupArtworkInCacheWithKey:(id)arg1;
- (void)_setArtworkImageInCache:(id)arg1 forKey:(id)arg2;
- (id)artworkManager;
- (id)imageForArtwork:(id)arg1 view:(id)arg2;
- (id)initWithArtworkManager:(id)arg1;
- (void)purge;

@end
