/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MapKit.framework/MapKit
 */

@interface MKOfficialAppViewController : MKPlaceSectionViewController <_MKInfoCardChildViewControllerAnalyticsDelegate> {
    <MKOfficialAppViewControllerDelegate> * _officialAppDelegate;
    MKPlaceSectionHeaderView * _officialAppHeaderView;
    MKOfficialAppView * _officialAppView;
    NSString * _url;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic) <MKOfficialAppViewControllerDelegate> *officialAppDelegate;
@property (nonatomic, retain) MKPlaceSectionHeaderView *officialAppHeaderView;
@property (nonatomic, retain) MKOfficialAppView *officialAppView;
@property (readonly) Class superclass;
@property (nonatomic, copy) NSString *url;

- (void).cxx_destruct;
- (void)_beginFindingOfficialApp;
- (void)dealloc;
- (id)infoCardChildPossibleActions;
- (id)initWithURLString:(id)arg1;
- (id)officialAppDelegate;
- (id)officialAppHeaderView;
- (id)officialAppView;
- (void)setOfficialAppDelegate:(id)arg1;
- (void)setOfficialAppHeaderView:(id)arg1;
- (void)setOfficialAppView:(id)arg1;
- (void)setUrl:(id)arg1;
- (void)updateOfficialViewButtonText;
- (id)url;
- (void)viewDidLoad;

@end
