/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MapKit.framework/MapKit
 */

@interface MKPlaceHoursViewController : MKPlaceSectionViewController <MKStackingViewControllerFixedHeightAware, _MKInfoCardChildViewControllerAnalyticsDelegate, _MKStackViewDelegate> {
    MKPlaceSectionHeaderView * _headerView;
    <MKPlaceHoursViewControllerDelegate> * _hoursDelegate;
    bool  _isExpanded;
    MKMapItem * _mapItem;
    bool  _resizableViewsDisabled;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic) <MKPlaceHoursViewControllerDelegate> *hoursDelegate;
@property (nonatomic, retain) MKMapItem *mapItem;
@property (nonatomic) bool resizableViewsDisabled;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_contentSizeDidChange;
- (void)_setExpanded:(bool)arg1;
- (void)_toggleShowAllHours;
- (void)_updateHoursAnimated:(bool)arg1;
- (void)dealloc;
- (double)extraHeightToReserveInLayout;
- (id)hoursDelegate;
- (id)infoCardChildPossibleActions;
- (id)mapItem;
- (bool)resizableViewsDisabled;
- (void)setHoursDelegate:(id)arg1;
- (void)setMapItem:(id)arg1;
- (void)setResizableViewsDisabled:(bool)arg1;
- (double)stackView:(id)arg1 distanceBetweenUpperView:(id)arg2 andLowerView:(id)arg3;
- (void)viewDidLoad;

@end
