/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DiagnosticsKit.framework/DiagnosticsKit
 */

@interface DKHostContext : NSExtensionContext <DKHostRemoteContext> {
    <DKAssertionDelegate> * _assertionDelegate;
    <DKAssetResponder> * _assetResponder;
}

@property (nonatomic, retain) <DKAssertionDelegate> *assertionDelegate;
@property (nonatomic, retain) <DKAssetResponder> *assetResponder;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

+ (id)_extensionAuxiliaryHostProtocol;
+ (id)_extensionAuxiliaryVendorProtocol;

- (void).cxx_destruct;
- (id)assertionDelegate;
- (id)assetResponder;
- (void)cancelWithCompletion:(id /* block */)arg1;
- (void)enableVolumeHUD:(bool)arg1;
- (void)getAsset:(id)arg1 completion:(id /* block */)arg2;
- (void)setAssertionDelegate:(id)arg1;
- (void)setAssetResponder:(id)arg1;
- (void)setScreenToBrightness:(float)arg1 animate:(bool)arg2;
- (void)startWithCompletion:(id /* block */)arg1;

@end
