/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppStoreDaemon.framework/AppStoreDaemon
 */

@interface ASDRestoreRequestOptions : ASDRequestOptions {
    ASDJobManifest * _manifest;
    NSString * _originatingClientID;
}

@property (nonatomic, copy) ASDJobManifest *manifest;
@property (nonatomic, copy) NSString *originatingClientID;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithManifest:(id)arg1;
- (id)manifest;
- (id)originatingClientID;
- (void)setManifest:(id)arg1;
- (void)setOriginatingClientID:(id)arg1;

@end
