/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ContactsUI.framework/ContactsUI
 */

@interface CNActionView : UIView {
    NSObject<CNActionViewProtocol> * _actionDelegate;
    NSArray * _activatedContstrants;
    bool  _disabled;
    UIImage * _image;
    UIImageView * _imageView;
    UILongPressGestureRecognizer * _longPressGestureRecognizer;
    UIView * _platterView;
    long long  _style;
    UITapGestureRecognizer * _tapGestureRecognizer;
    NSString * _title;
    UILabel * _titleLabel;
    NSString * _type;
}

@property (nonatomic) NSObject<CNActionViewProtocol> *actionDelegate;
@property (nonatomic, retain) NSArray *activatedContstrants;
@property (nonatomic) bool disabled;
@property (nonatomic, retain) UIImage *image;
@property (nonatomic, retain) UIImageView *imageView;
@property (nonatomic, retain) UILongPressGestureRecognizer *longPressGestureRecognizer;
@property (nonatomic, retain) UIView *platterView;
@property (nonatomic) long long style;
@property (nonatomic, retain) UITapGestureRecognizer *tapGestureRecognizer;
@property (nonatomic, retain) NSString *title;
@property (nonatomic, retain) UILabel *titleLabel;
@property (nonatomic, retain) NSString *type;

+ (bool)requiresConstraintBasedLayout;

- (void).cxx_destruct;
- (id)actionDelegate;
- (id)activatedContstrants;
- (void)didMoveToWindow;
- (bool)disabled;
- (void)handleLongPressGesture:(id)arg1;
- (void)handleTapGesture:(id)arg1;
- (id)image;
- (id)imageView;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (id)longPressGestureRecognizer;
- (id)platterView;
- (void)setActionDelegate:(id)arg1;
- (void)setActivatedContstrants:(id)arg1;
- (void)setDisabled:(bool)arg1;
- (void)setImage:(id)arg1;
- (void)setImageView:(id)arg1;
- (void)setLongPressGestureRecognizer:(id)arg1;
- (void)setPlatterView:(id)arg1;
- (void)setStyle:(long long)arg1;
- (void)setTapGestureRecognizer:(id)arg1;
- (void)setTitle:(id)arg1;
- (void)setTitleLabel:(id)arg1;
- (void)setType:(id)arg1;
- (long long)style;
- (id)tapGestureRecognizer;
- (id)title;
- (id)titleLabel;
- (id)type;
- (void)updateConstraints;
- (void)updateImageViewState;
- (void)updateLabelState;
- (void)updatePlatterViewState;

@end
