/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ContactsUI.framework/ContactsUI
 */

@interface CNAvatarImageRenderer : NSObject {
    _CNUIPRLikenessResolver * _resolver;
}

@property (nonatomic, readonly) _CNUIPRLikenessResolver *resolver;

+ (id)descriptorForRequiredKeys;

- (void).cxx_destruct;
- (id)init;
- (id)initWithSettings:(id)arg1;
- (id)renderAvatarsForContacts:(id)arg1 handler:(id /* block */)arg2;
- (id)resolver;

@end
