/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ContactsUI.framework/ContactsUI
 */

@interface CNAvatarImageRendererSettings : NSObject {
    CNContactStore * _contactStore;
    CNUIMeMonitor * _meMonitor;
    PRPersonaStore * _personaStore;
    <CNScheduler> * _scheduler;
}

@property (nonatomic, retain) CNContactStore *contactStore;
@property (nonatomic, retain) CNUIMeMonitor *meMonitor;
@property (nonatomic, retain) PRPersonaStore *personaStore;
@property (nonatomic, retain) <CNScheduler> *scheduler;

+ (id)defaultSettings;
+ (id)settingsWithContactStore:(id)arg1;
+ (id)settingsWithContactStore:(id)arg1 personaStore:(id)arg2;

- (void).cxx_destruct;
- (id)contactStore;
- (id)initWithContactStore:(id)arg1 personaStore:(id)arg2;
- (id)meMonitor;
- (id)personaStore;
- (id)scheduler;
- (void)setContactStore:(id)arg1;
- (void)setMeMonitor:(id)arg1;
- (void)setPersonaStore:(id)arg1;
- (void)setScheduler:(id)arg1;

@end
