/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ContactsUI.framework/ContactsUI
 */

@interface CNPropertyInstantMessageCell : CNPropertySimpleTransportCell {
    CNUIUserActionItem * _action;
}

@property (nonatomic, retain) CNUIUserActionItem *action;

- (void).cxx_destruct;
- (id)action;
- (id)defaultContext;
- (void)performDefaultAction;
- (void)setAction:(id)arg1;
- (bool)shouldPerformDefaultAction;
- (void)transportButton1Clicked:(id)arg1;
- (void)updateTransportButtons;

@end
