/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXAssetCollectionActionPerformer : PXActionPerformer {
    <PXDisplayAssetCollection> * _assetCollection;
    PHFetchResult * _people;
}

@property (nonatomic, readonly) <PXDisplayAssetCollection> *assetCollection;
@property (nonatomic, readonly) PHFetchResult *people;

- (void).cxx_destruct;
- (id)assetCollection;
- (id)initWithActionType:(id)arg1;
- (id)initWithActionType:(id)arg1 assetCollection:(id)arg2 people:(id)arg3;
- (id)people;

@end
