/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXPeopleOnboardingViewController : UIViewController <PXPeopleWelcomeDelegate> {
    unsigned long long  _onboardStatus;
    bool  _originalNavBarHidesShadow;
    bool  _originalNavBarTranslucent;
    PXPeopleProgressManager * _progressManager;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic) unsigned long long onboardStatus;
@property bool originalNavBarHidesShadow;
@property bool originalNavBarTranslucent;
@property (nonatomic, retain) PXPeopleProgressManager *progressManager;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)_controllerForStatus:(unsigned long long)arg1;
- (void)_faceImagesForWelcomeScreenWithCompletionBlock:(id /* block */)arg1;
- (void)_progressChanged:(id)arg1;
- (void)_transitionFromViewController:(id)arg1 toViewController:(id)arg2;
- (void)_updateStatusViewForStatus:(unsigned long long)arg1 progress:(double)arg2;
- (void)_updateWithStatus:(unsigned long long)arg1 progress:(double)arg2;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (unsigned long long)onboardStatus;
- (bool)originalNavBarHidesShadow;
- (bool)originalNavBarTranslucent;
- (id)progressManager;
- (void)pushToPeopleHome:(id)arg1;
- (void)setOnboardStatus:(unsigned long long)arg1;
- (void)setOriginalNavBarHidesShadow:(bool)arg1;
- (void)setOriginalNavBarTranslucent:(bool)arg1;
- (void)setProgressManager:(id)arg1;
- (void)viewDidAppear:(bool)arg1;
- (void)viewDidLoad;
- (void)viewWillDisappear:(bool)arg1;
- (void)viewWillTransitionToSize:(struct CGSize { double x1; double x2; })arg1 withTransitionCoordinator:(id)arg2;
- (void)welcomeViewControllerButtonTapped:(id)arg1;

@end
