/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXPeopleStatusView : UIView {
    NSArray * _constraints;
    UIView * _containerView;
    NSLayoutConstraint * _containerY;
    struct UIEdgeInsets { 
        double top; 
        double left; 
        double bottom; 
        double right; 
    }  _contentInsets;
    UIButton * _continueButton;
    UILabel * _descriptionLabel;
    NSLayoutConstraint * _descriptionToTitleCnst;
    NSLayoutConstraint * _progressLeading;
    NSLayoutConstraint * _progressTopCnst;
    NSLayoutConstraint * _progressTrailing;
    UIProgressView * _progressView;
    UILabel * _titleLabel;
    NSLayoutConstraint * _titleToDescriptionCnst;
    unsigned long long  _viewState;
}

@property (nonatomic, retain) NSArray *constraints;
@property (nonatomic, retain) UIView *containerView;
@property (nonatomic, retain) NSLayoutConstraint *containerY;
@property (nonatomic) struct UIEdgeInsets { double x1; double x2; double x3; double x4; } contentInsets;
@property (nonatomic, retain) UIButton *continueButton;
@property (nonatomic, readonly) UILabel *descriptionLabel;
@property (nonatomic, retain) NSLayoutConstraint *descriptionToTitleCnst;
@property (nonatomic, retain) NSLayoutConstraint *progressLeading;
@property (nonatomic, retain) NSLayoutConstraint *progressTopCnst;
@property (nonatomic, retain) NSLayoutConstraint *progressTrailing;
@property (nonatomic, readonly) UIProgressView *progressView;
@property (nonatomic, readonly) UILabel *titleLabel;
@property (nonatomic, retain) NSLayoutConstraint *titleToDescriptionCnst;
@property (nonatomic) unsigned long long viewState;

- (void).cxx_destruct;
- (void)_createViews;
- (void)commonInit;
- (id)constraints;
- (id)containerView;
- (id)containerY;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })contentInsets;
- (id)continueButton;
- (id)descriptionLabel;
- (id)descriptionToTitleCnst;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (id)progressLeading;
- (id)progressTopCnst;
- (id)progressTrailing;
- (id)progressView;
- (void)setConstraints:(id)arg1;
- (void)setContainerView:(id)arg1;
- (void)setContainerY:(id)arg1;
- (void)setContentInsets:(struct UIEdgeInsets { double x1; double x2; double x3; double x4; })arg1;
- (void)setContinueButton:(id)arg1;
- (void)setDescriptionToTitleCnst:(id)arg1;
- (void)setProgressLeading:(id)arg1;
- (void)setProgressTopCnst:(id)arg1;
- (void)setProgressTrailing:(id)arg1;
- (void)setTitleToDescriptionCnst:(id)arg1;
- (void)setViewState:(unsigned long long)arg1;
- (id)titleLabel;
- (id)titleToDescriptionCnst;
- (void)updateConstraints;
- (unsigned long long)viewState;

@end
