/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXPeopleDetailsContext : PXPhotosDetailsContext {
    PHManualFetchResult * _peopleFetchResult;
}

@property (nonatomic, readonly) PHManualFetchResult *peopleFetchResult;

- (void).cxx_destruct;
- (id)initWithPhotosDataSource:(id)arg1 parentContext:(id)arg2 keyAssetsFetchResult:(id)arg3;
- (id)initWithPhotosDataSource:(id)arg1 parentContext:(id)arg2 people:(id)arg3;
- (id)peopleFetchResult;

@end
