/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXPeopleWelcomeView : UIView {
    struct UIEdgeInsets { 
        double top; 
        double left; 
        double bottom; 
        double right; 
    }  _contentInsets;
    UILabel * _descriptionLabel;
    UIView * _iconView;
    NSArray * _landscapeConstraints;
    NSArray * _portraitConstraints;
    UIButton * _startButton;
    UILabel * _titleLabel;
    long long  _verticalSizeClass;
}

@property (nonatomic) struct UIEdgeInsets { double x1; double x2; double x3; double x4; } contentInsets;
@property (nonatomic, readonly) UILabel *descriptionLabel;
@property (nonatomic, retain) UIView *iconView;
@property (nonatomic, retain) NSArray *landscapeConstraints;
@property (nonatomic, retain) NSArray *portraitConstraints;
@property (nonatomic, readonly) UIButton *startButton;
@property (nonatomic, readonly) UILabel *titleLabel;
@property (nonatomic) long long verticalSizeClass;

- (void).cxx_destruct;
- (void)commonInit;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })contentInsets;
- (id)descriptionLabel;
- (id)iconView;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (id)landscapeConstraints;
- (id)portraitConstraints;
- (void)setContentInsets:(struct UIEdgeInsets { double x1; double x2; double x3; double x4; })arg1;
- (void)setIconView:(id)arg1;
- (void)setLandscapeConstraints:(id)arg1;
- (void)setPortraitConstraints:(id)arg1;
- (void)setVerticalSizeClass:(long long)arg1;
- (id)startButton;
- (id)titleLabel;
- (void)updateConstraints;
- (long long)verticalSizeClass;

@end
