/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MIME.framework/MIME
 */

@interface _MFLazyFuture : MFFuture {
    id /* block */  _block;
    MFPromise * _promise;
    NSConditionLock * _stateLock;
}

- (void)addFailureBlock:(id /* block */)arg1;
- (void)addFailureBlock:(id /* block */)arg1 scheduler:(id)arg2;
- (void)addSuccessBlock:(id /* block */)arg1;
- (void)addSuccessBlock:(id /* block */)arg1 scheduler:(id)arg2;
- (bool)cancel;
- (void)dealloc;
- (id)initWithBlock:(id /* block */)arg1;
- (bool)isCancelled;
- (bool)isFinished;
- (id)resultBeforeDate:(id)arg1 error:(id*)arg2;
- (bool)run;

@end
