/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/VideoSubscriberAccount.framework/VideoSubscriberAccount
 */

@interface VSABundlePrivacyInfo : NSObject {
    struct __CFBundle { } * _bundle;
    VSAPrivacyFacade * _privacyFacade;
}

@property (getter=isAccessGranted, nonatomic) bool accessGranted;
@property (nonatomic, readonly) struct __CFBundle { }*bundle;
@property (nonatomic, readonly) VSAPrivacyFacade *privacyFacade;

- (void).cxx_destruct;
- (struct __CFBundle { }*)bundle;
- (void)dealloc;
- (id)initWithBundle:(struct __CFBundle { }*)arg1 privacyFacade:(id)arg2;
- (bool)isAccessGranted;
- (id)privacyFacade;
- (void)setAccessGranted:(bool)arg1;

@end
