/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/VideoSubscriberAccount.framework/VideoSubscriberAccount
 */

@interface VSACredentialSaveOperation : VSAAsyncOperation {
    VSAAccountStore * _accountStore;
    NSError * _error;
    VSAAccount * _savedAccount;
    VSAAccount * _unsavedAccount;
}

@property (nonatomic, retain) VSAAccountStore *accountStore;
@property (nonatomic, retain) NSError *error;
@property (nonatomic, retain) VSAAccount *savedAccount;
@property (nonatomic, retain) VSAAccount *unsavedAccount;

- (void).cxx_destruct;
- (void)_didSaveAccount:(id)arg1 withResult:(bool)arg2 error:(id)arg3;
- (id)accountStore;
- (id)error;
- (void)executionDidBegin;
- (id)init;
- (id)initWithUnsavedAccount:(id)arg1;
- (id)savedAccount;
- (void)setAccountStore:(id)arg1;
- (void)setError:(id)arg1;
- (void)setSavedAccount:(id)arg1;
- (void)setUnsavedAccount:(id)arg1;
- (id)unsavedAccount;

@end
