/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/VideoSubscriberAccount.framework/VideoSubscriberAccount
 */

@interface VSAITMLCredentialEntryField : VSACredentialEntryField {
    IKViewElement * _associatedViewElement;
}

@property (nonatomic, retain) IKViewElement *associatedViewElement;

- (void).cxx_destruct;
- (id)associatedViewElement;
- (void)setAssociatedViewElement:(id)arg1;

@end
