/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/VideoSubscriberAccount.framework/VideoSubscriberAccount
 */

@interface VSAIdentityProviderFetchAllOperation : VSAStoreRequestOperation {
    NSArray * _featuredIdentityProviders;
    NSArray * _supportedAccountProviderIDs;
}

@property (nonatomic, copy) NSArray *featuredIdentityProviders;
@property (nonatomic, copy) NSArray *supportedAccountProviderIDs;

- (void).cxx_destruct;
- (id)URLBagKey;
- (id)featuredIdentityProviders;
- (void)handleResponseObject:(id)arg1;
- (id)init;
- (void)setFeaturedIdentityProviders:(id)arg1;
- (void)setSupportedAccountProviderIDs:(id)arg1;
- (id)supportedAccountProviderIDs;

@end
