/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/VideoSubscriberAccount.framework/VideoSubscriberAccount
 */

@interface VSAIdentityProviderFetchOperation : VSAAsyncOperation {
    NSError * _error;
    VSAIdentityProvider * _identityProvider;
    NSString * _identityProviderID;
    NSOperationQueue * _privateQueue;
}

@property (nonatomic, copy) NSError *error;
@property (nonatomic, copy) VSAIdentityProvider *identityProvider;
@property (nonatomic, copy) NSString *identityProviderID;
@property (nonatomic, retain) NSOperationQueue *privateQueue;

- (void).cxx_destruct;
- (void)cancel;
- (id)error;
- (void)executionDidBegin;
- (id)identityProvider;
- (id)identityProviderID;
- (id)init;
- (id)initWithIdentityProviderID:(id)arg1;
- (id)privateQueue;
- (void)setError:(id)arg1;
- (void)setIdentityProvider:(id)arg1;
- (void)setIdentityProviderID:(id)arg1;
- (void)setPrivateQueue:(id)arg1;

@end
