/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/VideoSubscriberAccount.framework/VideoSubscriberAccount
 */

@interface VSAPrivacyFacade : NSObject {
    unsigned long long  _localAccessStatus;
    NSOperationQueue * _privateQueue;
    NSString * _service;
}

@property (getter=isAccessRestricted, nonatomic, readonly) bool accessRestricted;
@property (nonatomic, readonly, copy) NSArray *knownAppBundles;
@property (nonatomic) unsigned long long localAccessStatus;
@property (nonatomic, retain) NSOperationQueue *privateQueue;
@property (nonatomic, copy) NSString *service;

+ (id)sharedPrivacyFacade;

- (void).cxx_destruct;
- (id)init;
- (id)initWithService:(id)arg1;
- (bool)isAccessGrantedForAuditToken:(struct { unsigned int x1[8]; })arg1;
- (bool)isAccessGrantedForBundle:(struct __CFBundle { }*)arg1;
- (bool)isAccessRestricted;
- (id)knownAppBundles;
- (unsigned long long)localAccessStatus;
- (id)privateQueue;
- (void)requestAccessForAuditToken:(struct { unsigned int x1[8]; })arg1 processIdentifier:(int)arg2 identityProviderDisplayName:(id)arg3 completionHandler:(id /* block */)arg4;
- (bool)reset;
- (id)service;
- (bool)setAccessGranted:(bool)arg1 forAuditToken:(struct { unsigned int x1[8]; })arg2;
- (bool)setAccessGranted:(bool)arg1 forBundle:(struct __CFBundle { }*)arg2;
- (void)setLocalAccessStatus:(unsigned long long)arg1;
- (void)setPrivateQueue:(id)arg1;
- (void)setService:(id)arg1;

@end
