/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/VideoSubscriberAccount.framework/VideoSubscriberAccount
 */

@interface VSAReverseValueTransformer : NSValueTransformer {
    NSValueTransformer * _valueTransformer;
}

@property (nonatomic, retain) NSValueTransformer *valueTransformer;

- (void).cxx_destruct;
- (id)init;
- (id)initWithValueTransformer:(id)arg1;
- (id)reverseTransformedValue:(id)arg1;
- (void)setValueTransformer:(id)arg1;
- (id)transformedValue:(id)arg1;
- (id)valueTransformer;

@end
