/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/VideoSubscriberAccount.framework/VideoSubscriberAccount
 */

@interface VSAUserNotificationOperation : NSOperation {
    NSString * _alternateButtonTitle;
    NSString * _defaultButtonTitle;
    NSString * _message;
    struct __CFUserNotification { } * _notification;
    unsigned long long  _response;
    NSString * _title;
}

@property (nonatomic, copy) NSString *alternateButtonTitle;
@property (nonatomic, copy) NSString *defaultButtonTitle;
@property (nonatomic, copy) NSString *message;
@property (nonatomic) unsigned long long response;
@property (nonatomic, copy) NSString *title;

- (void).cxx_destruct;
- (id)alternateButtonTitle;
- (void)cancel;
- (id)defaultButtonTitle;
- (void)main;
- (id)message;
- (unsigned long long)response;
- (void)setAlternateButtonTitle:(id)arg1;
- (void)setDefaultButtonTitle:(id)arg1;
- (void)setMessage:(id)arg1;
- (void)setResponse:(unsigned long long)arg1;
- (void)setTitle:(id)arg1;
- (id)title;

@end
