/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthUI.framework/HealthUI
 */

@interface HKDocumentPickerTableViewCell : UITableViewCell {
    HKAdjustableTapTargetButton * _checkboxButton;
    NSMutableArray * _constraints;
    <HKDocumentPickerTableViewCellDelegate> * _delegate;
    HKCDADocumentSample * _sample;
    UILabel * _secondaryLabel;
    bool  _showsCheckbox;
    UILabel * _titleLabel;
}

@property (getter=isChecked, nonatomic) bool checked;
@property (nonatomic) <HKDocumentPickerTableViewCellDelegate> *delegate;
@property (nonatomic, retain) HKCDADocumentSample *sample;
@property (nonatomic) bool showsCheckbox;

+ (bool)requiresConstraintBasedLayout;

- (void).cxx_destruct;
- (id)_checkboxConstraints;
- (void)_selectedCheckbox:(id)arg1;
- (id)delegate;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (bool)isChecked;
- (void)layoutSubviews;
- (id)sample;
- (void)setChecked:(bool)arg1;
- (void)setDelegate:(id)arg1;
- (void)setSample:(id)arg1;
- (void)setShowsCheckbox:(bool)arg1;
- (bool)showsCheckbox;
- (void)updateConstraints;

@end
