/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UserManagement.framework/UserManagement
 */

@interface UMException : NSObject

+ (void)raiseExceptionIfOperationNotPermittedError:(id)arg1;
+ (void)raiseExceptionOnMainThread:(id)arg1;

@end
