/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CryptoTokenKit.framework/CryptoTokenKit
 */

@interface TKSmartCardWithError : TKSmartCard {
    NSError * _error;
    TKSmartCard * _parentCard;
}

- (void).cxx_destruct;
- (void)beginSessionWithReply:(id /* block */)arg1;
- (id)initWithCard:(id)arg1 error:(id)arg2;
- (void)transmitRequest:(id)arg1 reply:(id /* block */)arg2;

@end
