/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Parsec.framework/Parsec
 */

@interface PRSRankingManager : NSObject {
    NSMutableDictionary * _combinedBottomScoreOrder;
    NSMutableDictionary * _combinedTopScoreOrder;
    NSDictionary * _groupedResults;
    NSArray * _preferredTopHitGroups;
    NSString * _shortcutBundleIdentifier;
    NSDictionary * _shortcutsDict;
}

@property (retain) NSMutableDictionary *combinedBottomScoreOrder;
@property (retain) NSMutableDictionary *combinedTopScoreOrder;
@property (nonatomic, retain) NSDictionary *groupedResults;
@property (nonatomic, retain) NSArray *preferredTopHitGroups;
@property (nonatomic, retain) NSDictionary *shortcutsDict;

+ (void)addToGlanceCategories:(id)arg1;
+ (void)fetchDuetValues;
+ (void)getAppRanking;
+ (id)getCoreDuetValues;
+ (id)getDuetExperCenterAppList;
+ (id)quickGlanceBundleIds;

- (void).cxx_destruct;
- (void)adjustScoresUsingCategoryEngagement:(id)arg1 forTopScores:(id)arg2 forBottomScores:(id)arg3 query:(id)arg4 logInfo:(id)arg5;
- (id)chooseTopHitsWithMaxCount:(unsigned long long)arg1 disabledGroups:(id)arg2 topHit:(id)arg3 queryString:(id)arg4 cepData:(id)arg5 cumulativeTopHitSet:(id)arg6;
- (id)combinedBottomScoreOrder;
- (id)combinedTopScoreOrder;
- (void)getRankedCategoriesForQuery:(id)arg1 meanScores:(id)arg2 maxScores:(id)arg3 standardDeviation:(id)arg4 serverLongTermCategoryRankOrder:(id)arg5 sectionHeaderToBundleIdMapping:(id)arg6 parsecResultOrdering:(id)arg7 rankingKnobs:(id)arg8 placements:(id)arg9 allowLocal:(bool)arg10 topCategories:(id*)arg11 bottomCategories:(id*)arg12 blacklistedCategories:(id*)arg13 scoresForFeedback:(id*)arg14 scoreToSendInFeedback:(long long)arg15 sessionIdentifier:(unsigned long long)arg16 categoryEngagements:(id)arg17 logString:(id)arg18 cepsUsed:(id)arg19 minimumCEPSource:(id)arg20;
- (id)getTopHitsBasedOnCategoryOrder:(id)arg1 groupedResults:(id)arg2 CEPTopHitThreshold:(double)arg3 CEPProbabilityFactor:(double)arg4 topHitCountLimit:(long long)arg5;
- (id)groupedResults;
- (id)initWithGroupedResult:(id)arg1 preferredTopHitGroups:(id)arg2 shortcuts:(id)arg3;
- (id)postDeDuplicationTopHitResultArray:(id)arg1;
- (id)preferredTopHitGroups;
- (bool)rankIsMeaningfulForTopHit:(unsigned long long)arg1;
- (void)setCombinedBottomScoreOrder:(id)arg1;
- (void)setCombinedTopScoreOrder:(id)arg1;
- (void)setGroupedResults:(id)arg1;
- (void)setPreferredTopHitGroups:(id)arg1;
- (void)setShortcutResultSectionBundleIdentifier:(id)arg1;
- (void)setShortcutsDict:(id)arg1;
- (id)shortcutsDict;

@end
