/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreHAP.framework/CoreHAP
 */

@interface HAPPairingIdentity : NSObject {
    NSString * _identifier;
    unsigned long long  _permissions;
    HAPPairingKey * _privateKey;
    HAPPairingKey * _publicKey;
}

@property (nonatomic, readonly, copy) NSString *identifier;
@property (nonatomic, readonly) unsigned long long permissions;
@property (nonatomic, readonly) HAPPairingKey *privateKey;
@property (nonatomic, readonly) HAPPairingKey *publicKey;

- (void).cxx_destruct;
- (id)debugDescription;
- (id)description;
- (id)descriptionWithPointer:(bool)arg1;
- (unsigned long long)hash;
- (id)identifier;
- (id)init;
- (id)initWithIdentifier:(id)arg1 publicKey:(id)arg2 privateKey:(id)arg3 permissions:(unsigned long long)arg4;
- (bool)isEqual:(id)arg1;
- (unsigned long long)permissions;
- (id)privateKey;
- (id)publicKey;
- (id)shortDescription;

@end
