/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthDaemon.framework/HealthDaemon
 */

@interface HDCodableLocationDatum : PBCodable <NSCopying> {
    double  _altitude;
    struct { 
        unsigned int altitude : 1; 
        unsigned int latitude : 1; 
        unsigned int longitude : 1; 
        unsigned int speed : 1; 
        unsigned int timestamp : 1; 
    }  _has;
    double  _latitude;
    double  _longitude;
    double  _speed;
    double  _timestamp;
}

@property (nonatomic) double altitude;
@property (nonatomic) bool hasAltitude;
@property (nonatomic) bool hasLatitude;
@property (nonatomic) bool hasLongitude;
@property (nonatomic) bool hasSpeed;
@property (nonatomic) bool hasTimestamp;
@property (nonatomic) double latitude;
@property (nonatomic) double longitude;
@property (nonatomic) double speed;
@property (nonatomic) double timestamp;

- (double)altitude;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (bool)hasAltitude;
- (bool)hasLatitude;
- (bool)hasLongitude;
- (bool)hasSpeed;
- (bool)hasTimestamp;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (double)latitude;
- (double)longitude;
- (void)mergeFrom:(id)arg1;
- (bool)readFrom:(id)arg1;
- (void)setAltitude:(double)arg1;
- (void)setHasAltitude:(bool)arg1;
- (void)setHasLatitude:(bool)arg1;
- (void)setHasLongitude:(bool)arg1;
- (void)setHasSpeed:(bool)arg1;
- (void)setHasTimestamp:(bool)arg1;
- (void)setLatitude:(double)arg1;
- (void)setLongitude:(double)arg1;
- (void)setSpeed:(double)arg1;
- (void)setTimestamp:(double)arg1;
- (double)speed;
- (double)timestamp;
- (void)writeTo:(id)arg1;

@end
