/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthDaemon.framework/HealthDaemon
 */

@interface HDFitnessFriendsManager : NSObject <HDCurrentActivitySummaryHelperObserver, HDFitnessFriendsActivityDataManagerDelegate, HDFitnessFriendsNotificationEngineDelegate, HDFitnessFriendsRelationshipManagerDelegate, HDHealthDaemonReadyObserver> {
    HDFitnessFriendsActivityDataManager * _activityDataManager;
    int  _activitySharingHasFriendsChangedToken;
    HDFitnessFriendsCloudKitManager * _cloudKitManager;
    HKActivitySummary * _currentActivitySummary;
    _HKDelayedOperation * _delayedListUpdateOperation;
    HDKeyValueDomain * _deviceLocalActivitySharingKeyValueDomain;
    NSMutableSet * _fitnessFriends;
    NSObject<OS_dispatch_queue> * _friendsListObserverQueue;
    NSHashTable * _friendsListObservers;
    HDFitnessFriendsGatewayManager * _gatewayManager;
    HDDaemon * _healthDaemon;
    bool  _isWatch;
    HDFitnessFriendsNotificationEngine * _notificationEngine;
    HDFitnessFriendsPeriodicUpdateManager * _periodicUpdateManager;
    NSObject<OS_dispatch_queue> * _readWriteQueue;
    HDFitnessFriendsRelationshipManager * _relationshipManager;
    HKActivitySummary * _yesterdayActivitySummary;
}

@property (nonatomic, readonly) HDFitnessFriendsActivityDataManager *activityDataManager;
@property (nonatomic, readonly) HDFitnessFriendsCloudKitManager *cloudKitManager;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) HDKeyValueDomain *deviceLocalActivitySharingKeyValueDomain;
@property (nonatomic, retain) NSMutableSet *fitnessFriends;
@property (nonatomic, readonly) HDFitnessFriendsGatewayManager *gatewayManager;
@property (nonatomic, readonly) bool hasSnapshotsToPush;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) HDDaemon *healthDaemon;
@property (nonatomic, readonly) bool isWatch;
@property (nonatomic, readonly) HDFitnessFriendsNotificationEngine *notificationEngine;
@property (nonatomic, readonly) HDFitnessFriendsPeriodicUpdateManager *periodicUpdateManager;
@property (nonatomic, readonly) HDFitnessFriendsRelationshipManager *relationshipManager;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)_copyCurrentActivitySummary;
- (id)_copyFriends;
- (id)_copyYesterdayActivitySummary;
- (id)_dateComponentsForDate:(id)arg1;
- (id)_fakeAchievementsForDate:(id)arg1;
- (id)_fakeActivitySnapshotForDate:(id)arg1 sourceUUID:(id)arg2;
- (id)_fakeWorkoutForDate:(id)arg1;
- (id)_getAllActivitySnapshotsForFriend:(id)arg1;
- (id)_getAllFriendAchievementsForFriend:(id)arg1;
- (id)_getAllFriendWorkoutsForFriend:(id)arg1;
- (void)_handleFriendListChangedNotification:(id)arg1;
- (bool)_hasFriendsToShareWith;
- (void)_notifyObserversOfUpdatedFriends:(id)arg1;
- (void)_notifySubmanagersOfManagerReady;
- (void)_pushActivityDataWithNotificationEvents:(id)arg1 completion:(id /* block */)arg2;
- (void)_queue_friendListDidUpdate;
- (id)_queue_friendWithUUID:(id)arg1;
- (void)_queue_handleHasFriendsChanged;
- (bool)_queue_hasFriendsToShareWith;
- (void)_queue_updateFriendListFromFriendKit;
- (void)_updateFriendListWithNewSnapshots:(id)arg1 friendAchievements:(id)arg2 friendWorkouts:(id)arg3;
- (id)activityDataManager;
- (void)addFriendsListObserver:(id)arg1;
- (void)clearFriendListWithCompletion:(id /* block */)arg1;
- (void)cloudKitAccountStatusWithCompletion:(id /* block */)arg1;
- (id)cloudKitManager;
- (void)currentActivitySummaryHelper:(id)arg1 didUpdateTodayActivitySummary:(id)arg2 changedFields:(unsigned long long)arg3;
- (void)currentActivitySummaryHelper:(id)arg1 didUpdateYesterdayActivitySummary:(id)arg2 changedFields:(unsigned long long)arg3;
- (void)daemonReady:(id)arg1;
- (void)dealloc;
- (id)deviceLocalActivitySharingKeyValueDomain;
- (void)fetchAndUpdateActivityDataForAllFriendsWithCompletion:(id /* block */)arg1;
- (void)fetchMySharedActivityDataWithCompletion:(id /* block */)arg1;
- (id)fitnessFriends;
- (void)fitnessFriendsActivityDataManager:(id)arg1 recievedNewSnapshots:(id)arg2 workouts:(id)arg3 achievements:(id)arg4;
- (id)gatewayManager;
- (bool)hasSnapshotsToPush;
- (id)healthDaemon;
- (void)ignoreInviteRequestFromFriendWithUUID:(id)arg1 completion:(id /* block */)arg2;
- (id)initWithHealthDaemon:(id)arg1 isWatch:(bool)arg2;
- (bool)isWatch;
- (id)notificationEngine;
- (void)notificationEngine:(id)arg1 didDetectEvents:(id)arg2;
- (id)periodicUpdateManager;
- (void)pushActivityDataWithCompletion:(id /* block */)arg1;
- (void)pushFakeActivityDataToAllFriendsWithCompletion:(id /* block */)arg1;
- (id)relationshipManager;
- (void)relationshipManager:(id)arg1 didRemoveFriendWithUUID:(id)arg2;
- (void)relationshipManager:(id)arg1 didUpdateFriendListWithPerson:(id)arg2;
- (void)removeFriendWithUUID:(id)arg1 completion:(id /* block */)arg2;
- (void)removeFriendsListObserver:(id)arg1;
- (void)sendInviteRequestToDestination:(id)arg1 addressBookGUID:(id)arg2 serviceIdentifier:(id)arg3 completion:(id /* block */)arg4;
- (void)sendInviteResponse:(long long)arg1 toFriendWithUUID:(id)arg2 completion:(id /* block */)arg3;
- (void)sendWithdrawInviteRequestToFriendWithUUID:(id)arg1 completion:(id /* block */)arg2;
- (void)setActivityDataVisible:(bool)arg1 toFriendWithUUID:(id)arg2 completion:(id /* block */)arg3;
- (void)setFitnessFriends:(id)arg1;
- (void)setMuteEnabled:(bool)arg1 forFriendWithUUID:(id)arg2 completion:(id /* block */)arg3;
- (void)showNotifications:(id)arg1;
- (id)snapshotForPersonWithUUID:(id)arg1 forDate:(id)arg2;
- (void)updateShareWithActivitySnapshots:(id)arg1 achievements:(id)arg2 workouts:(id)arg3 notificationEvents:(id)arg4 completion:(id /* block */)arg5;

@end
