/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthDaemon.framework/HealthDaemon
 */

@interface HDFitnessFriendsRelationshipManager : NSObject <HDFitnessFriendsBBDataProviderDelegate, HDFitnessFriendsCloudKitManagerChangesObserver, HDFitnessFriendsGatewayManagerChangesObserver, HDFitnessFriendsIDSMessageCenterDelegate, HDFitnessFriendsManagerReadyObserver> {
    ACAccountStore * _accountStore;
    NSMutableArray * _blocksWaitingOnCloudKitFetch;
    HDFitnessFriendsInvitationBBDataProvider * _bulletinBoardInvitationDataProvider;
    HDFitnessFriendsCloudKitManager * _cloudKitManager;
    <HDFitnessFriendsRelationshipManagerDelegate> * _delegate;
    FKFriendsManager * _friendsManager;
    HDFitnessFriendsGatewayManager * _gatewayManager;
    NSDictionary * _messageCenters;
    NSObject<OS_dispatch_group> * _newRelationshipBarrierGroup;
    NSMutableDictionary * _relationshipRecordsToReconcile;
    NSObject<OS_dispatch_queue> * _serialQueue;
}

@property (nonatomic, readonly) NSSet *allFriends;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <HDFitnessFriendsRelationshipManagerDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_beginNewRelationshipTransaction;
- (void)_endNewRelationshipTransaction;
- (void)_notifyDelegateOfChangesToPerson:(id)arg1;
- (void)_performBlockAfterCloudKitFetch:(id /* block */)arg1;
- (void)_performBlockAfterNewRelationshipTransactionsFinish:(id /* block */)arg1;
- (void)_queue_acceptShares:(id)arg1 forRelationship:(id)arg2 person:(id)arg3 completion:(id /* block */)arg4;
- (void)_queue_addFriendIfNecessary:(id)arg1;
- (void)_queue_addPersonWithCloudKitAddress:(id)arg1 toShares:(id)arg2 completion:(id /* block */)arg3;
- (id)_queue_allFriends;
- (id)_queue_createOrFetchPersonWithDestinations:(id)arg1 addressBookGUID:(id)arg2;
- (void)_queue_fetchSharesForRelationship:(id)arg1 completion:(id /* block */)arg2;
- (id)_queue_findPersonWithRelationshipShareRecordID:(id)arg1;
- (id)_queue_findPersonWithRemoteRelationshipRecordZoneID:(id)arg1;
- (id)_queue_handleSavedRecords:(id)arg1 forPerson:(id)arg2;
- (id)_queue_pendingInviteCount;
- (id)_queue_personWithFriendUUID:(id)arg1;
- (id)_queue_personWithIncomingHandshakeToken:(id)arg1;
- (id)_queue_personWithOutgoingHandshakeToken:(id)arg1;
- (void)_queue_reconcileCloudKitRelationships:(id)arg1;
- (void)_queue_saveRelationship:(id)arg1 person:(id)arg2 completion:(id /* block */)arg3;
- (void)_queue_saveRelationshipAndFetchOrCreateShare:(id)arg1 person:(id)arg2 completion:(id /* block */)arg3;
- (void)_removeFriendWithUUID:(id)arg1 eventType:(long long)arg2 completion:(id /* block */)arg3;
- (bool)_shouldFilterIncomingMessageFrom:(id)arg1;
- (id)allFriends;
- (void)beginReceivingMessages;
- (void)bulletinProvider:(id)arg1 didReceiveActionResponse:(long long)arg2 fromPersonWithUUID:(id)arg3;
- (void)clearFriendList;
- (void)cloudKitManager:(id)arg1 didRecieveNewRelationships:(id)arg2 fromRecordZoneWithID:(id)arg3 moreComing:(bool)arg4 changesProcessedHandler:(id /* block */)arg5;
- (void)cloudKitManager:(id)arg1 didRecieveNewRemoteRelationships:(id)arg2 fromRecordZoneWithID:(id)arg3 moreComing:(bool)arg4 changesProcessedHandler:(id /* block */)arg5;
- (void)cloudKitManagerDidFinishFetching:(id)arg1;
- (id)delegate;
- (id)deviceCloudKitAddress;
- (id)fakePersonWithDestinations:(id)arg1;
- (void)fitnessFriendsManagerReady:(id)arg1;
- (id)friendUUIDForPerson:(id)arg1;
- (id)friendUUIDForPersonWithActivityDataShareRecordZoneID:(id)arg1;
- (void)gatewayManagerStatusDidChange;
- (void)ignoreInviteRequestFromFriendWithUUID:(id)arg1 completion:(id /* block */)arg2;
- (id)init;
- (bool)isMuteEnabledForPerson:(id)arg1;
- (void)messageCenter:(id)arg1 didReceiveFinalizeHandshake:(id)arg2 fromSenderAddress:(id)arg3 messageHandledCompletion:(id /* block */)arg4;
- (void)messageCenter:(id)arg1 didReceiveInviteRequest:(id)arg2 fromSenderAddress:(id)arg3 messageHandledCompletion:(id /* block */)arg4;
- (void)messageCenter:(id)arg1 didReceiveInviteResponse:(id)arg2 fromSenderAddress:(id)arg3 messageHandledCompletion:(id /* block */)arg4;
- (void)messageCenter:(id)arg1 didReceiveWithdrawInviteRequest:(id)arg2 fromSenderAddress:(id)arg3 messageHandledCompletion:(id /* block */)arg4;
- (id)personWithFriendUUID:(id)arg1;
- (id)relationshipZone;
- (void)removeFriendWithUUID:(id)arg1 completion:(id /* block */)arg2;
- (void)sendInviteResponse:(long long)arg1 toFriendWithUUID:(id)arg2 completion:(id /* block */)arg3;
- (void)sendInviteToPersonWithDestination:(id)arg1 addressBookGUID:(id)arg2 serviceIdentifier:(id)arg3 completion:(id /* block */)arg4;
- (void)sendWithdrawInviteRequestToFriendWithUUID:(id)arg1 completion:(id /* block */)arg2;
- (void)setActivityDataVisible:(bool)arg1 toFriendWithUUID:(id)arg2 completion:(id /* block */)arg3;
- (void)setDelegate:(id)arg1;
- (void)setMuteEnabled:(bool)arg1 forFriendWithUUID:(id)arg2 completion:(id /* block */)arg3;

@end
