/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthDaemon.framework/HealthDaemon
 */

@interface HDFitnessFriendsInvitationBBDataProvider : NSObject <BBRemoteDataProvider> {
    NSObject<OS_dispatch_queue> * _bulletinQueue;
    NSMutableDictionary * _currentBulletinRequestsByRequestID;
    BBDataProviderConnection * _dataProviderConnection;
    BBDataProviderProxy * _dataProviderProxy;
    <HDFitnessFriendsBBDataProviderDelegate> * _delegate;
    int  notifyInviteRequestToken;
    int  notifyInviteResponseToken;
    int  notifyOfInviteToken;
}

@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <HDFitnessFriendsBBDataProviderDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)_bulletinForInvitationFromPerson:(id)arg1;
- (id)_fakePerson;
- (id)_newPrepopulatedBulletinRequest;
- (void)_notifyOfFakeInvitationRequest;
- (void)_notifyOfInvitationFromPerson:(id)arg1;
- (void)_queue_addBulletinRequest:(id)arg1;
- (void)_queue_removeBulletinRequestsWithType:(id)arg1 fromPerson:(id)arg2;
- (void)_queue_removeBulletins:(id)arg1;
- (void)_showFakeInvitationRequest;
- (void)_showFakeInvitationResponse;
- (void)_showInvitationRequestFromPerson:(id)arg1;
- (void)_showInvitationResponseFromPerson:(id)arg1;
- (id)bulletinsWithRequestParameters:(id)arg1 lastCleared:(id)arg2;
- (id)clearedInfoForBulletins:(id)arg1 lastClearedInfo:(id)arg2;
- (void)dealloc;
- (id)defaultSectionInfo;
- (id)delegate;
- (void)handleBulletinActionResponse:(id)arg1;
- (id)initWithDelegate:(id)arg1;
- (id)sectionDisplayName;
- (id)sectionIdentifier;
- (void)setDelegate:(id)arg1;
- (void)showInviteAcceptResponseFrom:(id)arg1;
- (void)showInviteRequestFrom:(id)arg1;
- (id)sortDescriptors;
- (id)universalSectionIdentifier;
- (void)withdrawInviteRequestFrom:(id)arg1;

@end
