/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthDaemon.framework/HealthDaemon
 */

@interface HDLocationDataCollector : NSObject <CLLocationManagerDelegate> {
    <HDHealthDaemon> * _daemon;
    <HDLocationEventDelegate> * _delegate;
    CMElevation * _elevation;
    CLInUseAssertion * _inUseAssertion;
    CLLocationManager * _locationManager;
    NSObject<OS_dispatch_queue> * _queue;
    HKLocationSeriesSample * _seriesSample;
    HDServer * _server;
}

@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <HDLocationEventDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) HKLocationSeriesSample *seriesSample;
@property (nonatomic, retain) HDServer *server;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_handleCreatedLocationSeriesSample;
- (void)_handleElevationData:(id)arg1 error:(id)arg2;
- (void)_queue_stopUpdatingLocation;
- (id)delegate;
- (id)entityForUUID:(id)arg1;
- (id)initWithDaemon:(id)arg1 server:(id)arg2;
- (void)locationManager:(id)arg1 didChangeAuthorizationStatus:(int)arg2;
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;
- (void)locationManager:(id)arg1 didUpdateLocations:(id)arg2;
- (id)seriesSample;
- (id)server;
- (void)setDelegate:(id)arg1;
- (void)setServer:(id)arg1;
- (void)start;
- (void)stop;

@end
