/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/PhotosUI.framework/PhotosUI
 */

@interface PUIrisImageTileViewController : PUImageTileViewController <PHLivePhotoViewDelegate, PHLivePhotoViewDelegatePrivate, _UISettingsKeyObserver> {
    PHLivePhotoView * __livePhotoView;
    bool  __needUpdateIrisContent;
    bool  _canLoadIrisContent;
    <PUIrisImageTileViewControllerDelegate> * _delegate;
    struct { 
        bool respondsToDidBeginPlaying; 
        bool respondsToWillEndPlaying; 
        bool respondsToDidEndPlaying; 
        bool respondsToDidEndVitality; 
        bool respondsToViewHostingGestureRecognizers; 
        bool respondsToDelegateForGestureRecognizer; 
    }  _delegateFlags;
}

@property (nonatomic, readonly) PHLivePhotoView *_livePhotoView;
@property (setter=_setNeedsUpdateIrisContent:, nonatomic) bool _needUpdateIrisContent;
@property (nonatomic) bool canLoadIrisContent;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <PUIrisImageTileViewControllerDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_assetFocusValueDidChange;
- (void)_handleBrowsingIrisPlayer:(id)arg1 didChange:(id)arg2;
- (void)_invalidateIrisContent;
- (id)_livePhotoView;
- (bool)_needUpdateIrisContent;
- (bool)_needsIrisUpdate;
- (void)_playVitalityHintIfNeeded;
- (void)_playerViewReadinessDidChange;
- (void)_setLivePhotoView:(id)arg1;
- (void)_setNeedsUpdateIrisContent:(bool)arg1;
- (void)_updateIrisContentIfNeeded;
- (void)_updateIrisIfNeeded;
- (void)_updateLivePhotoViewVitalityEnabled;
- (void)_updatePlaybackGestureRecognizer;
- (void)_updatePlayerViewInteractivePlaybackAllowed;
- (void)applyLayoutInfo:(id)arg1;
- (void)assetViewModelDidChange;
- (void)becomeReusable;
- (bool)canLoadIrisContent;
- (id)delegate;
- (void)didChangeAnimating;
- (void)livePhotoView:(id)arg1 didEndPlaybackWithStyle:(long long)arg2;
- (void)livePhotoView:(id)arg1 willBeginPlaybackWithStyle:(long long)arg2;
- (void)livePhotoViewDidEndPlayingVitality:(id)arg1;
- (void)setAssetViewModel:(id)arg1;
- (void)setCanLoadIrisContent:(bool)arg1;
- (void)setDelegate:(id)arg1;
- (void)settings:(id)arg1 changedValueForKey:(id)arg2;
- (void)viewDidLoad;
- (void)viewModel:(id)arg1 didChange:(id)arg2;

@end
