/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/PhotosUI.framework/PhotosUI
 */

@interface PUTimelineScrubberView : UIView <PXChangeObserver, UIScrollViewDelegate> {
    UIScrollView * __scrollView;
    bool  _isUpdatingScrollView;
    PUTimelineScrubberModel * _scrubberModel;
}

@property (nonatomic, readonly) UIScrollView *_scrollView;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) PUTimelineScrubberModel *scrubberModel;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (double)_modelOffsetFromScrollView;
- (id)_scrollView;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })_scrollViewContentInsetsFromModel;
- (struct CGPoint { double x1; double x2; })_scrollViewContentOffsetFromModel;
- (struct CGSize { double x1; double x2; })_scrollViewContentSizeFromModel;
- (void)_updateModelOffset;
- (void)_updateScrollViewContentInsets;
- (void)_updateScrollViewContentOffset;
- (void)_updateScrollViewContentSize;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (id)initWithScrubberModel:(id)arg1;
- (void)layoutSubviews;
- (void)observable:(id)arg1 didChange:(unsigned long long)arg2 context:(void*)arg3;
- (void)scrollViewDidScroll:(id)arg1;
- (id)scrubberModel;

@end
