/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/PhotosUI.framework/PhotosUI
 */

@interface PUTimelineScrubberModel : PXObservable <PUMutableTimelineScrubberModel> {
    double  __accelerationFactor;
    struct PUTimelineScrubberInsets { 
        double start; 
        double end; 
    }  _contentInsets;
    double  _contentOffset;
    double  _contentRange;
    struct { 
        bool scrubberRange; 
        bool scrubberOffset; 
        bool contentOffset; 
    }  _needsUpdateFlags;
    struct PUTimelineScrubberInsets { 
        double start; 
        double end; 
    }  _scrubberInsets;
    double  _scrubberOffset;
    double  _scrubberRange;
    double  _scrubbingRate;
}

@property (setter=_setAccelerationFactor:, nonatomic) double _accelerationFactor;
@property (nonatomic, readonly) struct PUTimelineScrubberInsets { double x1; double x2; } contentInsets;
@property (nonatomic, readonly) double contentOffset;
@property (nonatomic, readonly) double contentRange;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) struct PUTimelineScrubberInsets { double x1; double x2; } scrubberInsets;
@property (nonatomic, readonly) double scrubberOffset;
@property (setter=_setScrubberRange:, nonatomic) double scrubberRange;
@property (nonatomic, readonly) double scrubbingRate;
@property (readonly) Class superclass;

- (double)_accelerationFactor;
- (void)_invalidateContentOffset;
- (void)_invalidateScrubberOffset;
- (void)_invalidateScrubberRange;
- (bool)_needsUpdate;
- (void)_setAccelerationFactor:(double)arg1;
- (void)_setContentOffset:(double)arg1 fromSource:(unsigned long long)arg2;
- (void)_setNeedsUpdate;
- (void)_setScrubberOffset:(double)arg1 fromSource:(unsigned long long)arg2;
- (void)_setScrubberRange:(double)arg1;
- (void)_updateContentOffsetIfNeeded;
- (void)_updateIfNeeded;
- (void)_updateScrubberOffsetIfNeeded;
- (void)_updateScrubberRangeIfNeeded;
- (struct PUTimelineScrubberInsets { double x1; double x2; })contentInsets;
- (double)contentOffset;
- (double)contentOffsetForScrubberOffset:(double)arg1;
- (double)contentRange;
- (void)didPerformChanges;
- (double)foreignOffsetForLocalOffset:(double)arg1 inLocalRange:(double)arg2 withLocalInsets:(struct PUTimelineScrubberInsets { double x1; double x2; })arg3 foreignRange:(double)arg4 foreignInsets:(struct PUTimelineScrubberInsets { double x1; double x2; })arg5 localToForeignRatio:(double)arg6;
- (id)init;
- (id)mutableChangeObject;
- (void)performChanges:(id /* block */)arg1;
- (struct PUTimelineScrubberInsets { double x1; double x2; })scrubberInsets;
- (double)scrubberOffset;
- (double)scrubberOffsetForContentOffset:(double)arg1;
- (double)scrubberRange;
- (double)scrubbingRate;
- (void)setContentInsets:(struct PUTimelineScrubberInsets { double x1; double x2; })arg1;
- (void)setContentOffset:(double)arg1;
- (void)setContentRange:(double)arg1;
- (void)setScrubberOffset:(double)arg1;
- (void)setScrubbingRate:(double)arg1;

@end
