/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/PhotosUI.framework/PhotosUI
 */

@interface PUTimelineScrubberRateCalculator : NSObject

@property (nonatomic, readonly) double dateScrubbingRate;
@property (nonatomic, readonly) double libraryScrubbingRate;

- (double)dateScrubbingRate;
- (double)libraryScrubbingRate;

@end
