/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/PhotosUI.framework/PhotosUI
 */

@interface PUWhatsNewWelcomeViewController : PUWelcomeViewController {
    id /* block */  __completionHandler;
    UIScrollView * __scrollView;
    NSLayoutConstraint * __topConstraint;
}

@property (nonatomic, readonly, copy) id /* block */ _completionHandler;
@property (nonatomic, readonly, copy) UIScrollView *_scrollView;
@property (nonatomic, readonly, copy) NSLayoutConstraint *_topConstraint;

+ (void)presentIfNecessaryFromViewController:(id)arg1 completionHandler:(id /* block */)arg2;
+ (void)resetLastPresentationInfo;

- (void).cxx_destruct;
- (id /* block */)_completionHandler;
- (void)_handleContinueButton:(id)arg1;
- (id)_initWithCompletionHandler:(id /* block */)arg1;
- (id)_scrollView;
- (id)_topConstraint;
- (void)dismissViewControllerAnimated:(bool)arg1 completion:(id /* block */)arg2;
- (void)viewDidAppear:(bool)arg1;
- (void)viewDidLoad;
- (void)viewWillLayoutSubviews;

@end
