/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreKnowledge.framework/CoreKnowledge
 */

@interface CoreKnowledge.CKDeviceActivityStore : NSObject <CoreKnowledge.CKReadableDeviceActivityStore, CoreKnowledge.CKWritableDeviceActivityStore> {
    void store;
}

+ (id)dateFormat;

- (id /* block */).cxx_destruct;
- (id)init;
- (bool)recordActivityWithIdentifier:(id)arg1 startDate:(id)arg2 endDate:(id)arg3 error:(id*)arg4;
- (id)recordedActivityWithIdentifier:(id)arg1;

@end
