/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreData.framework/CoreData
 */

@interface NSCachedFetchRequestThunk : NSObject {
    NSSQLiteStatement * _limitedStatement;
    long long  _refCount;
    NSSQLiteStatement * _unlimitedStatement;
}

@property (readonly) long long inUseCounter;
@property (nonatomic, retain) NSSQLiteStatement *limitedStatement;
@property (nonatomic, retain) NSSQLiteStatement *unlimitedStatement;

- (void)clearCaches;
- (void)dealloc;
- (void)decrementInUseCounter;
- (long long)inUseCounter;
- (void)incrementInUseCounter;
- (id)init;
- (id)limitedStatement;
- (void)setLimitedStatement:(id)arg1;
- (void)setUnlimitedStatement:(id)arg1;
- (id)unlimitedStatement;

@end
