/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PDFKit.framework/PDFKit
 */

@interface PDFScrollViewPrivate : NSObject {
    PDFDocument * document;
    PDFDocumentView * documentView;
    double  oldMagnification;
    NSTimer * updateVisibilityTimer;
}

- (void).cxx_destruct;

@end
