/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@interface SKUIApplicationControllerOptions : NSObject <NSCopying, NSMutableCopying> {
    bool  _requiresLocalBootstrapScript;
    bool  _supportsFullApplicationReload;
    long long  _tabBarControllerStyle;
}

@property (nonatomic, readonly) bool requiresLocalBootstrapScript;
@property (nonatomic, readonly) bool supportsFullApplicationReload;
@property (nonatomic, readonly) long long tabBarControllerStyle;

- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (unsigned long long)hash;
- (id)init;
- (bool)isEqual:(id)arg1;
- (id)mutableCopyWithZone:(struct _NSZone { }*)arg1;
- (bool)requiresLocalBootstrapScript;
- (bool)supportsFullApplicationReload;
- (long long)tabBarControllerStyle;

@end
