/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/EventKit.framework/EventKit
 */

@interface EKTravelEngineHypothesis : NSObject <NSSecureCoding> {
    NSDate * _aggressiveDepartureDate;
    double  _aggressiveTravelTime;
    unsigned long long  _currentTrafficDensity;
    NSDate * _originalConservativeDepartureDate;
    double  _originalConservativeTravelTime;
    double  _originalEstimatedTravelTime;
    NSDate * _originalSuggestedDepartureDate;
    NSDate * _roundedConservativeDepartureDate;
    double  _roundedConservativeTravelTime;
    double  _roundedEstimatedTravelTime;
    NSDate * _roundedSuggestedDepartureDate;
    NSString * _routeName;
    bool  _supportsLiveTraffic;
    NSString * _trafficDensityDescription;
    int  _transportType;
    long long  _travelState;
}

@property (nonatomic, retain) NSDate *aggressiveDepartureDate;
@property (nonatomic) double aggressiveTravelTime;
@property (nonatomic) unsigned long long currentTrafficDensity;
@property (nonatomic, retain) NSDate *originalConservativeDepartureDate;
@property (nonatomic) double originalConservativeTravelTime;
@property (nonatomic, readonly) double originalEffectiveTravelTime;
@property (nonatomic) double originalEstimatedTravelTime;
@property (nonatomic, retain) NSDate *originalSuggestedDepartureDate;
@property (nonatomic, retain) NSDate *roundedConservativeDepartureDate;
@property (nonatomic) double roundedConservativeTravelTime;
@property (nonatomic, readonly) double roundedEffectiveTravelTime;
@property (nonatomic) double roundedEstimatedTravelTime;
@property (nonatomic, retain) NSDate *roundedSuggestedDepartureDate;
@property (nonatomic, retain) NSString *routeName;
@property (nonatomic) bool supportsLiveTraffic;
@property (nonatomic, retain) NSString *trafficDensityDescription;
@property (nonatomic) int transportType;
@property (nonatomic) long long travelState;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)aggressiveDepartureDate;
- (double)aggressiveTravelTime;
- (unsigned long long)currentTrafficDensity;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithEKGEORouteHypothesis:(id)arg1;
- (id)initWithGEORouteHypothesis:(id)arg1;
- (id)initWithSyntheticGEORouteHypothesis:(id)arg1;
- (id)originalConservativeDepartureDate;
- (double)originalConservativeTravelTime;
- (double)originalEffectiveTravelTime;
- (double)originalEstimatedTravelTime;
- (id)originalSuggestedDepartureDate;
- (id)roundedConservativeDepartureDate;
- (double)roundedConservativeTravelTime;
- (double)roundedEffectiveTravelTime;
- (double)roundedEstimatedTravelTime;
- (id)roundedSuggestedDepartureDate;
- (id)routeName;
- (void)setAggressiveDepartureDate:(id)arg1;
- (void)setAggressiveTravelTime:(double)arg1;
- (void)setCurrentTrafficDensity:(unsigned long long)arg1;
- (void)setOriginalConservativeDepartureDate:(id)arg1;
- (void)setOriginalConservativeTravelTime:(double)arg1;
- (void)setOriginalEstimatedTravelTime:(double)arg1;
- (void)setOriginalSuggestedDepartureDate:(id)arg1;
- (void)setRoundedConservativeDepartureDate:(id)arg1;
- (void)setRoundedConservativeTravelTime:(double)arg1;
- (void)setRoundedEstimatedTravelTime:(double)arg1;
- (void)setRoundedSuggestedDepartureDate:(id)arg1;
- (void)setRouteName:(id)arg1;
- (void)setSupportsLiveTraffic:(bool)arg1;
- (void)setTrafficDensityDescription:(id)arg1;
- (void)setTransportType:(int)arg1;
- (void)setTravelState:(long long)arg1;
- (bool)supportsLiveTraffic;
- (id)trafficDensityDescription;
- (int)transportType;
- (long long)travelState;

@end
