/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CalendarFoundation.framework/CalendarFoundation
 */

@interface EKTTLEventTracker : NSObject

+ (id)featureID;
+ (void)trackTTLAlertDirectionsEngaged;
+ (void)trackTTLAlertFired;
+ (void)trackTTLEventCandidate;
+ (id)ttlAlertDirectionsEngagedEventTracker;
+ (id)ttlAlertFiredEventTracker;

@end
