/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DataDetectorsUI.framework/DataDetectorsUI
 */

@interface DDActionSuggestionsContext : NSObject {
    NSString * _coreSpotlightUniqueIdentifier;
}

@property (retain) NSString *coreSpotlightUniqueIdentifier;

- (id)coreSpotlightUniqueIdentifier;
- (void)dealloc;
- (void)setCoreSpotlightUniqueIdentifier:(id)arg1;

@end
