/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DataDetectorsUI.framework/DataDetectorsUI
 */

@interface DDParsecCollectionViewController : UINavigationController <DDParsecHostVCInterface, UINavigationControllerDelegate> {
    NSArray * _actions;
    UIView * _blurView;
    NSDictionary * _context;
    id /* block */  _dismissCompletionHandler;
    <DDParsecCollectionDelegate> * _parsecDelegate;
    bool  _popoverMode;
    bool  _previewMode;
    struct _NSRange { 
        unsigned long long location; 
        unsigned long long length; 
    }  _queryRange;
    NSString * _queryString;
    DDParsecRemoteCollectionViewController * _remoteViewController;
    DDScannerResult * _result;
    bool  _showingError;
}

@property (copy) NSArray *actions;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (copy) id /* block */ dismissCompletionHandler;
@property (readonly) unsigned long long hash;
@property <DDParsecCollectionDelegate> *parsecDelegate;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_updatePreferredContentSize;
- (id)actions;
- (id /* block */)dismissCompletionHandler;
- (void)doneButtonPressed:(id)arg1;
- (void)fetchRemoteViewControllerWithValidInput:(bool)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithResult:(struct __DDResult { }*)arg1 context:(id)arg2;
- (id)initWithString:(id)arg1 range:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg2;
- (void)interactionEnded;
- (void)openParsecURL:(id)arg1;
- (id)parsecDelegate;
- (void)presentRemoteCollection:(id)arg1;
- (id)previewActionItems;
- (void)replaceControllerWithController:(id)arg1;
- (void)setActions:(id)arg1;
- (void)setDismissCompletionHandler:(id /* block */)arg1;
- (void)setParsecDelegate:(id)arg1;
- (void)setPopoverMode:(bool)arg1;
- (void)setPreviewMode:(bool)arg1;
- (void)showError:(id)arg1;
- (void)showSpinner;
- (void)showingErrorView:(bool)arg1;
- (void)updateVisualMode;
- (void)viewWillAppear:(bool)arg1;

@end
