/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SpriteKit.framework/SpriteKit
 */

@interface SKShaderTargetNodeReference : NSObject {
    SKNode * _targetNode;
}

@property (nonatomic) SKNode *targetNode;

- (void).cxx_destruct;
- (void)setTargetNode:(id)arg1;
- (id)targetNode;

@end
