/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DuetExpertCenter.framework/DuetExpertCenter
 */

@interface _DECTypes : NSObject

+ (unsigned long long)categoryForItem:(id)arg1;
+ (id)categoryMapping;
+ (id)consumerMapping;
+ (id)consumerSubtypeMapping;
+ (unsigned long long)intersectCategories:(unsigned long long)arg1 withCategories:(unsigned long long)arg2;
+ (void)invokeBlockOverCategoriesMatching:(unsigned long long)arg1 block:(id /* block */)arg2;
+ (id)outcomeMapping;
+ (id)predictionReasonMapping;
+ (id)stringForAppPredictionSources:(unsigned char)arg1;
+ (id)stringForCategory:(unsigned long long)arg1;
+ (id)stringForConsumerSubtype:(unsigned char)arg1;
+ (id)stringForConsumerType:(unsigned long long)arg1;
+ (id)stringForLaunchSource:(long long)arg1;
+ (id)stringForOutcome:(unsigned long long)arg1;
+ (id)stringForPredictionReason:(long long)arg1;

@end
