/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

@interface SAIntentGroupSnippet : SAUISnippet

@property (nonatomic, copy) NSString *appId;
@property (nonatomic, retain) SAIntentGroupProtobufMessage *intent;
@property (nonatomic, retain) <SAServerBoundCommand> *processSynapseFlowCommand;
@property (nonatomic, copy) NSArray *snippetTemplates;
@property (nonatomic, copy) NSString *title;
@property (nonatomic) bool widgetAllowed;
@property (nonatomic, copy) NSNumber *widgetIndex;

+ (id)snippet;
+ (id)snippetWithDictionary:(id)arg1 context:(id)arg2;

- (id)appId;
- (id)encodedClassName;
- (id)groupIdentifier;
- (id)intent;
- (id)processSynapseFlowCommand;
- (void)setAppId:(id)arg1;
- (void)setIntent:(id)arg1;
- (void)setProcessSynapseFlowCommand:(id)arg1;
- (void)setSnippetTemplates:(id)arg1;
- (void)setTitle:(id)arg1;
- (void)setWidgetAllowed:(bool)arg1;
- (void)setWidgetIndex:(id)arg1;
- (id)snippetTemplates;
- (id)title;
- (bool)widgetAllowed;
- (id)widgetIndex;

@end
