/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices
 */

@interface PLCloudScenarioExecutionResult : NSObject {
    bool  _duplicateScenario;
    NSMutableArray * _failedOperations;
    NSMutableArray * _successfullOperations;
}

@property (nonatomic) bool duplicateScenario;
@property (nonatomic, retain) NSMutableArray *failedOperations;
@property (nonatomic, retain) NSMutableArray *successfullOperations;

- (void)dealloc;
- (bool)duplicateScenario;
- (id)failedOperations;
- (id)init;
- (void)setDuplicateScenario:(bool)arg1;
- (void)setFailedOperations:(id)arg1;
- (void)setSuccessfullOperations:(id)arg1;
- (id)successfullOperations;

@end
