/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices
 */

@interface PLCloudCacheResetMessage : NSObject {
    bool  _hardReset;
}

@property (nonatomic, readonly) bool hardReset;

- (bool)hardReset;
- (id)initAsHardReset:(bool)arg1;

@end
