/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices
 */

@interface PLCloudLegacyPruneOperation : PLCloudLegacyOperation {
    bool  _cancelled;
}

- (id)_cloudResourceForCPLResource:(id)arg1 inPhotoLibrary:(id)arg2 outAssetsAffected:(id)arg3;
- (void)_resetCloudPlaceholderKindForAsset:(id)arg1;
- (bool)canPruneResource;
- (unsigned long long)cost;
- (bool)keepOriginalsEnabled;
- (void)markAsNotLocallyAvailable;
- (void)requestCancel;
- (void)runOperationWithCompletionHandler:(id /* block */)arg1;

@end
