/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices
 */

@interface PLDetectedFace : PLManagedObject <PLSyncableDetectedFace>

@property (nonatomic, copy) NSDate *adjustmentVersion;
@property (nonatomic, retain) NSDate *adjustmentVersion;
@property (nonatomic, retain) PLManagedAsset *asset;
@property (nonatomic) double centerX;
@property (nonatomic) double centerY;
@property (nonatomic) short cloudLocalState;
@property (nonatomic) long long clusterSequenceNumber;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic) double expressionConfidence;
@property (nonatomic) double expressionScore1;
@property (nonatomic) double expressionScore2;
@property (nonatomic) double expressionScore3;
@property (nonatomic) long long expressionType1;
@property (nonatomic) long long expressionType2;
@property (nonatomic) long long expressionType3;
@property (nonatomic) long long faceAlgorithmVersion;
@property (nonatomic, retain) PLDetectedFaceGroup *faceGroupBeingKeyFace;
@property (nonatomic, retain) NSSet *faceGroups;
@property (nonatomic, retain) PLDetectedFaceprint *faceprint;
@property (nonatomic) bool hasSmile;
@property (readonly) unsigned long long hash;
@property (nonatomic) bool hidden;
@property (nonatomic) bool isBlurred;
@property (nonatomic) bool isHiddenInGroups;
@property (nonatomic) bool isInTrash;
@property (nonatomic) bool isLeftEyeClosed;
@property (nonatomic) bool isRightEyeClosed;
@property (nonatomic) double leftEyeX;
@property (nonatomic) double leftEyeY;
@property (nonatomic) bool manual;
@property (nonatomic, retain) NSString *masterIdentifier;
@property (nonatomic) double mouthX;
@property (nonatomic) double mouthY;
@property (nonatomic) int nameSource;
@property (nonatomic) bool nameSourceAuto;
@property (nonatomic, retain) <PLSyncablePerson> *person;
@property (nonatomic, retain) PLPerson *person;
@property (nonatomic, retain) <PLSyncablePerson> *personBeingKeyFace;
@property (nonatomic, retain) PLPerson *personBeingKeyFace;
@property (nonatomic) double posePitch;
@property (nonatomic) double poseRoll;
@property (nonatomic) double poseYaw;
@property (nonatomic) long long qualityMeasure;
@property (nonatomic, retain) NSSet *rejectedPeople;
@property (nonatomic) double rightEyeX;
@property (nonatomic) double rightEyeY;
@property (nonatomic) double size;
@property (nonatomic) long long sourceHeight;
@property (nonatomic) long long sourceWidth;
@property (readonly) Class superclass;
@property (nonatomic, retain) NSString *uuid;

+ (id)_allSyncableFacesInManagedObjectContext:(id)arg1;
+ (id)detectedFaceWithUUID:(id)arg1 inManagedObjectContext:(id)arg2;
+ (id)entityInManagedObjectContext:(id)arg1;
+ (id)entityName;
+ (id)findExistingFaceMatchingRef:(id)arg1 inFaces:(id)arg2 inAsset:(id)arg3;
+ (id)insertInManagedObjectContext:(id)arg1;
+ (long long)resetAssetForAllSyncableFacesInManagedObjectContext:(id)arg1 error:(id*)arg2;
+ (id)userCuratedFacePredicate;

- (void)awakeFromInsert;
- (id)debugLogDescription;
- (void)delete;
- (bool)nameSourceAuto;
- (id)rejectedPeople;
- (void)removeFaceprint;
- (void)setNameSourceAuto:(bool)arg1;
- (void)setRejectedPeople:(id)arg1;
- (void)willSave;

@end
