/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreCDPUI.framework/CoreCDPUI
 */

@interface CDPEscapeOption : NSObject {
    id /* block */  _escapeAction;
    unsigned long long  _style;
    NSString * _title;
}

@property (nonatomic, copy) id /* block */ escapeAction;
@property (nonatomic) unsigned long long style;
@property (nonatomic, copy) NSString *title;

- (void).cxx_destruct;
- (id /* block */)escapeAction;
- (void)setEscapeAction:(id /* block */)arg1;
- (void)setStyle:(unsigned long long)arg1;
- (void)setTitle:(id)arg1;
- (unsigned long long)style;
- (id)title;

@end
