/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CalendarDatabase.framework/CalendarDatabase
 */

@interface CDBDebugPreferences : NSObject {
    CalPreferences * _preferences;
}

@property (nonatomic) bool locationPredictionsEnabled;
@property (nonatomic) bool sqlProfileLoggingEnabled;

+ (id)shared;

- (void).cxx_destruct;
- (id)init;
- (bool)locationPredictionsEnabled;
- (void)setLocationPredictionsEnabled:(bool)arg1;
- (void)setSqlProfileLoggingEnabled:(bool)arg1;
- (bool)sqlProfileLoggingEnabled;

@end
