/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ContactsUICore.framework/ContactsUICore
 */

@interface _CNUIUserActionTelephonyVoiceTarget : CNUIUserActionTarget

- (id)TTYCallActionWithDestinationID:(id)arg1 contactProperty:(id)arg2;
- (id)TTYRelayCallActionWithDestinationID:(id)arg1 contactProperty:(id)arg2;
- (id)actionsForPhoneNumbers:(id)arg1 contact:(id)arg2;
- (id)init;
- (id)phoneCallActionWithDestinationID:(id)arg1 contactProperty:(id)arg2;

@end
