/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Pegasus.framework/Pegasus
 */

@interface PGStashedView : UIView {
    bool  _active;
    PGBackdropView * _backdropView;
    PGChevronView * _chevronViewLeftColorBurn;
    PGChevronView * _chevronViewLeftPlusD;
    PGChevronView * _chevronViewRightColorBurn;
    PGChevronView * _chevronViewRightPlusD;
    bool  _stashed;
}

@property (getter=isActive, nonatomic) bool active;
@property (getter=isStashed, nonatomic) bool stashed;

- (void).cxx_destruct;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (bool)isActive;
- (bool)isStashed;
- (void)setActive:(bool)arg1;
- (void)setActive:(bool)arg1 animated:(bool)arg2;
- (void)setStashed:(bool)arg1;
- (void)setStashed:(bool)arg1 animated:(bool)arg2;

@end
