/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UIDocumentInteractionControllerOpenWithAppActivity : UIActivity {
    NSString * _activityType;
    LSApplicationProxy * _appProxy;
    bool  _defaultApp;
    UIDocumentInteractionController * _documentInteractionController;
}

@property (getter=isDefaultApp, nonatomic) bool defaultApp;
@property (nonatomic) UIDocumentInteractionController *documentInteractionController;

+ (long long)activityCategory;

- (void).cxx_destruct;
- (id)_activityImage;
- (id)_activitySettingsImage;
- (bool)_shouldOpenInPlace;
- (id)activityTitle;
- (id)activityType;
- (bool)canPerformWithActivityItems:(id)arg1;
- (id)documentInteractionController;
- (id)initWithApplicationIdentifier:(id)arg1 documentInteractionController:(id)arg2;
- (bool)isDefaultApp;
- (void)performActivity;
- (void)setDefaultApp:(bool)arg1;
- (void)setDocumentInteractionController:(id)arg1;

@end
