/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UIFallbackPresentationViewController : UIViewController {
    bool  _hasDismissCompletionHandler;
    bool  _hasPreservedKeyboardInputViews;
    _UIFallbackPresentationWindow * _presentationWindow;
    UIWindow * _rotationDecider;
}

@property (nonatomic) bool hasDismissCompletionHandler;
@property (nonatomic) bool hasPreservedKeyboardInputViews;
@property (nonatomic, retain) UIWindow *rotationDecider;

- (void).cxx_destruct;
- (void)_dismissViewControllerWithTransition:(int)arg1 from:(id)arg2 completion:(id /* block */)arg3;
- (void)_presentViewController:(id)arg1 sendingView:(id)arg2 animated:(bool)arg3;
- (void)_preserveInputViewsAnimated:(bool)arg1;
- (void)_restoreInputViewsAnimated:(bool)arg1;
- (bool)hasDismissCompletionHandler;
- (bool)hasPreservedKeyboardInputViews;
- (id)rotationDecider;
- (void)setHasDismissCompletionHandler:(bool)arg1;
- (void)setHasPreservedKeyboardInputViews:(bool)arg1;
- (void)setRotationDecider:(id)arg1;
- (bool)shouldAutorotate;
- (bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidLoad;

@end
