/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UIOpenCopyAppActivity : _UIOpenInAppActivity

- (id)activityTitle;
- (id)activityType;
- (void)performActivity;

@end
