/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIAlertControllerInterfaceActionGroupView : UIInterfaceActionGroupView {
    UIAlertController * _alertController;
}

@property (nonatomic) UIAlertController *alertController;

- (void).cxx_destruct;
- (id)_alertController;
- (id)alertController;
- (id)initWithAlertController:(id)arg1 actionGroup:(id)arg2 actionHandlerInvocationDelegate:(id)arg3;
- (void)setAlertController:(id)arg1;

@end
