/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIStatusBarBatteryItemView : UIStatusBarItemView {
    UIView * _accessoryView;
    bool  _batterySaverModeActive;
    unsigned long long  _cachedBatteryStyle;
    bool  _cachedImageHasAccessoryImage;
    _UILegibilityImageSet * _cachedImageSet;
    float  _cachedQuantizedCapacity;
    float  _quantizedCapacity;
    int  _state;
}

@property (nonatomic) unsigned long long cachedBatteryStyle;
@property (nonatomic) bool cachedImageHasAccessoryImage;
@property (nonatomic, retain) _UILegibilityImageSet *cachedImageSet;
@property (nonatomic) float cachedQuantizedCapacity;

- (void).cxx_destruct;
- (id)_accessoryImage;
- (struct CGSize { double x1; double x2; })_batteryOffsetWithBackground:(id)arg1;
- (id)_contentsImage;
- (bool)_needsAccessoryImage;
- (void)_updateAccessoryImage;
- (unsigned long long)cachedBatteryStyle;
- (bool)cachedImageHasAccessoryImage;
- (id)cachedImageSet;
- (float)cachedQuantizedCapacity;
- (id)contentsImage;
- (double)extraRightPadding;
- (double)legibilityStrength;
- (void)setCachedBatteryStyle:(unsigned long long)arg1;
- (void)setCachedImageHasAccessoryImage:(bool)arg1;
- (void)setCachedImageSet:(id)arg1;
- (void)setCachedQuantizedCapacity:(float)arg1;
- (bool)updateForNewData:(id)arg1 actions:(int)arg2;

@end
