/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEOPDSearchBrowseCategorySuggestionParameters : PBCodable <NSCopying> {
    struct { 
        unsigned int requestLocalTimestamp : 1; 
        unsigned int minimumNumberOfCategories : 1; 
        unsigned int suggestionType : 1; 
        unsigned int isCarplayRequest : 1; 
    }  _has;
    bool  _isCarplayRequest;
    int  _minimumNumberOfCategories;
    double  _requestLocalTimestamp;
    int  _suggestionType;
    GEOPDViewportInfo * _viewportInfo;
}

@property (nonatomic) bool hasIsCarplayRequest;
@property (nonatomic) bool hasMinimumNumberOfCategories;
@property (nonatomic) bool hasRequestLocalTimestamp;
@property (nonatomic) bool hasSuggestionType;
@property (nonatomic, readonly) bool hasViewportInfo;
@property (nonatomic) bool isCarplayRequest;
@property (nonatomic) int minimumNumberOfCategories;
@property (nonatomic) double requestLocalTimestamp;
@property (nonatomic) int suggestionType;
@property (nonatomic, retain) GEOPDViewportInfo *viewportInfo;

- (int)StringAsSuggestionType:(id)arg1;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (id)description;
- (id)dictionaryRepresentation;
- (bool)hasIsCarplayRequest;
- (bool)hasMinimumNumberOfCategories;
- (bool)hasRequestLocalTimestamp;
- (bool)hasSuggestionType;
- (bool)hasViewportInfo;
- (unsigned long long)hash;
- (bool)isCarplayRequest;
- (bool)isEqual:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (int)minimumNumberOfCategories;
- (bool)readFrom:(id)arg1;
- (double)requestLocalTimestamp;
- (void)setHasIsCarplayRequest:(bool)arg1;
- (void)setHasMinimumNumberOfCategories:(bool)arg1;
- (void)setHasRequestLocalTimestamp:(bool)arg1;
- (void)setHasSuggestionType:(bool)arg1;
- (void)setIsCarplayRequest:(bool)arg1;
- (void)setMinimumNumberOfCategories:(int)arg1;
- (void)setRequestLocalTimestamp:(double)arg1;
- (void)setSuggestionType:(int)arg1;
- (void)setViewportInfo:(id)arg1;
- (int)suggestionType;
- (id)suggestionTypeAsString:(int)arg1;
- (id)viewportInfo;
- (void)writeTo:(id)arg1;

@end
