/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/QuickLook.framework/QuickLook
 */

@interface _QLFileCoordinatorDownloadOperation : _QLDownloadOperation {
    NSFileCoordinator * _fileCoordinator;
    id  _progressSubscriber;
}

- (void).cxx_destruct;
- (bool)canBeCanceled;
- (bool)cancel;
- (void)dealloc;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;
- (bool)performDownload;

@end
