/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/QuickLook.framework/QuickLook
 */

@interface QLSlideTransitionDriver : QLTransitionDriver

- (void)animateFinishTransition;
- (void)animateTransition;
- (void)tearDown;

@end
