/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CacheDelete.framework/CacheDelete
 */

@interface CacheDeleteRecentServiceInfo : CacheDeleteRecent <NSCopying, NSSecureCoding> {
    NSMutableDictionary * _amounts;
    NSMutableDictionary * _diagnostics;
    NSDate * _timestamp;
}

@property (nonatomic, retain) NSMutableDictionary *amounts;
@property (nonatomic, retain) NSMutableDictionary *diagnostics;
@property (nonatomic, retain) NSDate *timestamp;

+ (id)cacheDeleteRecentServiceInfo:(id)arg1 atUrgency:(id)arg2 pushed:(bool)arg3;
+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)amountForUrgency:(id)arg1;
- (id)amounts;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)diagnostics;
- (id)diagnosticsForUrgency:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithAmount:(id)arg1 atUrgency:(id)arg2 pushed:(bool)arg3;
- (id)initWithCoder:(id)arg1;
- (void)log;
- (void)setAmounts:(id)arg1;
- (void)setDiagnostics:(id)arg1;
- (void)setTimestamp:(id)arg1;
- (id)timestamp;
- (void)updateAmount:(id)arg1 forUrgency:(id)arg2;
- (void)updateDiagnostics:(id)arg1 forUrgency:(id)arg2;
- (bool)validate:(double)arg1;

@end
