/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/FuseUI.framework/FuseUI
 */

@interface MusicAVPlayer : RURadioAVPlayer <MPNowPlayingPlaybackQueueDataSource> {
    bool  _isSubscribed;
    MPPlaybackContext * _lastPlaybackContext;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

+ (Class)playlistManagerClass;
+ (id)sharedAVPlayer;

- (void).cxx_destruct;
- (void)_connectAVPlayer;
- (id)_expectedAssetTypesForPlaybackMode:(long long)arg1;
- (id)_fallbackMusicPlaybackContext;
- (void)_handlePlaybackQueueChangedNotification;
- (void)_initiateMusicPlayback;
- (void)_musicPlayer_defaultsDidChangeNotification:(id)arg1;
- (void)_registerPlaybackQueueDataSource;
- (bool)_shouldVendContentItemForOffset:(long long)arg1;
- (void)_streamingDownloadSessionControllerDidFailDownloadSessionNotification:(id)arg1;
- (void)_subscriptionStatusDidChangeNotification;
- (void)_unregisterPlaybackQueueDataSource;
- (void)beginOrTogglePlayback;
- (void)beginPlayback;
- (id)contentItemForOffset:(long long)arg1;
- (id)contentItemIdentifierForOffset:(long long)arg1;
- (void)dealloc;
- (bool)hasVolumeControl;
- (id)init;
- (void)reloadWithPlaybackContext:(id)arg1;
- (void)reloadWithPlaybackContext:(id)arg1 completionHandler:(id /* block */)arg2;
- (void)seekAlbum:(int)arg1;
- (void)seekPlaylist:(int)arg1;

@end
